// data.ts
const data = [
  {
    name: "MySelf",
    "data set 1": [
      {
        name: "Positive" as const,
        sentence: [
          "Does he take photographs? Yes .<br />Is he taking a photograph? No,he isn’t. <br />What is he doing? He's having a bath.",
          "Is she driving a bus? No, She isn't. <br />Does she drive a bus? Yes.<br />What is she doing? She's playing a piano.",
          "Does he clean windows? Yes <br />Is he cleaning a window? Yes <br />What is he doing? He's cleaning a window.",
          "Are they teaching? No, they aren't.  <br />Do they teach? Yes.<br />What do they do? They are watching TV.",
          "Does he drive a taxi? Yes.<br />Is he driving a taxi? No, he isn’t.<br />What is he doing? He’s fixing his car.",
          "Does he go fishing? Yes.<br />Is he fishing now? No, he isn’t.<br />What is he doing? He’s repairing his fishing rod.",
          "Does he play basketball? Yes.<br />Is he playing basketball? No, he isn’t.<br />What is he doing? He’s lifting weights.",
          "Does he play chess? Yes.<br />Is he playing chess? No, he isn’t.<br />What is he doing? He’s reading a newspaper.",
          "Does he play football? Yes.<br />Is he playing football? No, he isn’t.<br />What is he doing? He’s jogging in the park.",
          "Does he play golf? Yes.<br />Is he playing golf? No, he isn’t.<br />What is he doing? He’s practicing his swing.",
          "Does he play tennis? Yes<br />Is he playing tennis? No, he isn’t.<br />What is he doing? He’s jogging.",
          "Does he play the accordion? Yes.<br />Is he playing the accordion? No, he isn’t.<br />What is he doing? He’s repairing his accordion.",
          "Does he play the bass guitar? Yes.<br />Is he playing the bass guitar? No, he isn’t.<br />What is he doing? He’s tuning his bass guitar.",
          "Does he play the cello? Yes. <br />Is he playing the cello? No, he isn’t. <br />What is he doing? He’s tuning his cello.",
          "Does he play the clarinet? Yes. <br />Is he playing the clarinet? No, he isn’t. <br />What is he doing? He’s practicing scales.",
          "Does he play the drums? Yes. <br />Is he playing the drums? No, he isn’t. <br />What is he doing? He’s tuning his guitar.",
          "Does he play the flute? Yes. <br />Is he playing the flute? No, he isn’t. <br />What is he doing? He’s reading sheet music.",
          "Does he play the French horn? Yes. <br />Is he playing the French horn? No, he isn’t. <br />What is he doing? He’s practicing scales.",
          "Does he play the guitar? Yes. <br />Is he playing the guitar? No, he isn’t. <br />What is he doing? He’s watching TV.",
          "Does he play the harmonica? Yes. <br />Is he playing the harmonica? No, he isn’t. <br />What is he doing? He’s practicing scales.",
          "Does he play the harp? Yes. <br />Is he playing the harp? No, he isn’t. <br />What is he doing? He’s tuning his harp.",
          "Does he play the oboe? Yes. <br />Is he playing the oboe? No, he isn’t. <br />What is he doing? He’s cleaning his oboe.",
          "Does he play the piccolo? Yes. <br />Is he playing the piccolo? No, he isn’t.",
          "Does he play the trumpet? Yes. <br />Is he playing the trumpet? No, he isn’t. <br />What is he doing? He’s polishing his trumpet.",
          "Does he play the tuba? Yes. <br />Is he playing the tuba? No, he isn’t. <br />What is he doing? He’s polishing his tuba.",
          "Does he play video games? Yes. <br />Is he playing video games? No, he isn’t. <br />What is he doing? He’s doing homework.",
          "Does he read books? Yes. <br />Is he reading a book? No, he isn’t. <br />What is he doing? He’s cooking dinner.",
          "Does he swim every day? Yes. <br />Is he swimming now? No, he isn’t. <br />What is he doing? He’s taking a nap.",
          "Does he write poems? Yes. <br />Is he writing a poem? No, he isn’t. <br />What is he doing? He’s drawing a picture.",
          "Does she bake bread? Yes. <br />Is she baking bread? No, she isn’t. <br />What is she doing? She’s making a cake.",
          "Does she bake cakes? Yes. <br />Is she baking a cake? No, she isn’t. <br />What is she doing? She’s cleaning the kitchen.",
          "Does she bake muffins? Yes. <br />Is she baking muffins? No, she isn’t. <br />What is she doing? She’s making cupcakes.",
          "Does she bake pies? Yes. <br />Is she baking a pie? No, she isn’t. <br />What is she doing? She’s making cookies.",
          "Does she cook Italian food? Yes. <br />Is she cooking Italian food? No, she isn’t. <br />What is she doing? She’s baking cookies.",
          "Does she dance ballet? Yes. <br />Is she dancing ballet? No, she isn’t. <br />What is she doing? She’s stretching.",
          "Does she draw cartoons? Yes. <br />Is she drawing a cartoon? No, she isn’t. <br />What is she doing? She’s painting a mural.",
          "Does she garden on weekends? Yes. <br />Is she gardening now? No, she isn’t. <br />What is she doing? She’s reading a magazine.",
          "Does she knit sweaters? Yes. <br />Is she knitting a sweater? No, she isn’t. <br />What is she doing? She’s watching a movie.",
          "Does she paint landscapes? Yes. <br />Is she painting a landscape? No, she isn’t. <br />What is she doing? She’s sketching.",
          "Does she paint pictures? Yes. <br />Is she painting a picture? No, she isn’t. <br />What is she doing? She’s reading a book.",
          "Does she play the violin? Yes. <br />Is she playing the violin? No, she isn’t. <br />What is she doing? She’s listening to music.",
          "Does she sew clothes? Yes. <br />Is she sewing clothes? No, she isn’t. <br />What is she doing? She’s knitting a scarf.",
          "Does she sew dresses? Yes. <br />Is she sewing a dress? No, she isn’t. <br />What is she doing? She’s designing a pattern.",
          "Does she sew quilts? Yes. <br />Is she sewing a quilt? No, she isn’t. <br />What is she doing? She’s cutting fabric.",
          "Does she sing in a choir? Yes. <br />Is she singing in a choir? No, she isn’t. <br />What is she doing? She’s practicing piano.",
          "Does she teach English? Yes. <br />Is she teaching English? No, she isn’t. <br />What is she doing? She’s grading papers.",
          "Does she write articles? Yes. <br />Is she writing an article? No, she isn’t. <br />What is she doing? She’s editing a draft.",
          "Does she write blogs? Yes. <br />Is she writing a blog? No, she isn’t. <br />What is she doing? She’s brainstorming ideas.",
          "Does she write letters? Yes. <br />Is she writing a letter? No, she isn’t. <br />What is she doing? She’s talking on the phone.",
          "Does she write music? Yes. <br />Is she writing music? No, she isn’t. <br />What is she doing? She’s playing the piano.",
          "Does she write novels? Yes. <br />Is she writing a novel? No, she isn’t. <br />What is she doing? She’s outlining a plot.",
          "Does she write poetry? Yes. <br />Is she writing poetry? No, she isn’t. <br />What is she doing? She’s reading a book.",
          "Does she write scripts? Yes. <br />Is she writing a script? No, she isn’t. <br />What is she doing? She’s brainstorming ideas.",
          "Does she write stories? Yes. <br />Is she writing a story? No, she isn’t. <br />What is she doing? She’s reading a novel."
        ]
        
        },
    ],
    "data set 2": [
      {
        name: "Positive" as const,
        sentence: [
          "Excuse me, do you speak English?",
          "‘Where’s Kate?’ ‘I don’t know.’",
          "What’s funny? Why are you laughing?",
          "‘What does your sister do?’ ‘She’s a dentist.’",
          "It isn’t raining. I want to go out in the rain.",
          "‘Where do you come from?’ ‘Canada.’",
          "How much does it cost to stay at this hotel? Is it expensive?",
          "Steve is a good tennis player, but he doesn’t play very often.",
          "Excuse me, do you have the time?",
          "‘Where’s John?’ ‘I don’t know.’",
          "What’s wrong? Why are you crying?",
          "‘What does your brother do?’ ‘He’s a teacher.’",
          "It isn’t snowing. I want to go out in the snow.",
          "‘Where do you live?’ ‘Islamabad.’",
          "How much does it cost to buy this book? Is it expensive?",
          "Mary is a good singer, but she doesn’t sing very often.",
          "Excuse me, do you know the way to the station?",
          "‘Where’s the bathroom?’ ‘I don’t know.’",
          "What’s happening? Why are you shouting?",
          "‘What does your father do?’ ‘He’s a lawyer.’",
          "It isn’t windy. I want to fly a kite.",
          "‘Where do you work?’ ‘At a bank.’",
          "How much does it cost to rent a car? Is it affordable?",
          "Tom is a good cook, but he doesn’t cook very often.",
          "Excuse me, do you have a pen?",
          "‘Where’s the library?’ ‘I don’t know.’",
          "What’s the matter? Why are you upset?",
          "‘What does your mother do?’ ‘She’s a nurse.’",
          "It isn’t sunny. I want to go to the beach.",
          "‘Where do you study?’ ‘At university.’",
          "How much does it cost to join the gym? Is it reasonable?",
          "Anna is a good dancer, but she doesn’t dance very often.",
          "Excuse me, do you have a map?",
          "‘Where’s the nearest café?’ ‘I don’t know.’",
          "What’s the problem? Why are you angry?",
          "‘What does your friend do?’ ‘He’s an engineer.’",
          "It isn’t cold. I want to wear my new coat.",
          "‘Where do you shop?’ ‘At the mall.’",
          "How much does it cost to buy a ticket? Is it cheap?",
          "Jack is a good writer, but he doesn’t write very often.",
          "Excuse me, do you have a light?",
          "‘Where’s the exit?’ ‘I don’t know.’",
          "What’s going on? Why are you laughing?",
          "‘What does your cousin do?’ ‘She’s a chef.’",
          "It isn’t hot. I want to go swimming.",
          "‘Where do you eat?’ ‘At home.’",
          "How much does it cost to get a haircut? Is it pricey?",
          "Sara is a good artist, but she doesn’t paint very often.",
          "Excuse me, do you have change for a dollar?",
          "‘Where’s the park?’ ‘I don’t know.’",
          "What’s the issue? Why are you silent?",
          "‘What does your uncle do?’ ‘He’s a pilot.’",
          "It isn’t foggy. I want to drive.",
          "‘Where do you exercise?’ ‘At the gym.’",
          "How much does it cost to buy groceries? Is it expensive?",
          "Mike is a good swimmer, but he doesn’t swim very often.",
          "Excuse me, do you have a moment?",
          "‘Where’s the bus stop?’ ‘I don’t know.’",
          "What’s the news? Why are you excited?",
          "‘What does your aunt do?’ ‘She’s a scientist.’",
          "It isn’t stormy. I want to go for a walk.",
          "‘Where do you relax?’ ‘At the park.’",
          "How much does it cost to buy a house? Is it affordable?",
          "Lucy is a good photographer, but she doesn’t take photos very often.",
          "Excuse me, do you have a spare ticket?",
          "‘Where’s the theater?’ ‘I don’t know.’",
          "What’s the plan? Why are you confused?",
          "‘What does your neighbor do?’ ‘He’s a mechanic.’",
          "It isn’t humid. I want to go hiking.",
          "‘Where do you hang out?’ ‘At the café.’",
          "How much does it cost to buy a laptop? Is it expensive?",
          "David is a good guitarist, but he doesn’t play very often.",
          "Excuse me, do you have a charger?",
          "‘Where’s the museum?’ ‘I don’t know.’",
          "What’s the story? Why are you smiling?",
          "‘What does your boss do?’ ‘He’s a manager.’",
          "It isn’t cloudy. I want to see the stars.",
          "‘Where do you travel?’ ‘To Europe.’",
          "How much does it cost to buy a car? Is it costly?",
          "Emma is a good singer, but she doesn’t sing very often.",
          "Excuse me, do you have a tissue?",
          "‘Where’s the supermarket?’ ‘I don’t know.’",
          "What’s the reason? Why are you nervous?",
          "‘What does your teacher do?’ ‘He’s a professor.’",
          "It isn’t windy. I want to fly a kite.",
          "‘Where do you stay?’ ‘At a hotel.’",
          "How much does it cost to buy a phone? Is it expensive?",
          "Chris is a good actor, but he doesn’t act very often.",
          "Excuse me, do you have a minute?",
          "‘Where’s the pharmacy?’ ‘I don’t know.’",
          "What’s the occasion? Why are you dressed up?",
          "‘What does your friend do?’ ‘She’s a designer.’",
          "It isn’t raining. I want to go for a run.",
          "‘Where do you park?’ ‘In the garage.’",
          "How much does it cost to buy a bike? Is it affordable?",
          "Liam is a good speaker, but he doesn’t speak very often.",
          "Excuse me, do you have a map?",
          "‘Where’s the bakery?’ ‘I don’t know.’",
          "What’s the deal? Why are you so quiet?",
          "‘What does your colleague do?’ ‘He’s an architect.’",
          "It isn’t snowing. I want to build a snowman.",
          "‘Where do you shop?’ ‘At the market.’",
          "How much does it cost to buy a ticket? Is it cheap?",
          "Olivia is a good writer, but she doesn’t write very often.",
          "Excuse me, do you have a pen?",
          "‘Where’s the post office?’ ‘I don’t know.’",
          "What’s the problem? Why are you so upset?",
          "‘What does your neighbor do?’ ‘She’s a nurse.’"
      ]
      
        
         },
    ],
    "data set 3": [
      {
        name: "Positive" as const,
        sentence: [
          "Excuse me, do you speak English?",
          "‘Where’s Tom?’ ‘He is having a shower.’",
          "I don’t watch TV very often.",
          "Listen! Somebody is singing.",
          "Sarah is tired. She wants to go home now.",
          "How often do you use your car? Every day?",
          "‘Excuse me, but you are sitting in my seat.’ ‘Oh, I’m sorry.’",
          "I’m sorry, I don’t understand. Can you speak more slowly?",
          "It’s late. I am going home now. Are you coming with me?",
          "What time does your father finish work every day?",
          "You can turn off the radio. I am not listening to it.",
          "‘Where’s Paul?’ ‘In the kitchen. He is cooking something.’",
          "Mark doesn’t usually drive to work. He usually walks.",
          "Sue doesn’t like coffee. She prefers tea.",
          "Excuse me, do you have a pen?",
          "‘Where’s Sarah?’ ‘She is reading a book.’",
          "I don’t eat meat very often.",
          "Look! The cat is climbing the tree.",
          "John is hungry. He wants to eat something.",
          "How often do you go to the gym? Every week?",
          "‘Excuse me, but you are blocking my view.’ ‘Oh, I’m sorry.’",
          "I’m sorry, I don’t remember your name.",
          "It’s getting late. I am leaving now. Are you staying here?",
          "What time does the train arrive every day?",
          "You can close the window. I am not feeling cold.",
          "‘Where’s Mike?’ ‘In the garage. He is fixing his car.’",
          "Anna doesn’t usually eat breakfast. She usually drinks coffee.",
          "Tom doesn’t like tea. He prefers coffee.",
          "Excuse me, do you know the time?",
          "‘Where’s Emma?’ ‘She is talking on the phone.’",
          "I don’t go to the cinema very often.",
          "Listen! The birds are singing.",
          "Lisa is tired. She wants to rest.",
          "How often do you travel abroad? Every year?",
          "‘Excuse me, but you are standing on my foot.’ ‘Oh, I’m sorry.’",
          "I’m sorry, I don’t understand this question.",
          "It’s dark. I am turning on the light. Are you staying here?",
          "What time does the shop open every day?",
          "You can turn off the TV. I am not watching it.",
          "‘Where’s Jane?’ ‘In the kitchen. She is baking a cake.’",
          "Mark doesn’t usually drink soda. He usually drinks water.",
          "Sue doesn’t like chocolate. She prefers fruit.",
          "Excuse me, do you have a map?",
          "‘Where’s the dog?’ ‘It is sleeping in its bed.’",
          "I don’t read newspapers very often.",
          "Watch out! The car is coming.",
          "David is thirsty. He wants a drink.",
          "How often do you visit your family? Every month?",
          "‘Excuse me, but you are using my pen.’ ‘Oh, I’m sorry.’",
          "I’m sorry, I don’t know the answer.",
          "It’s raining. I am taking an umbrella. Are you coming with me?",
          "What time does the bus leave every day?",
          "You can turn off the light. I am not reading.",
          "‘Where’s Peter?’ ‘In the garden. He is planting flowers.’",
          "Lucy doesn’t usually wear jeans. She usually wears dresses.",
          "Tom doesn’t like fish. He prefers chicken.",
          "Excuse me, do you have a ticket?",
          "‘Where’s the cat?’ ‘It is hiding under the bed.’",
          "I don’t drink coffee very often.",
          "Look! The children are playing in the park.",
          "Sarah is cold. She wants a blanket.",
          "How often do you exercise? Every day?",
          "‘Excuse me, but you are sitting in my seat.’ ‘Oh, I’m sorry.’",
          "I’m sorry, I don’t hear you. Can you repeat that?",
          "It’s late. I am going to bed. Are you staying up?",
          "What time does the movie start every day?",
          "You can turn off the fan. I am not hot.",
          "‘Where’s John?’ ‘In the living room. He is watching TV.’",
          "Anna doesn’t usually eat lunch. She usually eats dinner.",
          "Sue doesn’t like milk. She prefers juice.",
          "Excuse me, do you have a phone charger?",
          "‘Where’s the baby?’ ‘It is sleeping in the crib.’",
          "I don’t write letters very often.",
          "Listen! The wind is blowing.",
          "John is hungry. He wants a sandwich.",
          "How often do you clean your house? Every week?",
          "‘Excuse me, but you are blocking the door.’ ‘Oh, I’m sorry.’",
          "I’m sorry, I don’t believe you.",
          "It’s sunny. I am wearing sunglasses. Are you coming with me?",
          "What time does the train depart every day?",
          "You can turn off the heater. I am not cold.",
          "‘Where’s Lisa?’ ‘In the bathroom. She is brushing her teeth.’",
          "Mark doesn’t usually drink coffee. He usually drinks tea.",
          "Tom doesn’t like vegetables. He prefers meat.",
          "Excuse me, do you have a spare key?",
          "‘Where’s the bird?’ ‘It is flying in the sky.’",
          "I don’t use my phone very often.",
          "Watch out! The dog is barking.",
          "David is tired. He wants to sleep.",
          "How often do you read books? Every month?",
          "‘Excuse me, but you are standing in my way.’ ‘Oh, I’m sorry.’",
          "I’m sorry, I don’t recognize you.",
          "It’s cold. I am wearing a coat. Are you coming with me?",
          "What time does the store close every day?",
          "You can turn off the music. I am not listening to it.",
          "‘Where’s Emma?’ ‘In the kitchen. She is making dinner.’",
          "Lucy doesn’t usually wear makeup. She usually goes natural.",
          "Tom doesn’t like soda. He prefers water.",
          "Excuse me, do you have a moment?",
          "‘Where’s the fish?’ ‘It is swimming in the tank.’",
          "I don’t go to the gym very often.",
          "Listen! The rain is falling.",
          "Sarah is thirsty. She wants a drink.",
          "How often do you visit your friends? Every week?",
          "‘Excuse me, but you are using my computer.’ ‘Oh, I’m sorry.’",
          "I’m sorry, I don’t remember your face.",
          "It’s getting late. I am leaving now. Are you staying here?",
          "What time does the bus arrive every day?",
          "You can turn off the radio. I am not listening to it.",
          "‘Where’s Paul?’ ‘In the kitchen. He is cooking something.’",
          "Mark doesn’t usually drive to work. He usually walks.",
          "Sue doesn’t like coffee. She prefers tea.",
          "Excuse me, do you have a map?",
          "‘Where’s the dog?’ ‘It is sleeping in its bed.’"
      ]
      
        },
    ],
    "data set 4": [
      {
        name: "Positive" as const,
        sentence: [
          "‘Do you speak English?’ ‘Yes, a little.’",
          "Sometimes we go away at weekends.",
          "It’s a nice day today. The sun is shining.",
          "(You meet Kate in the street.) Hello, Kate. Where are you going?",
          "How often do you go on holiday?",
          "Emily is a writer. She writes books for children.",
          "I never read newspapers.",
          "‘Where are Mark and Laura?’ ‘They’re watching TV in the living room.’",
          "Helen is in her office. She’s talking to somebody.",
          "What time do you usually have dinner?",
          "Joe isn’t at home at the moment. He’s visiting some friends.",
          "‘Would you like some tea?’ ‘No, thank you. I don’t drink tea.’",
          "‘Do you play the piano?’ ‘Yes, a little.’",
          "Sometimes we go hiking in the mountains.",
          "It’s a beautiful evening. The stars are shining.",
          "(You see John at the park.) Hi, John. Where are you going?",
          "How often do you visit your grandparents?",
          "Michael is a chef. He cooks delicious meals.",
          "I rarely watch movies.",
          "‘Where are Sarah and Tom?’ ‘They’re playing in the garden.’",
          "David is in his room. He’s reading a book.",
          "What time do you usually wake up?",
          "Anna isn’t at school today. She’s visiting her grandmother.",
          "‘Would you like some coffee?’ ‘No, thank you. I don’t drink coffee.’",
          "‘Do you like chocolate?’ ‘Yes, very much.’",
          "Sometimes we go swimming in the lake.",
          "It’s a warm afternoon. The birds are singing.",
          "(You see Emma at the store.) Hi, Emma. What are you buying?",
          "How often do you go to the gym?",
          "Lisa is a teacher. She teaches math.",
          "I never eat fast food.",
          "‘Where are Jack and Jill?’ ‘They’re studying in the library.’",
          "Helen is in the kitchen. She’s baking a cake.",
          "What time do you usually go to bed?",
          "Tom isn’t at work today. He’s helping his friend move.",
          "‘Would you like some water?’ ‘No, thank you. I’m not thirsty.’",
          "‘Do you play soccer?’ ‘Yes, every weekend.’",
          "Sometimes we go camping in the forest.",
          "It’s a chilly morning. The wind is blowing.",
          "(You see Mike at the gym.) Hi, Mike. What are you doing?",
          "How often do you read books?",
          "Sarah is a doctor. She helps people.",
          "I rarely drink soda.",
          "‘Where are Ben and Lucy?’ ‘They’re shopping at the mall.’",
          "Mark is in the garage. He’s fixing his bike.",
          "What time do you usually start work?",
          "Jane isn’t at home right now. She’s visiting her aunt.",
          "‘Would you like some juice?’ ‘No, thank you. I don’t like juice.’",
          "‘Do you play chess?’ ‘Yes, sometimes.’",
          "Sometimes we go fishing at the river.",
          "It’s a foggy day. The mist is rising.",
          "(You see Alice at the café.) Hi, Alice. What are you drinking?",
          "How often do you go to the movies?",
          "John is a lawyer. He works in an office.",
          "I never eat breakfast.",
          "‘Where are Sam and Emma?’ ‘They’re walking in the park.’",
          "Laura is in the garden. She’s planting flowers.",
          "What time do you usually finish work?",
          "Peter isn’t at the office today. He’s attending a conference.",
          "‘Would you like some milk?’ ‘No, thank you. I’m lactose intolerant.’",
          "‘Do you play basketball?’ ‘Yes, with my friends.’",
          "Sometimes we go skiing in the winter.",
          "It’s a rainy afternoon. The rain is pouring.",
          "(You see Tom at the library.) Hi, Tom. What are you reading?",
          "How often do you visit the museum?",
          "Emily is an artist. She paints beautiful pictures.",
          "I rarely drink coffee.",
          "‘Where are Kate and John?’ ‘They’re having lunch at a restaurant.’",
          "David is in the living room. He’s watching a movie.",
          "What time do you usually leave the house?",
          "Anna isn’t at the gym today. She’s feeling sick.",
          "‘Would you like some bread?’ ‘No, thank you. I’m on a diet.’",
          "‘Do you play the guitar?’ ‘Yes, every day.’",
          "Sometimes we go running in the park.",
          "It’s a snowy evening. The snow is falling.",
          "(You see Sarah at the market.) Hi, Sarah. What are you buying?",
          "How often do you go to the beach?",
          "Michael is a musician. He plays the piano.",
          "I never drink alcohol.",
          "‘Where are Lisa and Tom?’ ‘They’re dancing at the club.’",
          "Helen is in the office. She’s writing a report.",
          "What time do you usually get home?",
          "Tom isn’t at the park today. He’s studying for an exam.",
          "‘Would you like some soup?’ ‘No, thank you. I’m not hungry.’",
          "‘Do you play video games?’ ‘Yes, in my free time.’",
          "Sometimes we go biking in the countryside.",
          "It’s a windy day. The leaves are falling.",
          "(You see John at the bus stop.) Hi, John. Where are you going?",
          "How often do you visit your friends?",
          "Lisa is a nurse. She takes care of patients.",
          "I rarely eat dessert.",
          "‘Where are Mark and Anna?’ ‘They’re jogging in the park.’",
          "David is in the kitchen. He’s making dinner.",
          "What time do you usually wake up?",
          "Anna isn’t at the store today. She’s working from home.",
          "‘Would you like some ice cream?’ ‘No, thank you. I’m full.’",
          "‘Do you play the drums?’ ‘Yes, in a band.’",
          "Sometimes we go sailing on the lake.",
          "It’s a cloudy morning. The sky is grey.",
          "(You see Emma at the gym.) Hi, Emma. What are you doing?",
          "How often do you read the newspaper?",
          "Sarah is a scientist. She conducts experiments.",
          "I never drink tea.",
          "‘Where are Ben and Lucy?’ ‘They’re shopping at the mall.’",
          "Mark is in the garage. He’s fixing his car.",
          "What time do you usually start work?",
          "Jane isn’t at home right now. She’s visiting her aunt.",
          "‘Would you like some juice?’ ‘No, thank you. I don’t like juice.’",
          "‘Do you play chess?’ ‘Yes, sometimes.’",
          "Sometimes we go fishing at the river.",
          "It’s a foggy day. The mist is rising.",
          "(You see Alice at the café.) Hi, Alice. What are you drinking?"
      ]      
      },
    ],
    "data set 5": [
      {
        name: "Positive" as const,
        sentence: [
          "Please be quiet. I’m working.",
          "Do you often go to the cinema?",
          "What are you cooking?",
          "Jack plays the piano very well.",
          "I'm going now. Goodbye!",
          "It's raining. Can I take this umbrella?",
          "I don't watch TV very much.",
          "Excuse me, we're looking for the museum.",
          "What's this word? How do you pronounce it?",
          "Please turn down the music. I’m studying.",
          "Do you often read books?",
          "What are you reading?",
          "Sarah sings beautifully.",
          "I’m leaving now. See you later!",
          "It’s snowing. Can I borrow your coat?",
          "I don’t play video games often.",
          "Excuse me, we’re searching for the library.",
          "What’s this phrase? How do you say it?",
          "Please be quiet. I’m on a call.",
          "Do you often go hiking?",
          "What are you writing?",
          "Tom paints very well.",
          "I’m heading out. Take care!",
          "It’s windy. Can I use your scarf?",
          "I don’t eat out very much.",
          "Excuse me, we’re looking for the train station.",
          "What’s this sentence? How do you read it?",
          "Please lower your voice. I’m trying to concentrate.",
          "Do you often travel?",
          "What are you drawing?",
          "Emily dances gracefully.",
          "I’m off now. Bye!",
          "It’s hot. Can I have some water?",
          "I don’t go to parties often.",
          "Excuse me, we’re searching for the post office.",
          "What’s this letter? How do you spell it?",
          "Please be silent. I’m meditating.",
          "Do you often swim?",
          "What are you making?",
          "John writes poetry beautifully.",
          "I’m heading out. See you soon!",
          "It’s cold. Can I borrow your gloves?",
          "I don’t drink coffee often.",
          "Excuse me, we’re looking for the bus stop.",
          "What’s this number? How do you read it?",
          "Please be quiet. I’m on a video call.",
          "Do you often go jogging?",
          "What are you knitting?",
          "Anna plays the violin wonderfully.",
          "I’m leaving now. Take care!",
          "It’s raining. Can I use your raincoat?",
          "I don’t eat sweets often.",
          "Excuse me, we’re searching for the pharmacy.",
          "What’s this symbol? How do you pronounce it?",
          "Please keep it down. I’m working.",
          "Do you often go cycling?",
          "What are you baking?",
          "David plays the guitar excellently.",
          "I’m off now. Goodbye!",
          "It’s sunny. Can I borrow your sunglasses?",
          "I don’t drink soda often.",
          "Excuse me, we’re looking for the supermarket.",
          "What’s this character? How do you say it?",
          "Please be quiet. I’m reading.",
          "Do you often go fishing?",
          "What are you sewing?",
          "Lucy sings very well.",
          "I’m heading out. See you later!",
          "It’s chilly. Can I use your hat?",
          "I don’t watch movies often.",
          "Excuse me, we’re searching for the bakery.",
          "What’s this word? How do you spell it?",
          "Please lower your voice. I’m on a call.",
          "Do you often go to concerts?",
          "What are you designing?",
          "Mike plays the drums skillfully.",
          "I’m leaving now. See you soon!",
          "It’s foggy. Can I borrow your flashlight?",
          "I don’t eat fast food often.",
          "Excuse me, we’re looking for the hospital.",
          "What’s this phrase? How do you read it?",
          "Please be silent. I’m thinking.",
          "Do you often go to the gym?",
          "What are you crafting?",
          "Emma dances beautifully.",
          "I’m off now. Take care!",
          "It’s humid. Can I have a fan?",
          "I don’t drink alcohol often.",
          "Excuse me, we’re searching for the cinema.",
          "What’s this sentence? How do you say it?",
          "Please keep it down. I’m studying.",
          "Do you often go to the beach?",
          "What are you building?",
          "James plays the saxophone wonderfully.",
          "I’m heading out. Goodbye!",
          "It’s freezing. Can I borrow your jacket?",
          "I don’t eat meat often.",
          "Excuse me, we’re looking for the park.",
          "What’s this letter? How do you pronounce it?",
          "Please be quiet. I’m writing.",
          "Do you often go to the library?",
          "What are you painting?",
          "Sophie sings very well.",
          "I’m leaving now. See you later!",
          "It’s stormy. Can I use your umbrella?",
          "I don’t drink milk often.",
          "Excuse me, we’re searching for the hotel.",
          "What’s this number? How do you say it?",
          "Please lower your voice. I’m on a meeting."
      ]      
      },
    ],
   
  },
];

export default data;
