// data.ts
const data = [
  {
    name: "MySelf",
    "data set 1": [
      {
        name: "Positive" as const,
        sentence: [
          "She reads.",
          "He thinks.",
          "It flies.",
          "He dances.",
          "It finishes.",
          "She has.",
          "She walks.",
          "He jumps.",
          "It spins.",
          "He laughs.",
          "She sings.",
          "It shines.",
          "He runs.",
          "She whispers.",
          "It falls.",
          "He cooks.",
          "She studies.",
          "It melts.",
          "He drives.",
          "She paints.",
          "It grows.",
          "He writes.",
          "She listens.",
          "It roars.",
          "He smiles.",
          "She waits.",
          "It cools.",
          "He dreams.",
          "She knits.",
          "It opens.",
          "He watches.",
          "She prays.",
          "It fades.",
          "He fights.",
          "She dances.",
          "It barks.",
          "He reads.",
          "She sews.",
          "It rains.",
          "He yawns.",
          "She eats.",
          "It shakes.",
          "He talks.",
          "She cleans.",
          "It burns.",
          "He sleeps.",
          "She cries.",
          "It buzzes.",
          "He listens.",
          "She types.",
          "It flows.",
          "He plays.",
          "She drinks.",
          "It spins.",
          "He stares.",
          "She laughs.",
          "It floats.",
          "He kneels.",
          "She teaches.",
          "It breaks.",
          "He fixes.",
          "She plans.",
          "It moves.",
          "He plants.",
          "She travels.",
          "It glows.",
          "He kneads.",
          "She works.",
          "It lands.",
          "He trims.",
          "She shops.",
          "It cracks.",
          "He sweeps.",
          "She dances.",
          "It freezes.",
          "He molds.",
          "She thinks.",
          "It runs.",
          "He prays.",
          "She cares.",
          "It flies.",
          "He lifts.",
          "She folds.",
          "It jumps.",
          "He sings.",
          "She packs.",
          "It blinks.",
          "He repairs.",
          "She visits.",
          "It bubbles.",
          "He learns.",
          "She serves.",
          "It dries.",
          "He hunts.",
          "She reads.",
          "It sparks.",
          "He sculpts.",
          "She hugs.",
          "It spins.",
          "He feeds.",
          "She grows.",
          "It climbs.",
          "He mixes.",
          "She teaches.",
          "It laughs.",
          "He listens."
        ]
        
      },
    ],
    "data set 2": [
      {
        name: "Positive" as const,
        sentence: [
          "He plays the piano.",
          "They live in a very big house.",
          "She eats a lot of fruits.",
          "He plays tennis.",
          "They go to the cinema a lot.",
          "He sleeps seven hours a night.",
          "She walks her dog every morning.",
          "They visit their grandparents every Sunday.",
          "He reads a book before bed.",
          "She watches TV in the evenings.",
          "They travel to Europe every summer.",
          "He drinks coffee in the morning.",
          "She practices yoga every day.",
          "They go hiking on weekends.",
          "He writes in his journal daily.",
          "She cooks dinner for her family.",
          "They play chess on Friday nights.",
          "He exercises at the gym every morning.",
          "She listens to music while studying.",
          "They go to the beach every summer.",
          "He studies for his exams every night.",
          "She paints in her free time.",
          "They attend church every Sunday.",
          "He drives to work every day.",
          "She gardens in her backyard.",
          "They swim in the pool during summer.",
          "He runs in the park every morning.",
          "She bakes cookies on weekends.",
          "They take a walk after dinner.",
          "He works on his computer all day.",
          "She reads the newspaper in the morning.",
          "They have dinner at 7 PM.",
          "He watches movies on Netflix.",
          "She sings in the choir every Sunday.",
          "They clean the house every Saturday.",
          "He rides his bike to school.",
          "She writes letters to her friends.",
          "They play video games after school.",
          "He mows the lawn every weekend.",
          "She does laundry on Mondays.",
          "They shop for groceries every Friday.",
          "He brushes his teeth twice a day.",
          "She calls her mom every evening.",
          "They take the bus to work.",
          "He checks his email every morning.",
          "She meditates in the morning.",
          "They cook together on weekends.",
          "He practices the guitar every day.",
          "She knits scarves in winter.",
          "They dance at parties.",
          "He reads the Bible every day.",
          "She drinks tea in the afternoon.",
          "They eat out every Friday.",
          "He writes poetry in his free time.",
          "She rides horses on weekends.",
          "They watch sports on TV.",
          "He goes fishing on weekends.",
          "She paints landscapes in oils.",
          "They study together for exams.",
          "He volunteers at the shelter.",
          "She practices the violin daily.",
          "They go jogging in the morning.",
          "He takes photos during vacations.",
          "She waters the plants every morning.",
          "They visit museums on weekends.",
          "He attends night classes twice a week.",
          "She decorates the house for holidays.",
          "They picnic in the park every Sunday.",
          "He takes the train to the city.",
          "She organizes charity events.",
          "They jog along the beach.",
          "He plays soccer every Saturday.",
          "She learns new languages online.",
          "They host dinner parties monthly.",
          "He reads science fiction novels.",
          "She cooks Italian food often.",
          "They attend concerts together.",
          "He plays golf on Sundays.",
          "She collects stamps from around the world.",
          "They participate in community events.",
          "He builds model airplanes.",
          "She teaches English to kids.",
          "They go camping every summer.",
          "He learns to play the piano.",
          "She makes pottery at a studio.",
          "They visit art galleries often.",
          "He brews his own beer.",
          "She walks in the park after work.",
          "They go skiing every winter.",
          "He writes code for fun.",
          "She attends painting classes.",
          "They run marathons together.",
          "He restores vintage cars.",
          "She dances ballet in the evenings.",
          "They read mystery novels.",
          "He trains for triathlons.",
          "She writes short stories.",
          "They explore new restaurants.",
          "He practices martial arts.",
          "She makes jewelry at home.",
          "They learn new recipes together.",
          "He grows vegetables in the garden.",
          "She travels for work often.",
          "They play basketball on weekends.",
          "He studies history in his spare time.",
          "She sews clothes for her children.",
          "She rides the bus to work.",
          "They spend their vacation at the beach.",
          "He enjoys reading classic novels.",
          "She paints beautiful landscapes.",
          "They hike in the mountains on the weekends.",
          "He practices yoga every morning.",
          "She listens to jazz music in the evenings.",
          "They host dinner parties for their friends.",
          "He trains for the marathon on weekdays.",
          "She gardens in the backyard on sunny days.",
          "They travel to different countries every year.",
          "He cooks delicious meals for his family.",
          "She knits cozy sweaters during the winter.",
          "They go on picnics in the park on Sundays.",
          "He plays the guitar in a local band.",
          "She takes dance classes at the studio.",
          "They go skiing in the mountains during the winter.",
          "He cycles to work to stay fit.",
          "She bakes cookies for the school bake sale.",
          "They host an annual barbecue in their backyard.",
          "He watches documentaries on the history channel.",
          "She volunteers at the animal shelter every weekend.",
          "They go on road trips to explore new destinations.",
          "He practices meditation to reduce stress.",
          "She collects antique furniture for her home.",
          "They attend the local theater's performances.",
          "He plays golf with his friends on Saturdays.",
          "She loves to try new recipes in the kitchen.",
          "They go on hiking adventures in the wilderness.",
          "He builds intricate models of airplanes.",
          "She enjoys going to the museum on Sundays.",
          "They plan family game nights every Friday.",
          "He attends lectures at the local university.",
          "She writes poetry in her spare time.",
          "They go on sailing trips during the summer.",
          "He enjoys playing chess with his grandchildren.",
          "She takes pottery classes at the community center.",
          "They go to the beach to watch the sunset.",
          "He plays video games with his friends online.",
          "She practices calligraphy as a hobby.",
          "They go on camping trips in the great outdoors.",
          "He volunteers at the local soup kitchen.",
          "She loves to go on long walks in the park.",
          "They attend concerts of their favorite musicians.",
          "He plays softball in a recreational league.",
          "She reads mystery novels before bed.",
          "They go on bike rides around the neighborhood.",
          "He enjoys watching science fiction movies.",
          "She takes photography classes to improve her skills.",
          "They go on weekend getaways to nearby towns.",
          "He practices playing the violin every day.",
          "She enjoys going to art galleries and museums.",
          "They go on boat tours to explore the local waterways.",
          "He plays chess with his colleagues during lunch breaks.",
          "She loves to go on shopping trips with her friends.",
          "They attend lectures on history and current events.",
          "He practices public speaking to improve his confidence.",
          "She enjoys going to the theater to see live performances.",
          "They go on day trips to explore the nearby countryside.",
          "He enjoys playing board games with his family.",
          "She loves to go on hikes in the nearby mountains.",
          "They go on weekend getaways to nearby cities.",
          "He practices playing the piano to improve his skills.",
          "She loves to go on picnics in the park.",
          "They go on weekend trips to the beach.",
          "He enjoys watching nature documentaries.",
          "She loves to go on shopping trips to the mall.",
          "They go on weekend trips to visit family.",
          "He practices playing the guitar to improve his skills.",
          "She loves to go on walks in the neighborhood.",
          "They go on weekend trips to visit friends.",
          "He enjoys playing video games in his free time.",
          "She loves to go on trips to the local zoo.",
          "They go on weekend trips to explore the countryside.",
          "He practices meditation to reduce stress and improve focus.",
          "She loves to go on trips to the local museum.",
          "They go on weekend trips to visit historical sites.",
          "He enjoys playing sports with his friends.",
          "She loves to go on trips to the local library.",
          "They go on weekend trips to attend cultural festivals.",
          "He practices yoga to improve his physical and mental well-being.",
          "She loves to go on trips to the local botanical garden.",
          "They go on weekend trips to explore nearby national parks.",
          "He enjoys playing board games with his family.",
          "She loves to go on trips to the local art gallery.",
          "They go on weekend trips to visit family members.",
          "He practices playing the drums to improve his musical skills.",
          "She loves to go on trips to the local theater.",
          "They go on weekend trips to attend concerts or performances.",
          "He enjoys playing outdoor sports like soccer or basketball.",
          "She loves to go on trips to the local aquarium.",
          "They go on weekend trips to explore nearby cities.",
          "He practices playing the saxophone to improve his musical skills.",
          "She loves to go on trips to the local science museum.",
          "They go on weekend trips to attend festivals or events.",
          "He enjoys playing card games with his friends.",
          "She loves to go on trips to the local history museum.",
          "They go on weekend trips to visit natural wonders.",
          "He practices playing the violin to improve his musical skills.",
          "She loves to go on trips to the local craft fair."
        ]
        
      },
    ],
    "data set 3": [
      {
        name: "Positive" as const,
        sentence: [
          "Maria speaks four languages.",
          "The shops in the city centre usually open at 9 o'clock in the morning.",
          "The City Museum closes at 5 o'clock in the evening.",
          "Tina is a teacher. She teaches mathematics to young children.",
          "My job is very interesting. I meet a lot of people.",
          "Peter's car is always dirty. He never washes it.",
          "Food is expensive. It costs a lot of money.",
          "Shoes are expensive. They cost a lot of money.",
          "Water boils at 100 degrees Celsius.",
          "Laura and I are good friends. I like her and she likes me.",
          "John plays the guitar.",
          "The library opens at 8 o’clock in the morning.",
          "The park closes at dusk.",
          "Sarah is a doctor. She works at the hospital.",
          "My brother is very tall.",
          "Emily’s house is always clean. She cleans it every day.",
          "Books are interesting. They provide a lot of knowledge.",
          "Cars are expensive. They cost a lot of money.",
          "Ice melts at 0 degrees Celsius.",
          "Tom and Jerry are best friends. They enjoy each other’s company.",
          "The sun rises in the east.",
          "The bank opens at 10 o’clock in the morning.",
          "The gym closes at 9 o’clock in the evening.",
          "Mark is a chef. He cooks delicious meals.",
          "My sister is very creative.",
          "Anna’s garden is beautiful. She takes care of it daily.",
          "Electronics are costly. They require a lot of money.",
          "Clothes are expensive. They cost a lot of money.",
          "Iron melts at 1538 degrees Celsius.",
          "Jane and I are colleagues. We work well together.",
          "The moon orbits the Earth.",
          "The supermarket opens at 7 o’clock in the morning.",
          "The cinema closes at midnight.",
          "David is an engineer. He designs buildings.",
          "My friend is very funny.",
          "Mike’s bike is always in good condition. He maintains it regularly.",
          "Jewelry is valuable. It costs a lot of money.",
          "Gadgets are expensive. They cost a lot of money.",
          "Gold melts at 1064 degrees Celsius.",
          "Sam and I are neighbors. We help each other.",
          "The stars shine at night.",
          "The bakery opens at 6 o’clock in the morning.",
          "The restaurant closes at 11 o’clock in the evening.",
          "Lisa is a nurse. She cares for patients.",
          "My cousin is very smart.",
          "Kevin’s garden is always green. He waters it every day.",
          "Furniture is pricey. It costs a lot of money.",
          "Watches are expensive. They cost a lot of money.",
          "Silver melts at 961 degrees Celsius.",
          "Alice and I are classmates. We study together.",
          "The river flows to the sea.",
          "The pharmacy opens at 9 o’clock in the morning.",
          "The zoo closes at 6 o’clock in the evening.",
          "Paul is a pilot. He flies airplanes.",
          "My uncle is very generous.",
          "Rachel’s car is always shiny. She washes it often.",
          "Perfume is luxurious. It costs a lot of money.",
          "Bags are expensive. They cost a lot of money.",
          "Copper melts at 1085 degrees Celsius.",
          "Ben and I are teammates. We play sports together.",
          "The wind blows from the west.",
          "The post office opens at 8 o’clock in the morning.",
          "The mall closes at 10 o’clock in the evening.",
          "Karen is a lawyer. She practices law.",
          "My aunt is very kind.",
          "Steve’s house is always tidy. He organizes it regularly.",
          "Art is valuable. It costs a lot of money.",
          "Shoes are expensive. They cost a lot of money.",
          "Aluminum melts at 660 degrees Celsius.",
          "Jack and I are partners. We run a business together.",
          "The rain falls from the sky.",
          "The clinic opens at 7 o’clock in the morning.",
          "The theater closes at 11 o’clock in the evening.",
          "Nancy is a writer. She writes novels.",
          "My nephew is very curious.",
          "Olivia’s garden is always colorful. She plants flowers often.",
          "Music is enriching. It costs a lot of money.",
          "Clothes are expensive. They cost a lot of money.",
          "Lead melts at 327 degrees Celsius.",
          "Emma and I are roommates. We live together.",
          "The snow falls in winter.",
          "The bookstore opens at 9 o’clock in the morning.",
          "The cafe closes at 10 o’clock in the evening.",
          "George is a scientist. He conducts experiments.",
          "My niece is very talented.",
          "Brian’s bike is always fast. He upgrades it regularly.",
          "Education is important. It costs a lot of money.",
          "Accessories are expensive. They cost a lot of money.",
          "Zinc melts at 419 degrees Celsius.",
          "Chloe and I are friends. We share secrets.",
          "The flowers bloom in spring.",
          "The market opens at 6 o’clock in the morning.",
          "The bar closes at 2 o’clock in the morning.",
          "Henry is a musician. He plays the piano.",
          "My grandmother is very wise.",
          "Daniel’s car is always reliable. He services it regularly.",
          "Travel is enriching. It costs a lot of money.",
          "Jewelry is expensive. It costs a lot of money.",
          "Tin melts at 232 degrees Celsius.",
          "Mia and I are pen pals. We write letters to each other.",
          "The leaves fall in autumn.",
          "The school opens at 8 o’clock in the morning.",
          "The library closes at 8 o’clock in the evening.",
          "Sophia is an artist. She paints beautiful pictures.",
          "My grandfather is very knowledgeable.",
          "Ethan’s garden is always neat. He trims it regularly.",
          "Health is priceless. It costs a lot of money.",
          "Watches are expensive. They cost a lot of money.",
          "Mercury melts at -39 degrees Celsius.",
          "Lily and I are hiking buddies. We explore trails together."
        ]
        
      },
    ],
    "data set 4": [
      {
        name: "Positive" as const,
        sentence: [
          "Sue always arrives early.",
          "I never go to the cinema.",
          "Martina always works hard.",
          "Children usually like chocolate.",
          "Jackie always enjoys parties.",
          "I often forget people’s names.",
          "Sam never watches TV.",
          "We usually have dinner at 7:30.",
          "Kate always wears nice clothes.",
          "John always wakes up early.",
          "I rarely eat fast food.",
          "Sarah often reads books.",
          "Dogs usually love playing fetch.",
          "Mike always attends meetings on time.",
          "I sometimes forget my keys.",
          "Emma never drinks coffee.",
          "We often go for a walk in the evening.",
          "Tom always wears a hat.",
          "Lisa usually cooks dinner.",
          "I always brush my teeth before bed.",
          "Cats often sleep during the day.",
          "David never misses a workout.",
          "We usually watch a movie on weekends.",
          "Anna always brings her lunch to work.",
          "I rarely watch the news.",
          "Birds usually sing in the morning.",
          "Kevin always finishes his homework.",
          "We often visit our grandparents.",
          "Mary never eats dessert.",
          "I usually take the bus to work.",
          "Flowers always bloom in spring.",
          "James often plays the piano.",
          "We never go out on weekdays.",
          "Rachel always wears sunglasses.",
          "I usually read before sleeping.",
          "Fish often swim in schools.",
          "Tom never skips breakfast.",
          "We always celebrate birthdays.",
          "Sarah usually drinks tea.",
          "I often forget my umbrella.",
          "Dogs always bark at strangers.",
          "Emily never eats spicy food.",
          "We usually have a picnic in the park.",
          "John always wears a tie to work.",
          "I rarely go to the gym.",
          "Cats usually chase mice.",
          "Mike never drinks soda.",
          "We often play board games.",
          "Lisa always wears a watch.",
          "I usually write in my journal.",
          "Birds often migrate in winter.",
          "David never eats junk food.",
          "We always go to the beach in summer.",
          "Anna usually brings a book to read.",
          "I rarely watch TV shows.",
          "Flowers often attract bees.",
          "Kevin always helps with chores.",
          "We usually visit the museum.",
          "Mary never drinks alcohol.",
          "I often forget my wallet.",
          "Dogs usually wag their tails.",
          "James never eats meat.",
          "We always go hiking in the mountains.",
          "Rachel usually wears a scarf.",
          "I rarely eat breakfast.",
          "Fish often swim upstream.",
          "Tom always carries a notebook.",
          "We never stay up late.",
          "Sarah usually wears a dress.",
          "I often forget my phone charger.",
          "Cats always purr when happy.",
          "Emily never eats dairy products.",
          "We usually go for a drive on Sundays.",
          "John always wears a jacket.",
          "I rarely drink milk.",
          "Birds usually build nests.",
          "Mike never eats fast food.",
          "We often go to the theater.",
          "Lisa always wears earrings.",
          "I usually take a nap in the afternoon.",
          "Flowers often bloom in the garden.",
          "David always brings a water bottle.",
          "We never miss a family gathering.",
          "Anna usually wears comfortable shoes.",
          "I rarely eat out.",
          "Dogs often dig holes.",
          "Kevin never drinks energy drinks.",
          "We usually go shopping on Saturdays.",
          "Mary always wears a smile.",
          "I often forget my glasses.",
          "Cats usually climb trees.",
          "James never eats sweets.",
          "We always go camping in the forest.",
          "Rachel usually wears a bracelet.",
          "I rarely watch movies.",
          "Fish often swim in circles.",
          "Tom always brings a pen.",
          "We never skip dinner.",
          "Sarah usually wears jeans.",
          "I often forget my hat.",
          "Birds always chirp in the morning.",
          "Emily never eats gluten.",
          "We usually go for a run in the park.",
          "John always wears gloves in winter.",
          "I rarely drink juice.",
          "Flowers usually bloom in the spring.",
          "Mike always brings a snack.",
          "We never miss a holiday celebration.",
          "Lisa usually wears a necklace."
        ]        
      },
    ],
    "data set 5": [
      {
        name: "Positive" as const,
        sentence: [
          "I usually watch TV in the evening.",
          "I often read in bed.",
          "I always get up before 7 o’clock.",
          "I usually go to work/school by bus.",
          "I always drink coffee in the morning.",
          "I often go for a walk in the park.",
          "I usually have breakfast at 8 o’clock.",
          "I always check my emails in the morning.",
          "I often listen to music while working.",
          "I usually take a shower before bed.",
          "I always call my parents on weekends.",
          "I often cook dinner at home.",
          "I usually read the news online.",
          "I always water my plants in the morning.",
          "I often go jogging in the evening.",
          "I usually clean the house on Saturdays.",
          "I always wear a jacket when it’s cold.",
          "I often visit my friends on Sundays.",
          "I usually do my homework after school.",
          "I always brush my teeth after meals.",
          "I often go shopping on weekends.",
          "I usually take a nap in the afternoon.",
          "I always write in my diary before bed.",
          "I often play video games in the evening.",
          "I usually go to the gym in the morning.",
          "I always drink water throughout the day.",
          "I often watch movies on Fridays.",
          "I usually eat lunch at noon.",
          "I always wear sunglasses when it’s sunny.",
          "I often read books on the weekend.",
          "I usually go to bed at 10 o’clock.",
          "I always take my dog for a walk in the morning.",
          "I often visit the library after work.",
          "I usually have a snack in the afternoon.",
          "I always wear a hat when it’s hot.",
          "I often go swimming on Sundays.",
          "I usually check social media in the evening.",
          "I always take my vitamins in the morning.",
          "I often go hiking on weekends.",
          "I usually do laundry on Sundays.",
          "I always pack my lunch for work.",
          "I often go to the beach in the summer.",
          "I usually read a book before bed.",
          "I always wear gloves when it’s cold.",
          "I often go cycling in the evening.",
          "I usually have a cup of tea in the afternoon.",
          "I always take a walk after dinner.",
          "I often visit my grandparents on weekends.",
          "I usually go to the market on Saturdays.",
          "I always wear a scarf in the winter.",
          "I often go to the cinema on Fridays.",
          "I usually do yoga in the morning.",
          "I always drink a glass of milk before bed.",
          "I often go to the park with my friends.",
          "I usually have a smoothie for breakfast.",
          "I always wear comfortable shoes.",
          "I often go to the museum on weekends.",
          "I usually take a bath in the evening.",
          "I always read the newspaper in the morning.",
          "I often go to the café after work.",
          "I usually have a salad for lunch.",
          "I always wear sunscreen when it’s sunny.",
          "I often go to the zoo on weekends.",
          "I usually take a walk in the park.",
          "I always drink green tea in the morning.",
          "I often go to the bookstore on Saturdays.",
          "I usually have dinner at 7 o’clock.",
          "I always wear a raincoat when it rains.",
          "I often go to the gym after work.",
          "I usually read a magazine in the evening.",
          "I always take my dog to the vet regularly.",
          "I often go to the theater on weekends.",
          "I usually have a sandwich for lunch.",
          "I always wear a helmet when cycling.",
          "I often go to the countryside on weekends.",
          "I usually take a walk in the evening.",
          "I always drink a glass of water before bed.",
          "I often go to the aquarium on weekends.",
          "I usually have cereal for breakfast.",
          "I always wear a mask in crowded places.",
          "I often go to the gym on weekdays.",
          "I usually read a novel before bed.",
          "I always take my car for a service regularly.",
          "I often go to the mountains on weekends.",
          "I usually have soup for dinner.",
          "I always wear a seatbelt in the car.",
          "I often go to the spa on weekends.",
          "I usually take a walk in the morning.",
          "I always drink herbal tea in the evening.",
          "I often go to the amusement park on weekends.",
          "I usually have toast for breakfast.",
          "I always wear a watch.",
          "I often go to the art gallery on weekends.",
          "I usually take a walk after lunch.",
          "I always drink a smoothie in the morning.",
          "I often go to the flea market on weekends.",
          "I usually have pasta for dinner.",
          "I always wear a sweater when it’s chilly.",
          "I often go to the botanical garden on weekends.",
          "I usually take a walk in the afternoon.",
          "I always drink a cup of coffee after lunch.",
          "I often go to the farmer’s market on weekends.",
          "I usually have a fruit salad for breakfast.",
          "I always wear a belt with my jeans.",
          "I often go to the lake on weekends."
        ]
        
      
      },
    ],
    "data set 6": [
      {
        name: "Positive" as const,
        sentence: [
          "He reads good books.",
          "Nasima always speaks the truth.",
          "They come to school in time.",
          "You take a bath daily.",
          "I get up early in the morning.",
          "We do our work ourselves.",
          "The goat gives milk.",
          "Parrots talk.",
          "The shoemakers make shoes.",
          "Karim cleans his teeth.",
          "You deal in sugar.",
          "I wear new clothes.",
          "Girls sing songs.",
          "Hard working students get prizes.",
          "Najma washes the clothes clean.",
          "Jackals howl in the evening.",
          "I love my brother.",
          "We read the newspaper every day.",
          "Aslam buys new shoes on Eid.",
          "A poor man lives with difficulty.",
          "A rich man looks down upon the poor with contempt.",
          "Chickens lay eggs all year round.",
          "You teach English to the 10th grade.",
          "I know how to swim.",
          "This boy always makes noise.",
          "God helps those who help themselves.",
          "We withdraw money from the bank every day.",
          "You make false excuses.",
          "A drowning man catches at a straw.",
          "The sun sets in the west.",
          "We go to the museum now and then.",
          "Children enjoy visiting the zoo.",
          "My friend always gives me the right advice.",
          "Those who work hard reap the rewards.",
          "You pay a thousand rupees in taxes every year.",
          "I pay the bill by the tenth of every month.",
          "This butcher gives less weight.",
          "This shopkeeper sells substandard goods.",
          "A greedy man earns black money.",
          "A poor man hardly makes both ends meet.",
          "The hunter takes aim at every bird.",
          "The doctor suggests rest to the patient.",
          "The farmer is harvesting the wheat crop these days.",
          "He associates with good people.",
          "This person deceives everyone."
        ]
        
      },
    ],
  },
];

export default data;
