// data.ts
const data = [
  {
    name: "MySelf",
    "data set 1": [
      {
        name: "Positive" as const,
        sentence: [
          "Are you watching it? No, you can turn it off.",
          "Are you going now? Yes, see you tomorrow.",
          "Is it raining? No, not at the moment.",
          "Are you enjoying the film? Yes, it's very funny.",
          "Is that clock working? No, it's broken.",
          "Are you waiting for a bus? No, for a taxi.",
          "Are you listening? Yes, I'm listening carefully.",
          "Do you have it? No, I don't have it.",
          "Can you help me? Yes, how can I assist you?",
          "Is it cold outside? No, it's actually quite mild.",
          "Did you finish your work? Yes, I just completed the project.",
          "Are you ready to go? No, I still need a few more minutes.",
          "Can you turn up the volume? Sure, let me increase the volume.",
          "Is your phone charged? No, the battery is low.",
          "Did you enjoy the party? Yes, it was a lot of fun.",
          "Are the lights on? No, they're turned off.",
          "Can you open the window? Of course, let me open it for you.",
          "Is dinner ready? Yes, it's ready to be served.",
          "Did you remember to lock the door? No, I forgot to lock it.",
          "Are you leaving now? Yes, I'm heading out now.",
          "Can you pass me that book? Certainly, here you go.",
          "Is the weather nice today? Yes, it's a beautiful sunny day.",
          "Did you watch the news? No, I haven't seen the news today.",
          "Are you feeling well? Yes, I'm feeling great, thank you.",
          "Can you turn off the TV? Sure, let me turn it off.",
          "Is your computer working properly? No, it seems to be having some issues.",
          "Did you make a reservation? Yes, I made a reservation for two.",
          "Are you almost done with your task? No, I still have a bit more to do.",
          "Can you send me that document? Absolutely, I'll email it to you right away.",
          "Is the traffic bad today? Yes, it's been very congested on the roads.",
          "Did you enjoy the meal? Yes, it was a delicious dinner.",
          "Are you coming with us? No, I have other plans.",
          "Can you check the time? Sure, it's 3:45 PM.",
          "Is the store open today? No, it's closed for the holiday.",
          "Did you water the plants? Yes, I took care of watering them.",
          "Are you ready for the meeting? No, I still need to prepare a few things.",
          "Can you turn on the air conditioning? Of course, let me switch it on.",
          "Is the printer working? No, it seems to be jammed.",
          "Did you receive my email? Yes, I got your email and will respond shortly.",
          "Are you going to the gym later? No, I don't have time today.",
          "Can you help me with this task? Definitely, I'd be happy to assist you.",
          "Is the weather forecast good for the weekend? Yes, they're predicting sunny skies.",
          "Did you call the plumber? No, I haven't called them yet.",
          "Are you heading home now? Yes, I'm leaving the office now.",
          "Can you grab me a bottle of water? Sure, let me get that for you.",
          "Is the WiFi connection stable? No, it seems to be a bit spotty today.",
          "Did you enjoy the concert? Yes, it was an amazing performance.",
          "Are you free this evening? No, I have plans already.",
          "Can you double-check the numbers? Absolutely, let me review them again.",
          "Is the package delivered yet? No, it hasn't arrived.",
          "Did you submit the report on time? Yes, I sent it off earlier today.",
          "Are you going to the party tonight? No, I don't think I can make it.",
          "Can you remind me of the meeting time? Sure, the meeting is at 2 PM.",
          "Is the car ready for the trip? Yes, it's all fueled up and ready to go.",
          "Did you lock the front door? No, I forgot to do that.",
          "Are you hungry for lunch? Yes, I'm ready for a meal.",
          "Can you turn on the fan? Absolutely, let me turn it on.",
          "Is the library open today? No, it's closed on Sundays.",
          "Did you enjoy the book? Yes, I found it to be a great read.",
          "Are you available this weekend? No, I have some prior commitments.",
          "Can you help me with my homework? Sure, I'd be happy to assist you.",
          "Is the weather forecast calling for rain? No, it looks like it will be sunny.",
          "Did you check the bank balance? Yes, I reviewed the account details.",
          "Are you interested in going to the museum? No, I don't have time for that today.",
          "Can you set the alarm for 6 AM? Absolutely, let me set the alarm.",
          "Is the dishwasher running? No, it's not currently in use.",
          "Did you reserve a table at the restaurant? Yes, I made a reservation for 7 PM.",
          "Are you heading to the gym after work? No, I plan to go tomorrow instead.",
          "Can you pass me that remote control? Sure, here you go.",
          "Is the laundry done? Yes, I just finished the laundry.",
          "Did you enjoy the movie? No, I didn't find it very entertaining.",
          "Are you planning to travel this summer? Yes, I have a trip scheduled.",
          "Can you double-check the schedule? Absolutely, let me take another look.",
          "Is the coffee fresh? No, I think it's been sitting for a while.",
          "Did you remember to feed the dog? Yes, I took care of feeding the pet.",
          "Are you going to the concert tonight? No, I don't have tickets for that.",
          "Can you help me with this math problem? Of course, I'd be happy to assist you.",
          "Is the temperature comfortable? Yes, it's a pleasant temperature today.",
          "Did you pick up the dry cleaning? No, I forgot to stop by the cleaners.",
          "Are you heading out for lunch soon? Yes, I'm going to get something to eat.",
          "Can you turn on the lights? Sure, let me switch the lights on.",
          "Is the internet connection stable? No, it seems to be experiencing some issues.",
          "Did you enjoy the weekend getaway? Yes, it was a wonderful and relaxing trip.",
          "Are you attending the work event tonight? No, I won't be able to make it.",
          "Can you check the traffic conditions? Sure, let me look up the latest traffic report.",
          "Is the weather forecast looking good? Yes, it's supposed to be sunny all week.",
          "Did you find the book you were looking for? No, they didn't have it in stock.",
          "Are you ready to leave for the airport? Yes, I have everything packed and ready to go.",
          "Can you adjust the thermostat? Absolutely, let me change the temperature setting.",
          "Is the car running low on gas? Yes, I think we need to fill up soon.",
          "Did you send the email to your boss? No, I haven't sent it yet.",
          "Are you heading to the gym after work? Yes, I'm planning to go for a workout.",
          "Can you turn off the radio? Sure, let me turn it off.",
          "Is the meeting still happening at 3 PM? No, it's been rescheduled for later.",
          "Did you enjoy the vacation? Yes, it was a fantastic and relaxing trip.",
          "Are you available for a quick call? No, I'm in the middle of something at the moment.",
          "Can you check if the oven is off? Certainly, let me go verify the oven.",
          "Is the package tracking number valid? Yes, the tracking number is working.",
          "Did you sign up for the fitness challenge? No, I didn't have time to participate.",
          "Are you going to the party this weekend? Yes, I'm looking forward to it.",
          "Can you remind me of the address? Sure, the address is 123 Main Street.",
          "Is the printer out of ink? Yes, I need to replace the ink cartridge.",
          "Did you finish your report? No, I'm still working on finalizing it.",
          "Are you free for a quick coffee break? Yes, I can take a short break.",
          "Can you lock the back door? Absolutely, let me make sure it's secure.",
          "Is the WiFi password still the same? Yes, the password hasn't changed.",
        ],
      },
    ],
    "data set 2": [
      {
        name: "Positive" as const,
        sentence: [
          "What are you reading? I'm reading a novel.",
          "Where's she going? She's going to the store.",
          "What are you eating? I'm having a sandwich for lunch.",
          "Why're you crying? I'm feeling a bit sad.",
          "What are they looking at? They're looking at a painting.",
          "Why's he laughing? He finds the situation quite funny.",
          "What are you working on? I'm working on a new project.",
          "Where's Tom headed? Tom is headed to the gym.",
          "What are you drinking? I'm sipping on a cup of coffee.",
          "Why're they shouting? They seem to be having an argument.",
          "What are the kids playing? The kids are playing tag outside.",
          "Why's the dog barking? The dog is barking at a stranger.",
          "What are you studying? I'm studying for an upcoming exam.",
          "Where's your family going? They're going on a road trip.",
          "What are you baking? I'm baking some cookies in the oven.",
          "Why're you frowning? I'm a bit concerned about something.",
          "What are they discussing? They appear to be discussing work.",
          "Why's the boss yelling? The boss is upset about a mistake.",
          "What are you sketching? I'm sketching a design for a new project.",
          "Where's the cat hiding? The cat is hiding under the bed.",
          "What are you sewing? I'm sewing a new shirt.",
          "Why're you smiling? I'm in a good mood today.",
          "What are they observing? They're observing the solar eclipse.",
          "Why's he scowling? He's annoyed about the situation.",
          "What are you packing? I'm packing for my upcoming vacation.",
          "Where's the train headed? The train is headed to the next city.",
          "What are you writing? I'm writing a letter to a friend.",
          "Why're you frowning? I'm a bit worried about the test results.",
          "What are they searching for? They're searching for their lost keys.",
          "Why's the baby crying? The baby is hungry and needs to be fed.",
          "What are you cooking? I'm cooking a stir-fry for dinner.",
          "Where's your sister going? She's going to the library to study.",
          "What are you building? I'm building a birdhouse in the garage.",
          "Why're you sighing? I'm feeling a bit tired and overwhelmed.",
          "What are they discussing? They appear to be discussing travel plans.",
          "Why's the teacher upset? The teacher is upset about the late assignment.",
          "What are you painting? I'm painting a landscape on the canvas.",
          "Where's the bus headed? The bus is headed to the city center.",
          "What are you reading? I'm reading the morning newspaper.",
          "Why're you frowning? I'm a bit confused by the instructions.",
          "What are they watching? They're watching a documentary on TV.",
          "Why's the dog barking? The dog is barking at a squirrel outside.",
          "What are you doing? I'm tidying up the living room.",
          "Where's your mom going? She's going to the grocery store.",
          "What are you knitting? I'm knitting a scarf for the winter.",
          "Why're you giggling? I find that joke quite amusing.",
          "What are they exploring? They're exploring the ancient ruins.",
          "Why's the crowd cheering? The crowd is cheering for the winning team.",
          "What are you drawing? I'm drawing a portrait of my friend.",
          "Where's the cat wandering? The cat is wandering around the backyard.",
          "What are you carving? I'm carving a wooden figurine.",
          "Why're you sighing? I'm a bit stressed about the upcoming deadline.",
          "What are they filming? They appear to be filming a commercial.",
          "Why's the toddler throwing a tantrum? The toddler wants a toy they can't have.",
          "What are you planting? I'm planting some flowers in the garden.",
          "Where's your brother going? He's going to soccer practice.",
          "What are you baking? I'm baking some cupcakes for a party.",
          "Why're you frowning? I'm a bit concerned about the weather forecast.",
          "What are they investigating? They're investigating a potential crime scene.",
          "Why's the teacher smiling? The teacher is pleased with the students' progress.",
          "What are you hammering? I'm hammering a few nails into the wall.",
          "Where's your dad headed? He's headed to the office for work.",
          "What are you sewing? I'm sewing a new dress for the wedding.",
          "Why're you crying? I'm feeling a bit homesick.",
          "What are they discussing? They're discussing the upcoming school play.",
          "Why's the crowd booing? The crowd is booing the referee's call.",
          "What are you sculpting? I'm sculpting a clay figure.",
          "Where's the bus going? The bus is going to the train station.",
          "What are you stirring? I'm stirring the soup on the stove.",
          "Why're you frowning? I'm a bit concerned about the test results.",
          "What are they building? They're building a new playground in the park.",
          "Why's the dog wagging its tail? The dog is happy to see its owner.",
          "What are you typing? I'm typing up a report for work.",
          "Where's the family traveling? They're traveling to the beach for vacation.",
          "What are you sketching? I'm sketching a design for a new product.",
          "Why're you smiling? I'm in a good mood because of the good news.",
          "What are they observing? They're observing the wildlife in the nature reserve.",
          "Why's the audience applauding? The audience is applauding the performer's excellent show.",
          "What are you carving? I'm carving a wooden sculpture for the art fair.",
          "Where's the cat hiding? The cat is hiding under the couch.",
          "What are you baking? I'm baking some cookies for the school bake sale.",
          "Why're you frowning? I'm a bit concerned about the upcoming exam.",
          "What are they discussing? They're discussing the details of the business proposal.",
          "Why's the baby giggling? The baby is giggling because the parent is playing with them.",
          "What are you painting? I'm painting a landscape scene on the canvas.",
          "Where's your friend going? They're going to the movies with their family.",
          "What are you knitting? I'm knitting a warm scarf for the winter.",
          "Why're you sighing? I'm a bit tired from the long workday.",
          "What are they exploring? They're exploring the ancient ruins of the historic site.",
          "Why's the crowd cheering? The crowd is cheering for the winning sports team.",
          "What are you sewing? I'm sewing a new outfit for the upcoming event.",
          "Where's the cat wandering? The cat is wandering around the backyard.",
          "What are you carving? I'm carving a wooden figurine for a gift.",
          "Why're you giggling? I find the situation quite amusing.",
          "What are they filming? They're filming a new documentary on nature.",
          "Why's the toddler throwing a tantrum? The toddler wants a toy they can't have right now.",
          "What are you planting? I'm planting some vegetable seeds in the garden.",
          "Where's your sister going? She's going to the library to study for her exam.",
          "What are you hammering? I'm hammering a few nails into the wall to hang a picture.",
          "Why're you frowning? I'm a bit concerned about the weather forecast for the weekend.",
        ],
      },
    ],
    "data set 3": [
      {
        name: "Positive" as const,
        sentence: [
          "Is Ben working today?",
          "What are the children doing?",
          "Are you listening to me?",
          "Where are your friends going?",
          "Are your parents watching TV?",
          "What's Eman cooking?",
          "Why are you looking at me?",
          "Is the bus coming?",
          "Is the store open today?",
          "What time does the movie start?",
          "Are you feeling okay?",
          "Where did you park the car?",
          "Is your sister coming to the party?",
          "What are you making for dinner?",
          "Why are you smiling?",
          "Is the bus running on time?",
          "Who is that person over there?",
          "What time does your flight depart?",
          "Are the children playing outside?",
          "Where is the nearest coffee shop?",
          "Is the library closed on Sundays?",
          "What is the weather forecast for tomorrow?",
          "Are you ready to leave for the appointment?",
          "Where can I find the restrooms?",
          "Is the office open during the holidays?",
          "What time does your shift end at work?",
          "Are the neighbors having a party tonight?",
          "Where can I purchase tickets for the concert?",
          "Is your dog allowed in the park?",
          "What are you studying for in your classes?",
          "Are the stores having a big sale this weekend?",
          "Where is the best place to get sushi in town?",
          "Is the museum open on Mondays?",
          "What are the plans for the upcoming vacation?",
          "Are the grandparents visiting next month?",
          "Where did you find that interesting book?",
          "Is the internet connection working properly?",
          "What is the capital of the next state over?",
          "Are the neighbors moving out soon?",
          "Where can I sign up for that fitness class?",
          "Is the dry cleaner open late tonight?",
          "What time do the children need to be picked up?",
          "Are the flowers in the garden blooming yet?",
          "Where did you get that delicious-looking dessert?",
          "Is the community center hosting an event this weekend?",
          "What are the recommended hiking trails in the area?",
          "Are the banks closed for the holiday tomorrow?",
          "Where can I find information about that new program?",
          "Is the car in need of an oil change soon?",
          "What are the plans for your brother's birthday party?",
          "Are you interested in trying that new restaurant?",
          "Where can I apply for the job opening at the office?",
          "Is the package I ordered going to arrive on time?",
          "What time does the yoga class start in the mornings?",
          "Are the children behaving well at school today?",
          "Where did you discover that unique vintage item?",
          "Is the public transportation reliable in this city?",
          "What are the special ingredients in that homemade recipe?",
          "Are the neighbors being too loud with their music?",
          "Where can I purchase tickets for the upcoming concert?",
          "Is the new technology easy to set up and use?",
          "What are the latest updates on the big project at work?",
          "Are the flowers in the garden ready to be picked?",
          "Where did you find that fascinating documentary to watch?",
          "Is the sports team having a good season so far?",
          "What are the details of the family reunion this summer?",
          "Are the guests enjoying the party so far?",
          "Where can I find more information about that volunteer opportunity?",
          "Is the local produce market open on Saturdays?",
          "What are the best places to go hiking in the mountains?",
          "Are the children excited for their school field trip?",
          "Where did you get that stylish new outfit you're wearing?",
          "Is the online order I placed going to arrive soon?",
          "What are the special features of that new kitchen appliance?",
          "Are the guests arriving on time for the event?",
          "Where can I find the schedule for the community center classes?",
          "Is the weather forecast calling for rain this weekend?",
          "What are the details of the big work conference next month?",
          "Are the pets being properly cared for while we're away?",
          "Where did you discover that amazing new restaurant to try?",
          "Is the public library open during the summer months?",
          "What are the highlights of the local art festival this year?",
          "Are the children excited for their upcoming vacation?",
          "Where can I find more information about registering for that workshop?",
          "Is the community garden accepting new members currently?",
          "What are the latest updates on the construction project downtown?",
          "Are the neighbors planning a block party anytime soon?",
          "Where did you hear about that interesting new book to read?",
          "Is the fitness center offering any special promotions right now?",
          "What are the plans for the company holiday party this year?",
          "Are the students enjoying their new classes so far?",
          "Where did you find that beautiful piece of artwork to display?",
          "Is the local farmers market open on Wednesdays?",
          "What are the special features of that new smart home device?",
          "Are the family members coming in from out of town this weekend?",
          "Where can I find the schedule for the community sports leagues?",
          "Is the car in need of any maintenance or repairs soon?",
          "What are the plans for the big company meeting next week?",
          "Are the children participating in any extracurricular activities?",
          "Where did you discover that delicious new recipe to try?",
          "Is the public transportation system running on time today?",
          "What are the highlights of the town's annual festival this year?",
          "Are the grandparents babysitting the children tonight?",
          "Where can I find more details about that volunteer opportunity?",
          "Is the neighborhood hosting a garage sale anytime soon?",
          "What are the latest updates on that home renovation project?",
          "Are the coworkers planning a surprise party for someone?",
          "Where did you hear about that exciting new travel destination?",
        ],
      },
    ],
    "data set 4": [
      {
        name: "Positive" as const,
        sentence: [
          "Are you watching TV? No, I'm not.",
          "Are you wearing a watch? Yes, I am.",
          "Are you eating something? Yes, I am.",
          "Is it raining? No, it isn't.",
          "Are you sitting on the floor? No, I'm not.",
          "Are you feeling well? Yes, I am.",
          "Are you listening to music? No, I'm not.",
          "Are you holding a book? Yes, I am.",
          "Is it cold outside? No, it's not.",
          "Are you talking on the phone? Yes, I am.",
          "Is the dog barking? No, it isn't.",
          "Are you drinking coffee? Yes, I am.",
          "Is the sun shining? Yes, it is.",
          "Are you taking notes? No, I'm not.",
          "Is the TV turned on? No, it's not.",
          "Are you typing on a computer? Yes, I am.",
          "Is it windy today? No, it's not.",
          "Are you reading the newspaper? Yes, I am.",
          "Is the room bright? Yes, it is.",
          "Are you chewing gum? No, I'm not.",
          "Is the door closed? Yes, it is.",
          "Are you playing a game? No, I'm not.",
          "Is the car parked outside? Yes, it is.",
          "Are you wearing a hat? No, I'm not.",
          "Is the food delicious? Yes, it is.",
          "Are you taking a break? No, I'm not.",
          "Is the water cold? Yes, it is.",
          "Are you taking photos? No, I'm not.",
          "Is the room clean? Yes, it is.",
          "Are you stretching? No, I'm not.",
          "Is the music loud? Yes, it is.",
          "Are you washing dishes? No, I'm not.",
          "Is the sky blue? Yes, it is.",
          "Are you folding laundry? No, I'm not.",
          "Is the temperature warm? Yes, it is.",
          "Are you watering plants? No, I'm not.",
          "Is the book interesting? Yes, it is.",
          "Are you exercising? No, I'm not.",
          "Is the house quiet? No, it's not.",
          "Are you painting a picture? Yes, I am.",
          "Is the traffic heavy? Yes, it is.",
          "Are you packing a suitcase? No, I'm not.",
          "Is the garden beautiful? Yes, it is.",
          "Are you playing a sport? No, I'm not.",
          "Is the room dark? No, it's not.",
          "Are you baking cookies? Yes, I am.",
          "Is the car clean? Yes, it is.",
          "Are you organizing your desk? No, I'm not.",
          "Is the food spicy? Yes, it is.",
          "Are you taking a nap? No, I'm not.",
          "Is the weather nice? Yes, it is.",
          "Are you reading a magazine? No, I'm not.",
          "Is the door unlocked? No, it's not.",
          "Are you listening to the radio? Yes, I am.",
          "Is the grass green? Yes, it is.",
          "Are you checking your email? No, I'm not.",
          "Is the water boiling? Yes, it is.",
          "Are you playing with a pet? No, I'm not.",
          "Is the temperature cool? No, it's not.",
          "Are you making a phone call? Yes, I am.",
          "Is the car parked properly? Yes, it is.",
          "Are you taking out the trash? No, I'm not.",
          "Is the computer turned on? Yes, it is.",
          "Are you writing a letter? No, I'm not.",
          "Is the room cozy? Yes, it is.",
          "Are you practicing yoga? No, I'm not.",
          "Is the music relaxing? Yes, it is.",
          "Are you preparing a meal? No, I'm not.",
          "Is the sky cloudy? Yes, it is.",
          "Are you cleaning the house? No, I'm not.",
          "Is the door locked? Yes, it is.",
          "Are you playing a video game? No, I'm not.",
          "Is the food fresh? Yes, it is.",
          "Are you going for a walk? No, I'm not.",
          "Is the table set for dinner? Yes, it is.",
          "Are you reading a book? No, I'm not.",
          "Is the weather stormy? No, it's not.",
          "Are you taking a shower? No, I'm not.",
          "Is the plant healthy? Yes, it is.",
          "Are you making notes? No, I'm not.",
          "Is the water warm? No, it's not.",
          "Are you drinking tea? Yes, I am.",
          "Is the room well-lit? Yes, it is.",
          "Are you doing laundry? No, I'm not.",
          "Is the car running smoothly? Yes, it is.",
          "Are you practicing a hobby? No, I'm not.",
          "Is the floor clean? Yes, it is.",
          "Are you meditating? No, I'm not.",
          "Is the fruit ripe? Yes, it is.",
          "Are you tidying up? No, I'm not.",
          "Is the bag heavy? No, it's not.",
          "Are you listening carefully? Yes, I am.",
          "Is the cup full? No, it's not.",
          "Are you resting? Yes, I am.",
          "Is the plant growing? Yes, it is.",
          "Are you concentrating? No, I'm not.",
          "Is the light bright? Yes, it is.",
          "Are you enjoying this? Yes, I am.",
          "Is the door open? No, it's not.",
          "Are you taking notes? Yes, I am.",
          "Is the weather nice? Yes, it is.",
          "Are you feeling good? Yes, I am.",
          "Is the music playing? No, it's not.",
          "Are you working hard? Yes, I am.",
          "Is the clock accurate? Yes, it is.",
          "Are you paying attention? Yes, I am.",
        ],
      },
    ],
    "data set 5": [
      {
        name: "Positive" as const,
        sentence: [
          "Where are your parents? They're watching TV.",
          "Where's she going? Paula is going out.",
          "Where's David? He's having a shower.",
          "What are the children doing? They're playing.",
          "Are they asleep? No, not at the moment.",
          "Where are Sue and Steve? They're coming now.",
          "Why are you standing here? I'm waiting for somebody.",
          "Is it raining? Yes, it is.",
          "Where are your siblings? They're eating dinner.",
          "Where's the cat? It's sleeping on the couch.",
          "What is your neighbor doing? They're gardening.",
          "Where's the dog? He's outside running around.",
          "Who are you waiting for? I'm waiting for my friend.",
          "Where's your boss? She's in a meeting.",
          "What are you doing? I'm reading a book.",
          "Where's your sister? She's at the library.",
          "Where's the teacher? He's teaching the class.",
          "What are your parents cooking? They're making spaghetti.",
          "Where's your uncle? He's at work.",
          "What are the neighbors doing? They're having a barbecue.",
          "Where's the baby? She's napping in her crib.",
          "What is your cousin up to? He's playing video games.",
          "Where's the mailman? He's delivering the mail.",
          "What are the kids playing? They're playing hide-and-seek.",
          "Where's Grandma? She's knitting in her rocking chair.",
          "What is your roommate studying? They're studying for an exam.",
          "Where's the boss? She's in her office.",
          "What are the dogs doing? They're chasing a squirrel.",
          "Where's your friend? She's at the park.",
          "What is your coworker working on? They're finishing a project.",
          "Where's the janitor? He's cleaning the hallway.",
          "What are the teenagers doing? They're hanging out at the mall.",
          "Where's the customer? She's at the checkout counter.",
          "What is the chef preparing? They're cooking a five-course meal.",
          "Where's the firefighter? He's responding to an emergency call.",
          "What are the musicians playing? They're performing a concert.",
          "Where's the police officer? She's patrolling the neighborhood.",
          "What is the student doing? They're taking notes in class.",
          "Where's the doctor? He's examining a patient.",
          "What are the volunteers doing? They're cleaning up the park.",
          "Where's the cashier? She's ringing up customers.",
          "What is the mechanic fixing? They're repairing a car.",
          "Where's the lifeguard? He's watching over the swimmers.",
          "What are the tourists doing? They're sightseeing around the city.",
          "Where's the barista? She's making coffee drinks.",
          "What is the artist creating? They're painting a landscape.",
          "Where's the receptionist? He's answering the phone.",
          "What are the gardeners doing? They're tending to the flowers.",
          "Where's the teacher? She's grading papers in the classroom.",
          "What is the chef baking? They're making a birthday cake.",
          "Where's the delivery person? He's dropping off a package.",
          "What are the children learning? They're studying math.",
          "Where's the plumber? She's fixing a leaky pipe.",
          "What is the team doing? They're practicing for the game.",
          "Where's the electrician? He's repairing a light fixture.",
          "What are the employees discussing? They're having a meeting.",
          "Where's the manager? She's in her office.",
          "What is the family planning? They're going on a vacation.",
          "Where's the athlete? He's training at the gym.",
          "What are the musicians rehearsing? They're practicing a new song.",
          "Where's the customer service rep? She's assisting a customer.",
          "What is the scientist researching? They're conducting an experiment.",
          "Where's the engineer? He's designing a new product.",
          "What are the students studying? They're preparing for an exam.",
          "Where's the nurse? She's checking on patients.",
          "What is the carpenter building? They're constructing a new table.",
          "Where's the salesperson? He's pitching a product to a client.",
          "What are the employees celebrating? They're having a company party.",
          "Where's the accountant? She's crunching numbers in her office.",
          "What is the writer working on? They're drafting a novel.",
          "Where's the editor? He's reviewing a manuscript.",
          "What are the chefs cooking? They're preparing a multi-course meal.",
          "Where's the contractor? She's overseeing a construction site.",
          "What is the designer creating? They're sketching a new fashion line.",
          "Where's the architect? He's meeting with clients.",
          "What are the researchers analyzing? They're studying data.",
          "Where's the social worker? She's meeting with a client.",
          "What is the counselor discussing? They're providing therapy.",
          "Where's the tutor? He's helping a student with homework.",
          "What are the musicians composing? They're writing a new song.",
          "Where's the housekeeper? She's cleaning a guest room.",
          "What is the photographer capturing? They're taking portraits.",
          "Where's the server? He's delivering food to a table.",
          "What are the athletes practicing? They're working on their technique.",
          "Where's the bartender? She's mixing cocktails.",
          "What is the chef tasting? They're sampling a new recipe.",
          "Where's the event planner? He's coordinating a wedding.",
          "What are the volunteers organizing? They're running a food drive.",
          "Where's the IT specialist? She's troubleshooting a computer issue.",
          "What is the developer coding? They're building a new app.",
          "Where's the project manager? He's leading a team meeting.",
          "What are the marketers strategizing? They're planning a campaign.",
          "Where's the financial advisor? She's meeting with a client.",
          "What is the HR representative discussing? They're handling an employee concern.",
          "Where's the recruiter? He's interviewing job candidates.",
          "What are the executives deliberating? They're making a business decision.",
          "Where's the personal trainer? She's guiding a client through a workout.",
          "What is the life coach exploring? They're helping a client set goals.",
          "Where's the career counselor? He's advising a student on job options.",
          "What are the tutors instructing? They're teaching academic subjects.",
          "Where's the therapist? She's conducting a session.",
          "What is the coach teaching? They're leading a skills clinic.",
          "Where's the mentor? He's meeting with a mentee.",
          "What are the experts discussing? They're analyzing a complex issue.",
          "Where's the librarian? She's assisting a patron.",
          "What is the instructor demonstrating? They're teaching a new technique.",
          "Where's the tour guide? He's leading a group through a museum.",
          "What are the facilitators modeling? They're demonstrating best practices."
      ]
      
      },
    ],
    "data set 6": [
      {
        name: "Positive" as const,
        sentence: [
          "Is the baby sleeping?",
          "Are you listening to the news?",
          "Are the players playing the match?",
          "Is Salma going to her aunt's house?",
          "Where are the people dancing?",
          "Why are the students coming back early from school?",
          "Why is the plane landing here?",
          "Is your watch losing five minutes daily?",
          "Who is ringing the bell?",
          "When are the guests arriving here?",
          "How many persons are considering this matter?",
          "Am I not addressing you?",
          "Whom is the nurse talking to?",
          "How is the doctor injecting the patient?",
          "How many lawyers are arguing?",
          "Is the moon coming out?",
          "Are the bad boys throwing stones at buses?",
          "Are the workers digging up soil?",
          "Why are you selling your house?",
          "Is Bashir buying a new motorcycle?",
          "Where are the women washing clothes?",
          "How many men are joining this business?",
          "How much money are you withdrawing from the bank?",
          "Who’s inviting me to dinner?",
          "Where are the poor refugees going?",
          "Is the shopkeeper charging the customer extra money?",
          "Whose message are you carrying?",
          "When is the contractor starting the work?",
          "Who’s knocking at the door?",
          "Which magazine are you reading?"
        ]
        
      },
    ],
  },
];

export default data;
