// data.ts
const data = [
  {
    name: "MySelf",
    "data set 1": [
      {
        name: "Positive" as const,
        sentence: [
          "He's assembling furniture.",
          "He's carving a pumpkin.",
          "He's changing a light bulb.",
          "He's changing a tire.",
          "He's chopping firewood.",
          "He's cleaning the windows.",
          "He's cooking dinner.",
          "He's driving a car.",
          "He's feeding the cat.",
          "He's fixing a bicycle.",
          "He's flipping pancakes.",
          "He's inflating a balloon.",
          "He's jogging in the park.",
          "He's mowing the lawn.",
          "He's painting the walls.",
          "He's playing video games.",
          "He's polishing shoes.",
          "He's polishing silverware.",
          "He's programming a computer.",
          "He's pruning trees.",
          "He's reading a book.",
          "He's repairing a clock.",
          "He's setting the table.",
          "He's sharpening pencils.",
          "He's shaving his beard.",
          "He's sketching a portrait.",
          "He's taking a nap.",
          "He's tuning a guitar.",
          "He's tuning a radio.",
          "He's typing on a computer.",
          "He's washing the dishes.",
          "He's watering the plants.",
          "He's waxing a car.",
          "He's wrapping a gift.",
          "She's addressing envelopes.",
          "She's arranging flowers.",
          "She's baking a cake.",
          "She's braiding hair.",
          "She's brewing coffee.",
          "She's brushing her teeth.",
          "She's combing her hair.",
          "She's dusting furniture.",
          "She's folding laundry.",
          "She's frosting a cake.",
          "She's ironing clothes.",
          "She's knitting a scarf.",
          "She's making a phone call.",
          "She's making the bed.",
          "She's mixing paint colors.",
          "She's organizing a closet.",
          "She's painting a picture.",
          "She's peeling potatoes.",
          "She's planting flowers.",
          "She's playing the piano.",
          "She's polishing jewelry.",
          "She's sewing a button.",
          "She's solving a puzzle.",
          "She's sorting mail.",
          "She's taking photographs.",
          "She's talking on the phone.",
          "She's threading a needle.",
          "She's trimming her nails.",
          "She's tying her shoelaces.",
          "She's walking the dog.",
          "She's watering houseplants.",
          "She's winding a watch.",
          "She's writing a letter.",
          "They're building a puzzle.",
          "They're building a sandcastle.",
          "They're building a snowman.",
          "They're dancing at a party.",
          "They're decorating for a party.",
          "They're doing yoga.",
          "They're flying kites.",
          "They're having a barbecue.",
          "They're having a picnic.",
          "They're hiking in the mountains.",
          "They're making snow angels.",
          "They're planting trees.",
          "They're playing cards.",
          "They're playing charades.",
          "They're playing chess.",
          "They're playing frisbee.",
          "They're playing hide-and-seek.",
          "They're playing hopscotch.",
          "They're playing ping pong.",
          "They're playing tennis.",
          "They're playing volleyball.",
          "They're raking leaves.",
          "They're riding bicycles.",
          "They're roasting marshmallows.",
          "They're rowing a boat.",
          "They're shopping for groceries.",
          "They're singing karaoke.",
          "They're skating on ice.",
          "They're stargazing.",
          "They're studying for an exam.",
          "They're swimming in the pool.",
          "They're watching a movie.",
          "They're watching the sunset."
        ]
        
      },
    ],
    "data set 2": [
      {
        name: "Positive" as const,
        sentence: [
          "Jane isn't having dinner.",
          "She's watching TV.",
          "She's sitting on the floor.",
          "She isn't reading a book.",
          "She isn't playing the piano.",
          "She's laughing.",
          "She's wearing a hat.",
          "She isn't drinking coffee.",
          "Tom isn't cooking dinner.",
          "He's listening to music.",
          "He's sitting on the couch.",
          "He isn't washing dishes.",
          "He isn't talking on the phone.",
          "He's smiling.",
          "He's wearing headphones.",
          "He isn't eating a snack.",
          "Mary isn't studying.",
          "She's painting a picture.",
          "She's standing at an easel.",
          "She isn't using a computer.",
          "She isn't singing.",
          "She's concentrating.",
          "She's wearing an apron.",
          "She isn't looking out the window.",
          "John isn't sleeping.",
          "He's exercising.",
          "He's running on a treadmill.",
          "He isn't watching TV.",
          "He isn't listening to podcasts.",
          "He's sweating.",
          "He's wearing running shoes.",
          "He isn't drinking water.",
          "Sarah isn't cooking.",
          "She's gardening.",
          "She's kneeling in the dirt.",
          "She isn't watering plants.",
          "She isn't talking to neighbors.",
          "She's planting seeds.",
          "She's wearing gloves.",
          "She isn't using a lawnmower.",
          "David isn't working.",
          "He's playing video games.",
          "He's sitting in a gaming chair.",
          "He isn't reading a book.",
          "He isn't eating snacks.",
          "He's pressing buttons rapidly.",
          "He's wearing a headset.",
          "He isn't listening to music.",
          "Emma isn't shopping.",
          "She's doing yoga.",
          "She's balancing on one foot.",
          "She isn't watching a yoga video.",
          "She isn't talking to anyone.",
          "She's breathing deeply.",
          "She's wearing yoga pants.",
          "She isn't using yoga blocks.",
          "Michael isn't driving.",
          "He's fixing his car.",
          "He's lying under the vehicle.",
          "He isn't using power tools.",
          "He isn't listening to the radio.",
          "He's tightening bolts.",
          "He's wearing old clothes.",
          "He isn't checking the oil.",
          "Lisa isn't sleeping.",
          "She's writing in her journal.",
          "She's sitting at a desk.",
          "She isn't using a computer.",
          "She isn't talking on the phone.",
          "She's chewing on her pen.",
          "She's wearing glasses.",
          "She isn't drinking tea.",
          "Robert isn't watching a movie.",
          "He's building a model airplane.",
          "He's sitting at the kitchen table.",
          "He isn't using glue.",
          "He isn't talking to anyone.",
          "He's focusing intently.",
          "He's wearing reading glasses.",
          "He isn't following instructions.",
          "Anna isn't cleaning the house.",
          "She's baking cookies.",
          "She's standing by the oven.",
          "She isn't using a mixer.",
          "She isn't talking on the phone.",
          "She's rolling out dough.",
          "She's wearing an apron.",
          "She isn't tasting the batter.",
          "Peter isn't mowing the lawn.",
          "He's painting the fence.",
          "He's standing on a ladder.",
          "He isn't using a spray painter.",
          "He isn't listening to music.",
          "He's applying paint carefully.",
          "He's wearing old jeans.",
          "He isn't taking breaks.",
          "Sophie isn't watching TV.",
          "She's practicing ballet.",
          "She's standing at the barre.",
          "She isn't wearing shoes.",
          "She isn't looking in the mirror.",
          "She's moving gracefully.",
          "She's wearing a leotard.",
          "She isn't following a routine.",
          "Mark isn't playing sports.",
          "He's assembling furniture.",
          "He's kneeling on the floor.",
          "He isn't reading the instructions."
        ]        
      },
    ],
    "data set 3": [
      {
        name: "Positive" as const,
        sentence: [
          "He's changing a lightbulb.",
          "He's fixing the car.",
          "He's mowing the lawn.",
          "He's painting a picture.",
          "He's polishing his shoes.",
          "He's polishing silverware.",
          "He's programming a computer.",
          "He's repairing the roof.",
          "He's shaving his beard.",
          "He's taking photographs.",
          "He's tuning a guitar.",
          "He's writing a letter.",
          "I'm breathing deeply.",
          "I'm brushing my teeth.",
          "I'm charging my phone.",
          "I'm drinking coffee.",
          "I'm drinking water.",
          "I'm eating.",
          "I'm folding clothes.",
          "I'm hanging up laundry.",
          "I'm ironing my clothes.",
          "I'm learning English.",
          "I'm learning Spanish.",
          "I'm not cooking dinner.",
          "I'm not driving a car.",
          "I'm not listening to music.",
          "I'm not reading a newspaper.",
          "I'm not swimming.",
          "I'm not washing my hair.",
          "I'm packing my suitcase.",
          "I'm peeling potatoes.",
          "I'm sitting at a desk.",
          "I'm sitting on a chair.",
          "I'm solving a puzzle.",
          "I'm speaking English.",
          "I'm studying grammar.",
          "I'm thinking about lunch.",
          "I'm tying my shoelaces.",
          "I'm typing on a keyboard.",
          "I'm washing my hands.",
          "I'm wearing a hat.",
          "I'm wearing a watch.",
          "I'm wearing glasses.",
          "I'm wearing shoes.",
          "I'm wearing socks.",
          "I'm wrapping a gift.",
          "I'm writing an email.",
          "It isn't freezing.",
          "It isn't raining.",
          "It isn't snowing.",
          "It isn't storming.",
          "It isn't windy today.",
          "She's baking cookies.",
          "She's blow-drying her hair.",
          "She's combing her hair.",
          "She's feeding the fish.",
          "She's knitting a scarf.",
          "She's planting flowers.",
          "She's playing the piano.",
          "She's reading a book.",
          "She's setting an alarm.",
          "She's sewing a dress.",
          "She's stirring soup.",
          "She's watering the plants.",
          "The artist is sketching a portrait.",
          "The audience is applauding.",
          "The baby is crawling on the floor.",
          "The baby is crying.",
          "The birds are building a nest.",
          "The birds are singing.",
          "The car is moving slowly.",
          "The cat is cleaning itself.",
          "The cat is purring.",
          "The chef is chopping vegetables.",
          "The chef is cooking pasta.",
          "The children are drawing pictures.",
          "The children are playing.",
          "The clock is ticking.",
          "The dentist is examining teeth.",
          "The dog is chasing a ball.",
          "The dog is sleeping.",
          "The farmers are harvesting crops.",
          "The flowers are blooming.",
          "The leaves are falling.",
          "The mechanic is changing oil.",
          "The phone is ringing.",
          "The students are taking notes.",
          "The sun is shining.",
          "The teacher is explaining.",
          "The train is arriving.",
          "The wind is blowing gently.",
          "They're assembling furniture.",
          "They're building a sandcastle.",
          "They're cleaning the windows.",
          "They're climbing a mountain.",
          "They're dancing at a party.",
          "They're inflating balloons.",
          "They're raking leaves.",
          "They're riding bicycles.",
          "They're setting the table.",
          "They're singing a song.",
          "They're swimming in the pool.",
          "They're watching television.",
          "We're booking a hotel.",
          "We're decorating the room.",
          "We're exercising in the gym.",
          "We're having a meeting.",
          "We're having dinner.",
          "We're organizing a party.",
          "We're planning a trip.",
          "We're rehearsing a play.",
          "We're shopping for groceries.",
          "We're solving a crossword puzzle.",
          "We're waiting for the bus.",
          "We're walking in the park."
        ]
        
      },
    ],
    "data set 4": [
      {
        name: "Positive" as const,
        sentence: [
          "Can I borrow your car? Sorry, I'm using it this afternoon.",
          "Can I use your phone? Not at the moment, I'm expecting an important call.",
          "Can we talk? Not now, I'm writing an important email.",
          "Can you help me move this sofa? Not now, I'm on a conference call.",
          "Can you help me? Sorry, I'm working on a report.",
          "Please be quiet. I'm studying.",
          "Where's Alex? He's in the basement. He's doing laundry.",
          "Where's Amanda? She's at the hair salon. She's getting a haircut.",
          "Where's Claire? She's in her room. She's practicing the violin.",
          "Where's Dad? He's in the garage. He's fixing the car.",
          "Where's Daniel? He's at the airport. He's picking up his sister.",
          "Where's David? He's mowing the lawn.",
          "Where's Dr. Smith? She's in surgery. She's operating on a patient.",
          "Where's Emily? She's in the backyard. She's hanging up laundry.",
          "Where's Emma? She's walking the dog.",
          "Where's Grandpa? He's in the garden. He's feeding the birds.",
          "Where's Jessica? She's at the library. She's studying for exams.",
          "Where's Kate? She's at the gym. She's doing yoga.",
          "Where's Kevin? He's at the gym. He's working out.",
          "Where's Linda? She's at the supermarket. She's buying groceries.",
          "Where's Lisa? She's in the garden. She's planting flowers.",
          "Where's Mike? He's taking a nap.",
          "Where's Mom? She's in the attic. She's looking for old photos.",
          "Where's Mr. Brown? He's in a meeting. He's presenting a new project.",
          "Where's Peter? He's having a meeting with his boss.",
          "Where's Professor Johnson? He's in his office. He's grading papers.",
          "Where's Robert? He's at the dentist. He's getting a checkup.",
          "Where's Sarah? She's in the living room. She's watching TV.",
          "Where's Sophia? She's at the post office. She's mailing a package.",
          "Where's Tom? He's upstairs. He's packing his suitcase.",
          "Where's Uncle Jim? He's in the attic. He's looking for his old guitar.",
          "Why are you carrying an umbrella? I'm preparing for the forecasted rain.",
          "Why are you dressed up? I'm going to a wedding.",
          "Why are you smiling? I'm thinking about my vacation next week.",
          "Why are you wearing a coat? I'm going for a walk. It's cold outside.",
          "Why are you whispering? The baby's sleeping.",
          "You're blocking the doorway. Oh, I'm moving.",
          "You're blocking the fire exit. I'm sorry, I'm moving immediately.",
          "You're blocking the view. My apologies, I'm moving aside.",
          "You're dripping water on the floor. Sorry, I'm getting a towel.",
          "You're sitting in my seat. I apologize, I'm moving right now.",
          "You're spilling your coffee. Oh, I'm cleaning it up right away.",
          "You're standing on my foot. I'm so sorry, I'm stepping back.",
          "You're standing on my toes. I'm so sorry!",
          "You're stepping on my drawing. Oh no, I'm so sorry!",
          "You're using my pen. Oh, I didn't realize. I'm giving it back.",
          "Your car alarm is going off. Thanks for telling me. I'm deactivating it now.",
          "Your cat is scratching the sofa. I'm stopping her right away.",
          "Your dog is barking loudly. I'm bringing him inside now.",
          "Your music is too loud. Sorry, I'm turning it down.",
          "Your phone is ringing. Thanks, I'm answering it now.",
          "I'm calling it a night. See you in the morning.",
          "I'm clocking out now. Have a great weekend.",
          "I'm going now. Goodbye.",
          "I'm heading out. Bye for now.",
          "I'm heading to bed. Goodnight.",
          "I'm leaving now. See you later.",
          "I'm logging off now. Have a good evening.",
          "I'm running late. I'll see you there.",
          "I'm signing off now. Talk to you tomorrow.",
          "I'm turning in for the night. Sleep well.",
          "I'm wrapping up for the day. See you tomorrow.",
          "Look! A group of kids is playing soccer in the park.",
          "Look! A group of tourists is taking a guided tour of the museum.",
          "Look! A photographer is taking pictures of the sunset.",
          "Look! A street artist is performing magic tricks.",
          "Look! A street musician is playing the violin on the corner.",
          "Look! Somebody's swimming in the river.",
          "Look! Someone's flying a kite on the beach.",
          "Look! Someone's painting the old bridge.",
          "Look! The artist is finishing her mural on the community center wall.",
          "Look! The bakers are preparing fresh bread for the morning.",
          "Look! The chef is giving a cooking demonstration.",
          "Look! The farmer's harvesting the wheat field.",
          "Look! The gardener is pruning the roses in the park.",
          "Look! The leaves are changing color.",
          "Look! The sun's setting over the mountains.",
          "Look! The theater group is rehearsing in the park.",
          "Please be quiet. I’m working.",
          "The city council is planning to build a new community center.",
          "The city is expanding the subway system this year.",
          "The construction company is building a new bridge across the river.",
          "The local government is improving the city's recycling program.",
          "They're building a new hotel in the city centre at the moment.",
          "They're building a new shopping mall near the station.",
          "They're conducting a survey about local transportation this month.",
          "They're conducting maintenance on the subway tracks this weekend.",
          "They're filming a documentary about local wildlife this week.",
          "They're filming a movie in the town square today.",
          "They're here for a family reunion. They're staying at a local bed and breakfast.",
          "They're here for a music festival. They're camping in the nearby fields.",
          "They're here on business. They're attending a conference.",
          "They're renovating the public library this month.",
          "They're visiting for the weekend. They're staying at a nearby hotel.",
          "We're adopting a puppy from the local shelter next week.",
          "We're here for work. We're staying at the Grand Hotel.",
          "We're here on holiday. We're staying at the Central Hotel.",
          "We're housesitting for our neighbors this week.",
          "We're learning Spanish for our trip to Mexico.",
          "We're on vacation. We're camping by the lake.",
          "We're planning a surprise party for Mom's birthday.",
          "We're redecorating our apartment this month.",
          "We're renting a cottage by the sea for our vacation.",
          "We're saving money for a big trip next year.",
          "We're staying indoors today. It's raining heavily.",
          "Where’s John? He's in the kitchen. He's cooking.",
          "Where’s Sue? She's having a shower.",
          "You're standing on my foot. Oh, I'm sorry."
        ]
        
      },
    ],
  },
];

export default data;
