// data.ts
const data = [
  {
    name: "MySelf",
    noun: [
      {
        name: "Negative" as const,
        sentence: [
          "I'm not a student",
          "I'm not a teacher",
          "I'm not an engineer",
        ],
      },
      {
        name: "Positive" as const,
        sentence: [
          "I'm Aima",
          "I'm 6 years old",
          "I'm Pakistani",
          "I'm from Rawalpindi",
          "I'm a student",
          "I'm a carpenter",
          "I'm a baker",
          "I'm a boss",
          "I'm a brother",
          "I'm a captain",
          "I'm a cashier",
          "I'm a champion",
          "I'm a chef",
          "I'm a clerk",
          "I'm a clown",
          "I'm a coach",
          "I'm a cousin",
          "I'm a cowboy",
          "I'm a customer",
          "I'm a dancer",
          "I'm a daughter",
          "I'm a dentist",
          "I'm a designer",
          "I'm a detective",
          "I'm a doctor",
          "I'm a driver",
          "I'm a farmer",
          "I'm a father",
          "I'm a firefighter",
          "I'm a follower",
          "I'm a friend",
          "I'm a gardener",
          "I'm a general",
          "I'm a grandma",
          "I'm a grandpa",
          "I'm a historian",
          "I'm a human",
          "I'm a judge",
          "I'm a juggler",
          "I'm a king",
          "I'm a knight",
          "I'm a lawyer",
          "I'm a leader",
          "I'm a librarian",
          "I'm a lifeguard",
          "I'm a magician",
          "I'm a manager",
          "I'm a mechanic",
          "I'm a mime",
          "I'm a mother",
          "I'm a musician",
          "I'm a neighbor",
          "I'm a ninja",
          "I'm a nurse",
          "I'm a painter",
          "I'm a passenger",
          "I'm a photographer",
          "I'm a pilot",
          "I'm a pirate",
          "I'm a plumber",
          "I'm a poet",
          "I'm a police officer",
          "I'm a politician",
          "I'm a president",
          "I'm a prince",
          "I'm a princess",
          "I'm a programmer",
          "I'm a queen",
          "I'm a receptionist",
          "I'm a referee",
          "I'm a reporter",
          "I'm a sailor",
          "I'm a salesman",
          "I'm a samurai",
          "I'm a scientist",
          "I'm a sculptor",
          "I'm a secretary",
          "I'm a sister",
          "I'm a soldier",
          "I'm a son",
          "I'm a spy",
          "I'm a student",
          "I'm a superhero",
          "I'm a teacher",
          "I'm a vet",
          "I'm a villain",
          "I'm a waiter",
          "I'm a wizard",
          "I'm a writer",
          "I'm a zookeeper",
          "I'm an acrobat",
          "I'm an actor",
          "I'm an archaeologist",
          "I'm an architect",
          "I'm an artist",
          "I'm an astronaut",
          "I'm an athlete",
          "I'm an aunt",
          "I'm an electrician",
          "I'm an enemy",
          "I'm an engineer",
          "I'm an entrepreneur",
          "I'm an explorer",
          "I'm an inventor",
          "I'm an uncle",
        ],
      },
      {
        name: "Yes/No Questions" as const,
        sentence: ["Am I a student?", "Am I a teacher?", "Am I an engineer?"],
      },
    ],
    adjective: [
      {
        name: "Negative" as const,
        sentence: ["I'm not happy", "I'm not tired", "I'm not busy"],
      },
      {
        name: "Positive" as const,
        sentence: ["I'm happy", "I'm tired", "I'm busy"],
      },
      {
        name: "Yes/No Questions" as const,
        sentence: ["Am I happy?", "Am I tired?", "Am I busy?"],
      },
    ],
    preposition: [
      {
        name: "Negative" as const,
        sentence: [
          "I'm not at home",
          "I'm not in the office",
          "I'm not on vacation",
        ],
      },
      {
        name: "Positive" as const,
        sentence: ["I'm at home", "I'm in the office", "I'm on vacation"],
      },
      {
        name: "Yes/No Questions" as const,
        sentence: ["Am I at home?", "Am I in the office?", "Am I on vacation?"],
      },
    ],
    objective: [
      {
        name: "Negative" as const,
        sentence: [
          "I'm not at home",
          "I'm not in the office",
          "I'm not on vacation",
        ],
      },
      {
        name: "Positive" as const,
        sentence: ["I'm at home", "I'm in the office", "I'm on vacation"],
      },
      {
        name: "Yes/No Questions" as const,
        sentence: ["Am I at home?", "Am I in the office?", "Am I on vacation?"],
      },
    ],
    possesive: [
      {
        name: "Negative" as const,
        sentence: [
          "I'm not at home",
          "I'm not in the office",
          "I'm not on vacation",
        ],
      },
      {
        name: "Positive" as const,
        sentence: ["I'm at home", "I'm in the office", "I'm on vacation"],
      },
      {
        name: "Yes/No Questions" as const,
        sentence: ["Am I at home?", "Am I in the office?", "Am I on vacation?"],
      },
    ],
  },
];

export default data;
