export const colorSchemes = {
  tealIndigo: {
    name: "Teal & Indigo",
    from: "from-teal-400",
    to: "to-indigo-600",
    gradientFrom: "from-teal-500",
    gradientTo: "to-indigo-500",
    bgFrom: "from-teal-100",
    bgTo: "to-indigo-100",
  },
  pinkYellow: {
    name: "Pink & Yellow",
    from: "from-pink-400",
    to: "to-yellow-400",
    gradientFrom: "from-pink-500",
    gradientTo: "to-yellow-500",
    bgFrom: "from-pink-100",
    bgTo: "to-yellow-100",
  },
  yellowOrange: {
    name: "Yellow & Orange",
    from: "from-yellow-400",
    to: "to-orange-500",
    gradientFrom: "from-yellow-500",
    gradientTo: "to-orange-600",
    bgFrom: "from-yellow-100",
    bgTo: "to-orange-100",
  },
  blueSkyBlue: {
    name: "Blue & Sky Blue",
    from: "from-blue-400",
    to: "to-sky-400",
    gradientFrom: "from-blue-500",
    gradientTo: "to-sky-500",
    bgFrom: "from-blue-100",
    bgTo: "to-sky-100",
  },
  indigoPurple: {
    name: "Indigo & Purple",
    from: "from-indigo-400",
    to: "to-purple-500",
    gradientFrom: "from-indigo-500",
    gradientTo: "to-purple-600",
    bgFrom: "from-indigo-100",
    bgTo: "to-purple-100",
  },
  redPink: {
    name: "Red & Pink",
    from: "from-red-400",
    to: "to-pink-500",
    gradientFrom: "from-red-500",
    gradientTo: "to-pink-600",
    bgFrom: "from-red-100",
    bgTo: "to-pink-100",
  },
};

export type ColorScheme = keyof typeof colorSchemes;