// data.ts
const data = [
  {
    name: "MySelf",
    "data set 1": [
      {
        name: "Positive" as const,
        sentence: [
          "Where's the camera? In your bag.",
          "Is your car blue? No, it's black.",
          "Is Kate from London? No, she's American.",
          "Am I late? Yes, you are.",
          "Where's Amy from? London.",
          "What color is your bag? Black.",
          "Are you hungry? No, I'm not.",
          "How is George? Very well.",
          "Who's that woman? My sister.",
          "Where's the book? On the shelf.",
          "Is your phone new? Yes, it is.",
          "Is Mark from Paris? No, he's Italian.",
          "Am I early? No, you're on time.",
          "Where's Sarah from? New York.",
          "What color is your shirt? White.",
          "Are you tired? Yes, I am.",
          "How is Lisa? She's fine.",
          "Who's that man? My father.",
          "Where's the remote? Under the couch.",
          "Is your house big? No, it's small.",
          "Is Tom a teacher? No, he's a doctor.",
          "Are we lost? Yes, we are.",
          "Where's the nearest store? Around the corner.",
          "What time is it? Half past three.",
          "Are you thirsty? Yes, very.",
          "How's the weather? Sunny and warm.",
          "Who's calling? It's Mike.",
          "Where's my wallet? In your jacket.",
          "Is the museum open? No, it's closed.",
          "Is Emily married? Yes, she is.",
          "Am I right? No, you're wrong.",
          "Where's the bathroom? Down the hall.",
          "What's your favorite color? Blue.",
          "Are you ready? Not yet.",
          "How's your coffee? Too hot.",
          "Who's next? You are.",
          "Where's the meeting? In room 302.",
          "Is this seat taken? No, it's free.",
          "Is John coming? No, he's busy.",
          "Are we there yet? Almost.",
          "Where's the exit? To your left.",
          "What's for dinner? Pasta.",
          "Are you sure? Yes, definitely.",
          "How's your family? They're well.",
          "Who won the game? The home team.",
          "Where's the station? Two blocks away.",
          "Is this yours? No, it's hers.",
          "Is the flight on time? No, it's delayed.",
          "Am I disturbing you? Not at all.",
          "Where's the conference? At the Hilton.",
          "What's your job? I'm an engineer.",
          "Are you married? No, I'm single.",
          "How's the food? Delicious.",
          "Who's in charge here? The manager.",
          "Where's the library? Across the street.",
          "Is this the right bus? No, you need the 42.",
          "Is Jane coming? Yes, she'll be late.",
          "Are we meeting tomorrow? No, on Friday.",
          "Where's the party? At David's house.",
          "What's the password? It's 'sunflower'.",
          "Are you allergic? Yes, to peanuts.",
          "How's your new car? It's great.",
          "Who's that kid? My nephew.",
          "Where's the airport? 20 miles north.",
          "Is this seat comfortable? Not really.",
          "Is Peter a good cook? Yes, he's excellent.",
          "Am I interrupting? No, go ahead.",
          "Where's the nearest ATM? In the lobby.",
          "What's your major? Computer Science.",
          "Are you local? No, I'm visiting.",
          "How's business? Booming.",
          "Who's presenting today? Dr. Smith.",
          "Where's the restroom? To your right.",
          "Is this water safe to drink? Yes, it is.",
          "Is the store open? Yes, until 9 PM.",
          "Are we late for the movie? No, we have time.",
          "Where's the reception? On the second floor.",
          "What's the Wi-Fi password? It's 'welcome123'.",
          "Are you feeling better? Yes, much better.",
          "How's the project going? On schedule.",
          "Who's the author? J.K. Rowling.",
          "Where's the nearest pharmacy? Two blocks south.",
          "Is this the express train? No, it's local.",
          "Is Mary still working here? No, she left.",
          "Am I doing this right? Yes, perfect.",
          "Where's the fire exit? Behind you.",
          "What's the special today? Grilled salmon.",
          "Are you vegetarian? No, I eat meat.",
          "How's your back? Much improved.",
          "Who's the new manager? Ms. Johnson.",
          "Where's the lost and found? Near the entrance.",
          "Is this gluten-free? Yes, it is.",
          "Is the concert cancelled? No, just postponed.",
          "Are we allowed to park here? Yes, it's free.",
          "Where's the charging station? In the corner.",
          "What's the exchange rate? 1.2 to the dollar.",
          "Are you staying long? Just for the weekend.",
          "How's the new apartment? Spacious and bright.",
          "Who's next in line? You are.",
          "Where's the checkout? At the front.",
          "Is this seat taken? No, feel free.",
          "Is the game over? Yes, we won.",
          "Am I pronouncing it correctly? Yes, you are.",
          "Where's the nearest bus stop? Across the park.",
          "What's the dress code? Smart casual.",
          "Are you coming to the party? Yes, I'll be there.",
          "How's your new job? Challenging but fun.",
          "Who's responsible for this? The marketing team.",
          "Where's the conference room? End of the hallway.",
        ],
      },
    ],
    "data set 2": [
      {
        name: "Positive" as const,
        sentence: [
          "Is your mother at home?",
          "Are your parents well?",
          "Is your job interesting?",
          "Are the shops open today?",
          "Where are you from?",
          "Are you interested in sport?",
          "Is the station near here?",
          "Are your children at school?",
          "Why are you late?",
          "Is your brother at work?",
          "Are your grandparents visiting?",
          "Is your car working?",
          "Are the restaurants busy tonight?",
          "Where are you going?",
          "Are you allergic to peanuts?",
          "Is the museum open on Sundays?",
          "Are your neighbors friendly?",
          "Why are you studying English?",
          "Is your dog well-trained?",
          "Are your shoes comfortable?",
          "Is the movie interesting?",
          "Are the buses running today?",
          "Where are the bathrooms?",
          "Are you excited about the trip?",
          "Is the water safe to drink?",
          "Are your classes difficult?",
          "Why are you moving?",
          "Is your apartment spacious?",
          "Are the tickets expensive?",
          "Is the concert tonight?",
          "Are your friends coming?",
          "Where are my keys?",
          "Are you familiar with this area?",
          "Is the gym crowded?",
          "Are your exams over?",
          "Why are you smiling?",
          "Is your phone charged?",
          "Are the flowers fresh?",
          "Is the weather nice today?",
          "Are your parents retired?",
          "Where are we meeting?",
          "Are you ready to order?",
          "Is the coffee hot?",
          "Are the children asleep?",
          "Why are you here?",
          "Is your sister married?",
          "Are the stores open late?",
          "Is the party tomorrow?",
          "Are you feeling better?",
          "Where are they from?",
          "Are you staying for dinner?",
          "Is the book interesting?",
          "Are the beaches clean?",
          "Why are you leaving early?",
          "Is your team winning?",
          "Are the directions clear?",
          "Is the hotel comfortable?",
          "Are you looking for something?",
          "Where are we going?",
          "Are you free this weekend?",
          "Is the food spicy?",
          "Are the trains on time?",
          "Why are you upset?",
          "Is your boss strict?",
          "Are the prices reasonable?",
          "Is the library quiet?",
          "Are you enjoying the party?",
          "Where are my glasses?",
          "Are you scared of heights?",
          "Is the traffic heavy?",
          "Are your relatives visiting?",
          "Why are you laughing?",
          "Is your computer working?",
          "Are the streets safe at night?",
          "Is the air conditioning on?",
          "Are you learning French?",
          "Where are the elevators?",
          "Are you tired from work?",
          "Is the restaurant expensive?",
          "Are the windows open?",
          "Why are you whispering?",
          "Is your watch accurate?",
          "Are the batteries included?",
          "Is the park crowded?",
          "Are you going on vacation?",
          "Where are the emergency exits?",
          "Are you allergic to cats?",
          "Is the wifi working?",
          "Are the rooms clean?",
          "Why are you excited?",
          "Is your passport valid?",
          "Are the paintings original?",
          "Is the pool heated?",
          "Are you feeling nervous?",
          "Where are the toilets?",
          "Are you staying late?",
          "Is the taxi here?",
          "Are the instructions clear?",
          "Why are you dressed up?",
          "Is your suitcase packed?",
          "Are the flights on schedule?",
          "Is the building old?",
          "Are you satisfied with the service?",
          "Where are we eating?",
          "Are you good at math?",
          "Is the ice cream homemade?",
          "Are the seats comfortable?",
          "Why are you in a hurry?",
          "Is your hometown big?",
        ],
      },
    ],
    "data set 3": [
      {
        name: "Positive" as const,
        sentence: [
          "How are your parents? They're very well.",
          "Where is the bus stop? At the end of the street.",
          "How old are your children? Five, six, and ten.",
          "How much are these oranges? $1.5 a kilo.",
          "What is your favorite sport? Skiing.",
          "Who's the man in this photo? That's my father.",
          "What color are your new shoes? Black.",
          "What time is it? It's half past three.",
          "Where's the nearest bank? Two blocks down on the left.",
          "How tall are you? I'm 5 feet 10 inches.",
          "What's your favorite food? I love pizza.",
          "When's your birthday? It's on June 10th.",
          "How many siblings do you have? I have two brothers.",
          "What's the weather like today? It's sunny and warm.",
          "Where did you go to college? I went to Stanford University.",
          "What's your dog's name? His name is Max.",
          "How long have you lived here? For about five years now.",
          "What's your favorite movie? I really enjoy The Godfather.",
          "Where are you from originally? I'm from Chicago.",
          "How do you get to work? I usually take the subway.",
          "What's your favorite book? To Kill a Mockingbird.",
          "How old is your car? It's about three years old.",
          "What's your job? I'm a software engineer.",
          "Where's the restroom? Down the hall on the right.",
          "What time does the store close? It closes at 9 PM.",
          "How many languages do you speak? I speak three languages fluently.",
          "What's your favorite color? I really like blue.",
          "Where did you go on vacation? We went to Hawaii last summer.",
          "How long is the movie? It's about two hours long.",
          "What's your phone number? It's 555-1234.",
          "Where can I buy tickets? At the box office near the entrance.",
          "How much does it cost? It's $20 per person.",
          "What's your favorite season? I love autumn.",
          "Where's the nearest gas station? About a mile down the road.",
          "How often do you exercise? I try to exercise three times a week.",
          "What's your favorite TV show? I enjoy watching Friends.",
          "Where do you work? I work at a local marketing firm.",
          "How long have you been married? We've been married for 12 years.",
          "What's your shoe size? I wear a size 9.",
          "Where's the library? It's across from the park.",
          "How many people are coming? We're expecting about 50 guests.",
          "What's your favorite hobby? I enjoy gardening in my free time.",
          "Where can I park my car? There's a parking lot behind the building.",
          "How much sugar do you want? Just one teaspoon, please.",
          "What's your email address? It's johndoe@email.com.",
          "Where's the nearest hospital? It's about 3 miles north of here.",
          "How long does the flight take? It's a 4-hour flight.",
          "What's your favorite ice cream flavor? I love chocolate chip.",
          "Where did you buy that shirt? I got it at the mall downtown.",
          "How many eggs do we need? We need a dozen eggs.",
          "What's your favorite restaurant? I really like the Italian place on Main Street.",
          "Where's the meeting being held? In the conference room on the 3rd floor.",
          "How do you spell your name? It's S-M-I-T-H.",
          "What's the capital of France? The capital of France is Paris.",
          "Where's the remote control? It's on the coffee table.",
          "How much does shipping cost? Shipping is $5 for standard delivery.",
          "What's your favorite holiday? I really enjoy Christmas.",
          "Where can I find a good dentist? Dr. Johnson on Oak Street is excellent.",
          "How long does it take to get there? It's about a 30-minute drive.",
          "What's your favorite type of music? I'm a big fan of jazz.",
          "Where's the nearest ATM? There's one inside the grocery store.",
          "How many pages is the report? The report is 15 pages long.",
          "What's your favorite animal? I've always loved elephants.",
          "Where did you learn to cook? I learned from my grandmother.",
          "How often do you water the plants? I water them twice a week.",
          "What's your blood type? My blood type is O positive.",
          "Where's the best place to watch the sunset? From the hilltop park.",
          "How long have you been studying French? For about two years now.",
          "What's your favorite dessert? I love chocolate mousse.",
          "Where can I buy fresh produce? At the farmer's market on Saturdays.",
          "How much does a membership cost? It's $50 per month.",
          "What's your zodiac sign? I'm a Taurus.",
          "Where's the lost and found? It's at the customer service desk.",
          "How do you like your coffee? I prefer it black with no sugar.",
          "What's your favorite day of the week? I always look forward to Fridays.",
          "Where can I recycle these bottles? There's a recycling center downtown.",
          "How long is your lunch break? I get an hour for lunch.",
          "What's your favorite subject in school? I really enjoy science classes.",
          "Where's the nearest bus stop? It's just around the corner.",
          "How many calories are in this? It contains about 300 calories.",
          "What's your favorite sport to watch? I love watching tennis.",
          "Where did you learn to dance? I took lessons at the community center.",
          "How often do you get haircuts? I get a trim every six weeks.",
          "What's your favorite vegetable? I'm a big fan of broccoli.",
          "Where's the best place to go hiking? There are great trails in the state park.",
          "How much did the tickets cost? They were $75 each.",
          "What's your favorite season? I love the colors of autumn.",
          "Where can I find a good plumber? Bob's Plumbing on Elm Street is reliable.",
          "How long does the warranty last? The warranty is good for two years.",
          "What's your favorite childhood memory? Building sandcastles at the beach.",
          "Where's the closest fire station? It's about five blocks north of here.",
          "How many rooms does the house have? It has four bedrooms and two bathrooms.",
          "What's your go-to comfort food? I always crave mac and cheese.",
          "Where did you meet your best friend? We met in high school.",
          "How long does it take to bake the cake? It needs to bake for 35 minutes.",
          "What's your favorite holiday tradition? Decorating the Christmas tree together.",
          "Where can I find a good gym? There's a great fitness center on Pine Street.",
          "How much does a ticket cost? Tickets are $15 for adults.",
          "What's your dream vacation destination? I'd love to visit New Zealand.",
          "Where's the closest pharmacy? There's one in the shopping center nearby.",
          "How often do trains run? They run every 15 minutes during peak hours.",
          "What's your favorite type of cuisine? I'm a big fan of Thai food.",
          "Where can I donate clothes? The charity shop on Main Street accepts donations.",
          "How long have you been a vegetarian? For about five years now.",
          "What's your shoe size? I wear a size 8.",
          "Where's the best place to watch the game? The sports bar downtown has great screens.",
          "How much does parking cost? It's $2 per hour in the city center.",
        ],
      },
    ],
    "data set 4": [
      {
        name: "Positive" as const,
        sentence: [
          "What's your name? Aima.",
          "Are you American? No, I'm Pakistani.",
          "How old are you? I'm 30.",
          "Are you a teacher? No, I'm a lawyer.",
          "Are you married? Yes, I am.",
          "Is your wife a lawyer? No, she's a designer.",
          "Where is she from? She's Italian.",
          "What's her name? Aiza.",
          "How old is she? She's 5.",
          "What's your occupation? I'm a doctor.",
          "Do you speak French? Yes, I do.",
          "How tall are you? I'm 5'8\".",
          "Are you left-handed? No, I'm right-handed.",
          "Do you have siblings? Yes, two brothers.",
          "Where do you live? In New York City.",
          "Can you swim? Yes, very well.",
          "Do you like spicy food? Yes, I love it.",
          "What's your favorite color? Blue.",
          "Are you allergic to anything? Yes, peanuts.",
          "Do you play an instrument? Yes, the piano.",
          "How long have you lived here? For 10 years.",
          "Do you have pets? Yes, a cat and a dog.",
          "What's your shoe size? It's a 9.",
          "Can you drive? Yes, I have a license.",
          "Do you wear glasses? Only for reading.",
          "What's your blood type? It's A positive.",
          "Are you vegetarian? No, I eat meat.",
          "Do you smoke? No, I don't.",
          "What's your favorite sport? Basketball.",
          "Are you an only child? No, I have a sister.",
          "Do you like coffee? Yes, I drink it daily.",
          "What's your zodiac sign? I'm a Libra.",
          "Can you cook? Yes, I enjoy cooking.",
          "Do you exercise regularly? Yes, three times a week.",
          "What's your favorite season? Summer.",
          "Are you religious? Yes, I'm Buddhist.",
          "Do you speak any other languages? Yes, Spanish and German.",
          "What's your eye color? Brown.",
          "Are you a morning person? No, I'm a night owl.",
          "Do you have any allergies? Yes, to pollen.",
          "What's your favorite fruit? Mangoes.",
          "Can you whistle? No, I never learned how.",
          "Do you like to dance? Yes, I love dancing.",
          "What's your favorite day of the week? Friday.",
          "Are you a good singer? No, I'm tone-deaf.",
          "Do you wear contact lenses? Yes, daily.",
          "What's your favorite movie genre? Science fiction.",
          "Can you ride a bike? Yes, since childhood.",
          "Do you have any tattoos? Yes, one on my arm.",
          "What's your favorite book? 'To Kill a Mockingbird'.",
          "Are you afraid of heights? Yes, terrified.",
          "Do you like to travel? Yes, I travel often.",
          "What's your favorite cuisine? Italian food.",
          "Can you juggle? No, I've never tried.",
          "Do you have a driver's license? Yes, for 12 years now.",
          "What's your favorite animal? Dolphins.",
          "Are you a good dancer? I'm decent, not great.",
          "Do you like rollercoasters? No, they scare me.",
          "What's your favorite ice cream flavor? Mint chocolate chip.",
          "Can you speak sign language? No, but I'd like to learn.",
          "Do you prefer tea or coffee? I prefer tea.",
          "What's your favorite holiday? Christmas.",
          "Are you a fast reader? Yes, quite fast.",
          "Do you play video games? Occasionally, not often.",
          "What's your favorite TV show? 'Breaking Bad'.",
          "Can you swim? Yes, I'm a good swimmer.",
          "Do you like camping? Yes, I go every summer.",
          "What's your favorite dessert? Tiramisu.",
          "Are you good at math? Yes, I've always enjoyed it.",
          "Do you have any phobias? Yes, fear of spiders.",
          "What's your favorite vegetable? Broccoli.",
          "Can you speak multiple languages? Yes, three languages.",
          "Do you like puzzles? Yes, especially crosswords.",
          "What's your favorite season? Autumn.",
          "Are you a good cook? I'm decent, still learning.",
          "Do you collect anything? Yes, vintage cameras.",
          "What's your favorite type of music? Classical.",
          "Can you play chess? Yes, I play regularly.",
          "Do you like public speaking? No, it makes me nervous.",
          "What's your favorite subject? History.",
          "Are you an early bird? Yes, I wake up at 5 AM.",
          "Do you have any siblings? Yes, an older brother.",
          "What's your favorite drink? Green tea.",
          "Can you rollerskate? No, I never learned.",
          "Do you like to read? Yes, I read daily.",
          "What's your favorite childhood memory? Building snowmen.",
          "Are you good at drawing? No, I'm not artistic.",
          "Do you have any nicknames? Yes, my friends call me 'Mac'.",
          "What's your favorite hobby? Photography.",
          "Can you touch your toes? Yes, I'm quite flexible.",
          "Do you like surprises? No, I prefer planning.",
          "What's your dream job? Being a novelist.",
          "Are you a good listener? Yes, I'm very empathetic.",
          "Do you believe in ghosts? No, I'm skeptical.",
          "What's your favorite pizza topping? Mushrooms.",
          "Can you do a handstand? No, I've never tried.",
          "Do you like documentaries? Yes, I find them fascinating.",
          "What's your favorite cartoon? 'The Simpsons'.",
          "Are you a cat person or dog person? I prefer dogs.",
          "Do you enjoy gardening? Yes, it's very relaxing.",
          "What's your favorite sandwich? BLT.",
          "Can you ice skate? Yes, but not very well.",
          "Do you like spicy food? Yes, the spicier the better.",
          "What's your favorite board game? Monopoly.",
          "Are you good at keeping secrets? Yes, very trustworthy.",
          "Do you like to sing karaoke? No, I'm too shy.",
          "What's your favorite time of day? Early morning.",
          "Can you speak any dead languages? Yes, I know Latin.",
          "Do you believe in aliens? I'm open to the possibility.",
        ],
      },
    ],
    "data set 5": [
      {
        name: "Positive" as const,
        sentence: [
          "Are you married? No, I'm not.",
          "Are you thirsty? Yes, I am.",
          "Is it cold today? Yes, it is.",
          "Are your hands cold? No, they aren't.",
          "Is it dark now? Yes, it is.",
          "Are you a teacher? Yes, I am.",
          "Are you hungry? Yes, I am.",
          "Is it raining? No, it isn't.",
          "Are you tired? Yes, I am.",
          "Is the store open? Yes, it is.",
          "Are you American? No, I'm not.",
          "Is it sunny today? Yes, it is.",
          "Are you a doctor? No, I'm not.",
          "Is the movie good? Yes, it is.",
          "Are you busy? No, I'm not.",
          "Is the water hot? Yes, it is.",
          "Are you happy? Yes, I am.",
          "Is the door locked? No, it isn't.",
          "Are you late? Yes, I am.",
          "Is the coffee fresh? Yes, it is.",
          "Are you sick? No, I'm not.",
          "Is the book interesting? Yes, it is.",
          "Are you ready? Yes, I am.",
          "Is the car new? No, it isn't.",
          "Are you alone? Yes, I am.",
          "Is the food spicy? Yes, it is.",
          "Are you tall? No, I'm not.",
          "Is the music loud? Yes, it is.",
          "Are you a student? Yes, I am.",
          "Is the room clean? No, it isn't.",
          "Are you excited? Yes, I am.",
          "Is the computer working? Yes, it is.",
          "Are you rich? No, I'm not.",
          "Is the dog friendly? Yes, it is.",
          "Are you worried? Yes, I am.",
          "Is the train late? No, it isn't.",
          "Are you a vegetarian? Yes, I am.",
          "Is the TV on? Yes, it is.",
          "Are you sleepy? Yes, I am.",
          "Is the window open? No, it isn't.",
          "Are you famous? No, I'm not.",
          "Is the cake sweet? Yes, it is.",
          "Are you early? Yes, I am.",
          "Is the road busy? Yes, it is.",
          "Are you cold? No, I'm not.",
          "Is the grass wet? Yes, it is.",
          "Are you an artist? No, I'm not.",
          "Is the sky blue? Yes, it is.",
          "Are you scared? No, I'm not.",
          "Is the milk fresh? Yes, it is.",
          "Are you a parent? Yes, I am.",
          "Is the building tall? Yes, it is.",
          "Are you single? Yes, I am.",
          "Is the fruit ripe? No, it isn't.",
          "Are you a writer? Yes, I am.",
          "Is the party fun? Yes, it is.",
          "Are you bored? No, I'm not.",
          "Is the chair comfortable? Yes, it is.",
          "Are you a musician? No, I'm not.",
          "Is the city crowded? Yes, it is.",
          "Are you awake? Yes, I am.",
          "Is the floor slippery? No, it isn't.",
          "Are you a chef? No, I'm not.",
          "Is the air fresh? Yes, it is.",
          "Are you smart? Yes, I am.",
          "Is the soup hot? Yes, it is.",
          "Are you an engineer? Yes, I am.",
          "Is the beach crowded? No, it isn't.",
          "Are you funny? Yes, I am.",
          "Is the test difficult? Yes, it is.",
          "Are you a dancer? No, I'm not.",
          "Is the night quiet? Yes, it is.",
          "Are you athletic? Yes, I am.",
          "Is the bag heavy? No, it isn't.",
          "Are you a lawyer? No, I'm not.",
          "Is the bread fresh? Yes, it is.",
          "Are you patient? Yes, I am.",
          "Is the wine expensive? Yes, it is.",
          "Are you a manager? Yes, I am.",
          "Is the pool clean? Yes, it is.",
          "Are you confident? Yes, I am.",
          "Is the sweater warm? Yes, it is.",
          "Are you a pilot? No, I'm not.",
          "Is the garden beautiful? Yes, it is.",
          "Are you a good cook? Yes, I am.",
          "Is the street noisy? No, it isn't.",
          "Are you a fast runner? Yes, I am.",
          "Is the mirror clean? Yes, it is.",
          "Are you a morning person? No, I'm not.",
          "Is the coffee strong? Yes, it is.",
          "Are you a good listener? Yes, I am.",
          "Is the restaurant expensive? No, it isn't.",
          "Are you left-handed? No, I'm not.",
          "Is the movie scary? Yes, it is.",
          "Are you a cat person? Yes, I am.",
          "Is the ice cream cold? Yes, it is.",
          "Are you a good driver? Yes, I am.",
          "Is the lecture boring? No, it isn't.",
          "Are you a night owl? Yes, I am.",
          "Is the pizza tasty? Yes, it is.",
          "Are you a fast reader? Yes, I am.",
          "Is the river deep? Yes, it is.",
          "Are you a good swimmer? No, I'm not.",
          "Is the jacket warm? Yes, it is.",
          "Are you a sports fan? Yes, I am.",
          "Is the sunset beautiful? Yes, it is.",
        ],
      },
    ],
    "data set 6": [
      {
        name: "Positive" as const,
        sentence: [
          "Are you hungry? No, but I'm thirsty.",
          "How are your parents? They're fine.",
          "Is Anna at home? No, she's at work.",
          "Where are my keys? On your desk.",
          "Where is Paul from? Is he American or British?",
          "It's very hot today. The temperature is 38 degrees.",
          "Are you a teacher? No, I'm a student.",
          "What color is your umbrella? Green.",
          "Where's your car? Is it in the car park?",
          "Are you tired? No, I'm fine.",
          "These shoes are nice. How much are they? Sixty pounds.",
          "Are you ready? Yes, let's go.",
          "How's your coffee? It's too hot.",
          "Where's the library? Down the street.",
          "Is Tom coming? No, he's busy.",
          "What time is it? Half past three.",
          "Do you like pizza? Yes, I love it.",
          "Where's my book? On the shelf.",
          "Is it raining? No, but it's cloudy.",
          "How old are you? I'm twenty-five.",
          "Are these yours? No, they're John's.",
          "What's for dinner? Chicken and rice.",
          "Is the store open? Yes, until 9 PM.",
          "How was the movie? It was great.",
          "Where's the bathroom? Upstairs, first door.",
          "Do you speak French? No, only English.",
          "Is this seat taken? No, it's free.",
          "How's your new job? It's challenging.",
          "Where are you from? I'm from Canada.",
          "Is the coffee good? Yes, it's excellent.",
          "What's your name? My name's Sarah.",
          "Are you cold? No, I'm comfortable.",
          "How much is this? It's ten dollars.",
          "Is the bus late? Yes, by 10 minutes.",
          "Where's the nearest ATM? Around the corner.",
          "Do you have a pen? Yes, here you go.",
          "Is this your dog? No, it's my neighbor's.",
          "How was your weekend? It was relaxing.",
          "Where's the meeting? In Room 302.",
          "Are you married? No, I'm single.",
          "What's the weather like? It's sunny and warm.",
          "Is this the right bus? Yes, for downtown.",
          "How's your family? They're all well.",
          "Where did you buy that? At the mall.",
          "Do you like spicy food? Yes, very much.",
          "Is the museum open? Yes, until 5 PM.",
          "How far is the airport? About 30 minutes away.",
          "Are you a vegetarian? No, I eat meat.",
          "What's your favorite color? I like blue.",
          "Is this seat free? Yes, you can sit here.",
          "How was your exam? It was difficult.",
          "Where's the nearest hotel? Two blocks north.",
          "Do you have change? Sorry, I don't.",
          "Is the water cold? No, it's quite warm.",
          "How long have you lived here? For five years.",
          "Where's the post office? Next to the bank.",
          "Are you allergic to nuts? Yes, I am.",
          "What's your job? I'm an engineer.",
          "Is the restaurant good? Yes, it's excellent.",
          "How tall are you? I'm six feet tall.",
          "Where's the nearest pharmacy? On Main Street.",
          "Do you play sports? Yes, I play tennis.",
          "Is this your first time here? No, I've been before.",
          "How's the food? It's delicious.",
          "Where's the exit? At the end of the hall.",
          "Are you feeling better? Yes, much better.",
          "What's your shoe size? I'm a size 8.",
          "Is the concert tonight? No, it's tomorrow.",
          "How was your trip? It was amazing.",
          "Where's the remote? On the coffee table.",
          "Do you have any siblings? Yes, two sisters.",
          "Is this yours? No, it's not mine.",
          "How do you spell that? S-M-I-T-H.",
          "Where's the nearest bus stop? Across the street.",
          "Are you free tonight? Sorry, I'm busy.",
          "What's your favorite food? I love pasta.",
          "Is the office closed? Yes, for lunch hour.",
          "How old is your cat? She's three years old.",
          "Where did you park? In the garage.",
          "Do you like coffee? No, I prefer tea.",
          "Is this the right way? No, it's the opposite direction.",
          "How was the concert? It was fantastic.",
          "Where's the restroom? Down the hall, left.",
          "Are you a student? Yes, at the university.",
          "What time does the shop close? At 6 PM.",
          "Is your brother older? No, he's younger.",
          "How long is the movie? About two hours.",
          "Where's the train station? Near the city center.",
          "Do you have a reservation? Yes, for two people.",
          "Is the Wi-Fi working? No, it's down.",
          "How much does it cost? Twenty euros.",
          "Where's the nearest supermarket? Three blocks away.",
          "Are you coming to the party? Yes, I'll be there.",
          "What's your favorite season? I love autumn.",
          "Is this seat taken? No, feel free to sit.",
          "How was your day? It was very busy.",
          "Where's the lost and found? At the information desk.",
          "Do you have any pets? Yes, a dog and a cat.",
          "Is the taxi here yet? No, it's on its way.",
          "How do you like your coffee? Black, no sugar.",
          "Where's the conference room? On the second floor.",
          "Are you feeling okay? No, I have a headache.",
          "What's your favorite book? To Kill a Mockingbird.",
          "Is the flight on time? Yes, it's on schedule.",
          "How long have you worked here? For three years.",
          "Where's the closest gas station? About a mile down the road.",
          "Do you speak Spanish? Yes, fluently.",
          "Is this the express train? No, it's the local.",
          "How was your vacation? It was very relaxing.",
          "Where's your office? In the city center.",
          "Are these shoes comfortable? Yes, very comfortable.",
        ],
      },
    ],

    "data set 7": [
      {
        name: "Positive" as const,
        sentence: [
          "Is it Ali outside?",
          "Are there no fish in this pond?",
          "Who's there on the roof?",
          "Is it hailing?",
          "Is Ali a cricket player?",
          "When is the train due?",
          "Why are many students absent today?",
          "Where are the players of your team?",
          "What's he to you?"
        ]
        
      },
    ],
  },
];

export default data;
