// data.ts
const data = [
  {
    name: "MySelf",
    noun: [
      {
        name: "Negative" as const,
        sentence: [
          "I'm not a student",
          "I'm not a teacher",
          "I'm not an engineer",
        ],
      },
      {
        name: "Positive" as const,
        sentence: [
          "I'm Aima",
          "I'm 6 years old",
          "I'm Pakistani",
          "I'm from Rawalpindi",
          "I'm a student",
          "I'm a carpenter",
          "I'm a baker",
          "I'm a boss",
          "I'm a brother",
          "I'm a captain",
          "I'm a cashier",
          "I'm a champion",
          "I'm a chef",
          "I'm a clerk",
          "I'm a clown",
          "I'm a coach",
          "I'm a cousin",
          "I'm a cowboy",
          "I'm a customer",
          "I'm a dancer",
          "I'm a daughter",
          "I'm a dentist",
          "I'm a designer",
          "I'm a detective",
          "I'm a doctor",
          "I'm a driver",
          "I'm a farmer",
          "I'm a father",
          "I'm a firefighter",
          "I'm a follower",
          "I'm a friend",
          "I'm a gardener",
          "I'm a general",
          "I'm a grandma",
          "I'm a grandpa",
          "I'm a historian",
          "I'm a human",
          "I'm a judge",
          "I'm a juggler",
          "I'm a king",
          "I'm a knight",
          "I'm a lawyer",
          "I'm a leader",
          "I'm a librarian",
          "I'm a lifeguard",
          "I'm a magician",
          "I'm a manager",
          "I'm a mechanic",
          "I'm a mime",
          "I'm a mother",
          "I'm a musician",
          "I'm a neighbor",
          "I'm a ninja",
          "I'm a nurse",
          "I'm a painter",
          "I'm a passenger",
          "I'm a photographer",
          "I'm a pilot",
          "I'm a pirate",
          "I'm a plumber",
          "I'm a poet",
          "I'm a police officer",
          "I'm a politician",
          "I'm a president",
          "I'm a prince",
          "I'm a princess",
          "I'm a programmer",
          "I'm a queen",
          "I'm a receptionist",
          "I'm a referee",
          "I'm a reporter",
          "I'm a sailor",
          "I'm a salesman",
          "I'm a samurai",
          "I'm a scientist",
          "I'm a sculptor",
          "I'm a secretary",
          "I'm a sister",
          "I'm a soldier",
          "I'm a son",
          "I'm a spy",
          "I'm a student",
          "I'm a superhero",
          "I'm a teacher",
          "I'm a vet",
          "I'm a villain",
          "I'm a waiter",
          "I'm a wizard",
          "I'm a writer",
          "I'm a zookeeper",
          "I'm an acrobat",
          "I'm an actor",
          "I'm an archaeologist",
          "I'm an architect",
          "I'm an artist",
          "I'm an astronaut",
          "I'm an athlete",
          "I'm an aunt",
          "I'm an electrician",
          "I'm an enemy",
          "I'm an engineer",
          "I'm an entrepreneur",
          "I'm an explorer",
          "I'm an inventor",
          "I'm an uncle",
        ],
      },
      {
        name: "Yes/No Questions" as const,
        sentence: ["Am I a student?", "Am I a teacher?", "Am I an engineer?"],
      },
    ],
    adjective: [
      {
        name: "Negative" as const,
        sentence: ["I'm not happy", "I'm not tired", "I'm not busy"],
      },
      {
        name: "Positive" as const,
        sentence: [
          "I'm active",
          "I'm angry",
          "I'm anxious",
          "I'm available",
          "I'm awake",
          "I'm big",
          "I'm bored",
          "I'm brave",
          "I'm busy",
          "I'm calm",
          "I'm careful",
          "I'm careless",
          "I'm clean",
          "I'm cold",
          "I'm confident",
          "I'm confused",
          "I'm content",
          "I'm cool",
          "I'm creative",
          "I'm curious",
          "I'm determined",
          "I'm dirty",
          "I'm disorganized",
          "I'm dry",
          "I'm early",
          "I'm energetic",
          "I'm excited",
          "I'm experienced",
          "I'm famous",
          "I'm fast",
          "I'm free",
          "I'm friendly",
          "I'm frustrated",
          "I'm generous",
          "I'm healthy",
          "I'm honest",
          "I'm hot",
          "I'm hungry",
          "I'm impatient",
          "I'm irresponsible",
          "I'm kind",
          "I'm late",
          "I'm lazy",
          "I'm loud",
          "I'm lucky",
          "I'm mean",
          "I'm messy",
          "I'm neat",
          "I'm nervous",
          "I'm new",
          "I'm occupied",
          "I'm old",
          "I'm organized",
          "I'm patient",
          "I'm playful",
          "I'm polite",
          "I'm poor",
          "I'm popular",
          "I'm proud",
          "I'm punctual",
          "I'm quiet",
          "I'm ready",
          "I'm relaxed",
          "I'm responsible",
          "I'm rich",
          "I'm rude",
          "I'm sad",
          "I'm scared",
          "I'm selfish",
          "I'm serious",
          "I'm short",
          "I'm shy",
          "I'm sick",
          "I'm silly",
          "I'm sleepy",
          "I'm slow",
          "I'm small",
          "I'm smart",
          "I'm sneaky",
          "I'm strong",
          "I'm successful",
          "I'm surprised",
          "I'm tall",
          "I'm tardy",
          "I'm thirsty",
          "I'm thoughtful",
          "I'm tired",
          "I'm unfriendly",
          "I'm unknown",
          "I'm unlucky",
          "I'm unpopular",
          "I'm unprepared",
          "I'm unsuccessful",
          "I'm warm",
          "I'm weak",
          "I'm wet",
          "I'm young",
        ],
      },
      {
        name: "Yes/No Questions" as const,
        sentence: ["Am I happy?", "Am I tired?", "Am I busy?"],
      },
    ],
    preposition: [
      {
        name: "Negative" as const,
        sentence: [
          "I'm not at home",
          "I'm not in the office",
          "I'm not on vacation",
        ],
      },
      {
        name: "Positive" as const,
        sentence: [
          "I'm at home",
          "I'm on time",
          "I'm in the office",
          "I'm under the table",
          "I'm with friends",
          "I'm from New York",
          "I'm into yoga",
          "I'm on the team",
          "I'm over the hill",
          "I'm off the list",
          "I'm against the idea",
          "I'm for the plan",
          "I'm between jobs",
          "I'm out of town",
          "I'm above the law",
          "I'm in love",
          "I'm out of breath",
          "I'm among the best",
          "I'm without a phone",
          "I'm under pressure",
          "I'm against the wall",
          "I'm in charge",
          "I'm above suspicion",
          "I'm outside the box",
          "I'm behind the wheel",
          "I'm near the finish line",
          "I'm below average",
          "I'm around the corner",
          "I'm on my way",
          "I'm beneath the surface",
          "I'm in trouble",
          "I'm off duty",
          "I'm at risk",
          "I'm under control",
          "I'm behind schedule",
          "I'm in the spotlight",
          "I'm at peace",
          "I'm within reach",
          "I'm out of control",
          "I'm in style",
          "I'm above average",
          "I'm off balance",
          "I'm on a break",
          "I'm at the top",
          "I'm in danger",
          "I'm out of luck",
          "I'm between friends",
          "I'm over the moon",
          "I'm in a hurry",
          "I'm on vacation",
        ],
      },
      {
        name: "Yes/No Questions" as const,
        sentence: ["Am I at home?", "Am I in the office?", "Am I on vacation?"],
      },
    ],
    objective: [
      {
        name: "Negative" as const,
        sentence: [
          "I'm not at home",
          "I'm not in the office",
          "I'm not on vacation",
        ],
      },
      {
        name: "Positive" as const,
        sentence: [
          "My toy is with me",
          "The book is for me",
          "The cat is near me",
          "My friend is with me",
          "The cake is for me",
          "My mom is beside me",
          "The ball is with me",
          "My dog is behind me",
          "The star is above me",
          "The chocolate is for me",
          "The sun is shining on me",
          "The rainbow is over me",
          "The wind is blowing on me",
          "The music is playing for me",
          "The rain is falling on me",
          "My sister is with me",
          "The butterfly is near me",
          "The snow is covering me",
          "The flower is for me",
          "The story is about me",
          "The tree is shading me",
          "The bed is waiting for me",
          "My pillow is under me",
          "The sand is under me",
          "My teacher is helping me",
          "The bird is watching me",
          "The ocean is calling me",
          "The mountain is waiting for me",
          "The car is ready for me",
          "The bike is waiting for me",
          "The ice cream is melting for me",
          "My shoes are with me",
          "The cookies are for me",
          "The clouds are above me",
          "The stars are twinkling for me",
          "My crayons are with me",
          "The paints are waiting for me",
          "The puzzles are ready for me",
          "The games are waiting for me",
          "The toys are around me",
          "The bubbles are floating near me",
          "The fish are swimming for me",
          "The ducks are quacking at me",
          "The dogs are barking at me",
          "The cats are purring for me",
          "My friends are with me",
          "The family is around me",
          "The party is for me",
          "The balloons are for me",
          "The presents are for me",
          "The songs are for me",
          "The fireworks are for me",
          "The stars are for me",
          "My dreams are with me",
          "The rainbow is for me",
          "The clouds are shading me",
          "The rain is wetting me",
          "The sun is warming me",
          "The grass is under me",
          "The wind is pushing me",
          "The music is moving me",
          "The waves are splashing me",
          "The river is calling me",
          "The forest is whispering to me",
          "The jungle is full of surprises for me",
          "The snowflakes are falling on me",
          "The leaves are falling around me",
          "The garden is waiting for me",
          "The playground is ready for me",
          "The slide is calling me",
          "The swing is waiting for me",
          "The seesaw is for me",
          "The sandcastle is for me to build",
          "The castle is for me to explore",
          "The adventure is for me",
          "The journey is waiting for me",
          "The ship is ready for me",
          "The airplane is ready for me",
          "The journey is for me",
          "The stars are guiding me",
          "The moon is watching over me",
          "The sun is setting for me",
          "The morning is for me",
          "The night is for me to rest",
          "The stars are shining on me",
          "The dream is waiting for me",
          "The world is for me to explore",
          "The path is for me to follow",
          "The road is for me to travel",
          "The treasure is waiting for me",
          "The goal is for me",
          "The victory is for me",
          "The journey is exciting for me",
          "The adventure is thrilling for me",
          "The magic is with me",
          "The fun is with me",
          "The surprise is for me",
          "The wonder is for me to discover",
          "The love is all around me",
          "The happiness is with me",
        ],
      },
      {
        name: "Yes/No Questions" as const,
        sentence: ["Am I at home?", "Am I in the office?", "Am I on vacation?"],
      },
    ],
    possesive: [
      {
        name: "Negative" as const,
        sentence: [
          "I'm not at home",
          "I'm not in the office",
          "I'm not on vacation",
        ],
      },
      {
        name: "Positive" as const,
        sentence: [
          "My activity is cool",
          "My adventure is thrilling",
          "My art is beautiful",
          "My art is colorful",
          "My bikes are fast",
          "My book is cool",
          "My book is exciting",
          "My book is interesting",
          "My books are colorful",
          "My camp is awesome",
          "My class is cheerful",
          "My class is great",
          "My class is happy",
          "My class is lively",
          "My classroom is neat",
          "My clothes are comfy",
          "My clothes are pretty",
          "My day is bright",
          "My day is fun",
          "My day is special",
          "My drawing is nice",
          "My drawings are bright",
          "My events are fun",
          "My family is awesome",
          "My family is caring",
          "My family is kind",
          "My family is loving",
          "My family is supportive",
          "My field trip is fun",
          "My friends are caring",
          "My friends are funny",
          "My friends are helpful",
          "My friends are kind",
          "My friends are silly",
          "My game is exciting",
          "My game is fun",
          "My games are fair",
          "My games are fun",
          "My garden is green",
          "My garden is pretty",
          "My goals are clear",
          "My holiday is amazing",
          "My holiday is fun",
          "My homework is easy",
          "My house is cozy",
          "My jokes are funny",
          "My lunch is good",
          "My lunch is yummy",
          "My movie is exciting",
          "My movie is fun",
          "My music is cheerful",
          "My music is happy",
          "My music is lively",
          "My neighborhood is safe",
          "My park is beautiful",
          "My park is lively",
          "My park is lovely",
          "My party is awesome",
          "My party is lively",
          "My pet is cute",
          "My pet is playful",
          "My pets are cute",
          "My pets are friendly",
          "My pets are playful",
          "My pets are sweet",
          "My picnic is great",
          "My plans are fun",
          "My playground is big",
          "My playground is fun",
          "My playground is nice",
          "My project is interesting",
          "My room is big",
          "My school is bright",
          "My school is cool",
          "My science is cool",
          "My shoes are comfy",
          "My snack is tasty",
          "My snacks are tasty",
          "My stories are fun",
          "My story is cool",
          "My story is fun",
          "My teacher is funny",
          "My teacher is nice",
          "My teachers are nice",
          "My team is exciting",
          "My team is friendly",
          "My team is happy",
          "My team is helpful",
          "My team is smart",
          "My team is strong",
          "My toys are colorful",
          "My toys are exciting",
          "My toys are fun",
          "My trip is cool",
          "My trip is exciting",
          "My weekend is exciting",
          "My weekend is fun",
        ],
      },
      {
        name: "Yes/No Questions" as const,
        sentence: ["Am I at home?", "Am I in the office?", "Am I on vacation?"],
      },
    ],
  },
];

export default data;
