// data.ts
export const myselfData = [
  {
    name: "MySelf",
    noun: [
      {
        name: "Negative" as const,
        sentence: [
          "I'm not a student",
          "I'm not a teacher",
          "I'm not an engineer",
        ],
      },
      {
        name: "Positive" as const,
        sentence: [
          "I'm Aima",
          "I'm 6 years old",
          "I'm Pakistani",
          "I'm from Rawalpindi",
          "I'm a student",
          "I'm a carpenter",
          "I'm a baker",
          "I'm a boss",
          "I'm a brother",
          "I'm a captain",
          "I'm a cashier",
          "I'm a champion",
          "I'm a chef",
          "I'm a clerk",
          "I'm a clown",
          "I'm a coach",
          "I'm a cousin",
          "I'm a cowboy",
          "I'm a customer",
          "I'm a dancer",
          "I'm a daughter",
          "I'm a dentist",
          "I'm a designer",
          "I'm a detective",
          "I'm a doctor",
          "I'm a driver",
          "I'm a farmer",
          "I'm a father",
          "I'm a firefighter",
          "I'm a follower",
          "I'm a friend",
          "I'm a gardener",
          "I'm a general",
          "I'm a grandma",
          "I'm a grandpa",
          "I'm a historian",
          "I'm a human",
          "I'm a judge",
          "I'm a juggler",
          "I'm a king",
          "I'm a knight",
          "I'm a lawyer",
          "I'm a leader",
          "I'm a librarian",
          "I'm a lifeguard",
          "I'm a magician",
          "I'm a manager",
          "I'm a mechanic",
          "I'm a mime",
          "I'm a mother",
          "I'm a musician",
          "I'm a neighbor",
          "I'm a ninja",
          "I'm a nurse",
          "I'm a painter",
          "I'm a passenger",
          "I'm a photographer",
          "I'm a pilot",
          "I'm a pirate",
          "I'm a plumber",
          "I'm a poet",
          "I'm a police officer",
          "I'm a politician",
          "I'm a president",
          "I'm a prince",
          "I'm a princess",
          "I'm a programmer",
          "I'm a queen",
          "I'm a receptionist",
          "I'm a referee",
          "I'm a reporter",
          "I'm a sailor",
          "I'm a salesman",
          "I'm a samurai",
          "I'm a scientist",
          "I'm a sculptor",
          "I'm a secretary",
          "I'm a sister",
          "I'm a soldier",
          "I'm a son",
          "I'm a spy",
          "I'm a student",
          "I'm a superhero",
          "I'm a teacher",
          "I'm a vet",
          "I'm a villain",
          "I'm a waiter",
          "I'm a wizard",
          "I'm a writer",
          "I'm a zookeeper",
          "I'm an acrobat",
          "I'm an actor",
          "I'm an archaeologist",
          "I'm an architect",
          "I'm an artist",
          "I'm an astronaut",
          "I'm an athlete",
          "I'm an aunt",
          "I'm an electrician",
          "I'm an enemy",
          "I'm an engineer",
          "I'm an entrepreneur",
          "I'm an explorer",
          "I'm an inventor",
          "I'm an uncle",
        ],
      },
      {
        name: "Yes/No Questions" as const,
        sentence: ["Am I a student?", "Am I a teacher?", "Am I an engineer?"],
      },
    ],
    adjective: [
      {
        name: "Negative" as const,
        sentence: ["I'm not happy", "I'm not tired", "I'm not busy"],
      },
      {
        name: "Positive" as const,
        sentence: [
          "I'm active",
          "I'm angry",
          "I'm anxious",
          "I'm available",
          "I'm awake",
          "I'm big",
          "I'm bored",
          "I'm brave",
          "I'm busy",
          "I'm calm",
          "I'm careful",
          "I'm careless",
          "I'm clean",
          "I'm cold",
          "I'm confident",
          "I'm confused",
          "I'm content",
          "I'm cool",
          "I'm creative",
          "I'm curious",
          "I'm determined",
          "I'm dirty",
          "I'm disorganized",
          "I'm dry",
          "I'm early",
          "I'm energetic",
          "I'm excited",
          "I'm experienced",
          "I'm famous",
          "I'm fast",
          "I'm free",
          "I'm friendly",
          "I'm frustrated",
          "I'm generous",
          "I'm healthy",
          "I'm honest",
          "I'm hot",
          "I'm hungry",
          "I'm impatient",
          "I'm irresponsible",
          "I'm kind",
          "I'm late",
          "I'm lazy",
          "I'm loud",
          "I'm lucky",
          "I'm mean",
          "I'm messy",
          "I'm neat",
          "I'm nervous",
          "I'm new",
          "I'm occupied",
          "I'm old",
          "I'm organized",
          "I'm patient",
          "I'm playful",
          "I'm polite",
          "I'm poor",
          "I'm popular",
          "I'm proud",
          "I'm punctual",
          "I'm quiet",
          "I'm ready",
          "I'm relaxed",
          "I'm responsible",
          "I'm rich",
          "I'm rude",
          "I'm sad",
          "I'm scared",
          "I'm selfish",
          "I'm serious",
          "I'm short",
          "I'm shy",
          "I'm sick",
          "I'm silly",
          "I'm sleepy",
          "I'm slow",
          "I'm small",
          "I'm smart",
          "I'm sneaky",
          "I'm strong",
          "I'm successful",
          "I'm surprised",
          "I'm tall",
          "I'm tardy",
          "I'm thirsty",
          "I'm thoughtful",
          "I'm tired",
          "I'm unfriendly",
          "I'm unknown",
          "I'm unlucky",
          "I'm unpopular",
          "I'm unprepared",
          "I'm unsuccessful",
          "I'm warm",
          "I'm weak",
          "I'm wet",
          "I'm young",
        ],
      },
      {
        name: "Yes/No Questions" as const,
        sentence: ["Am I happy?", "Am I tired?", "Am I busy?"],
      },
    ],
    preposition: [
      {
        name: "Negative" as const,
        sentence: [
          "I'm not at home",
          "I'm not in the office",
          "I'm not on vacation",
        ],
      },
      {
        name: "Positive" as const,
        sentence: [
          "I'm at home",
          "I'm on time",
          "I'm in the office",
          "I'm under the table",
          "I'm with friends",
          "I'm from New York",
          "I'm into yoga",
          "I'm on the team",
          "I'm over the hill",
          "I'm off the list",
          "I'm against the idea",
          "I'm for the plan",
          "I'm between jobs",
          "I'm out of town",
          "I'm above the law",
          "I'm in love",
          "I'm out of breath",
          "I'm among the best",
          "I'm without a phone",
          "I'm under pressure",
          "I'm against the wall",
          "I'm in charge",
          "I'm above suspicion",
          "I'm outside the box",
          "I'm behind the wheel",
          "I'm near the finish line",
          "I'm below average",
          "I'm around the corner",
          "I'm on my way",
          "I'm beneath the surface",
          "I'm in trouble",
          "I'm off duty",
          "I'm at risk",
          "I'm under control",
          "I'm behind schedule",
          "I'm in the spotlight",
          "I'm at peace",
          "I'm within reach",
          "I'm out of control",
          "I'm in style",
          "I'm above average",
          "I'm off balance",
          "I'm on a break",
          "I'm at the top",
          "I'm in danger",
          "I'm out of luck",
          "I'm between friends",
          "I'm over the moon",
          "I'm in a hurry",
          "I'm on vacation",
        ],
      },
      {
        name: "Yes/No Questions" as const,
        sentence: ["Am I at home?", "Am I in the office?", "Am I on vacation?"],
      },
    ],
    objective: [
      {
        name: "Negative" as const,
        sentence: [
          "I'm not at home",
          "I'm not in the office",
          "I'm not on vacation",
        ],
      },
      {
        name: "Positive" as const,
        sentence: [
          "My toy is with me",
          "The book is for me",
          "The cat is near me",
          "My friend is with me",
          "The cake is for me",
          "My mom is beside me",
          "The ball is with me",
          "My dog is behind me",
          "The star is above me",
          "The chocolate is for me",
          "The sun is shining on me",
          "The rainbow is over me",
          "The wind is blowing on me",
          "The music is playing for me",
          "The rain is falling on me",
          "My sister is with me",
          "The butterfly is near me",
          "The snow is covering me",
          "The flower is for me",
          "The story is about me",
          "The tree is shading me",
          "The bed is waiting for me",
          "My pillow is under me",
          "The sand is under me",
          "My teacher is helping me",
          "The bird is watching me",
          "The ocean is calling me",
          "The mountain is waiting for me",
          "The car is ready for me",
          "The bike is waiting for me",
          "The ice cream is melting for me",
          "My shoes are with me",
          "The cookies are for me",
          "The clouds are above me",
          "The stars are twinkling for me",
          "My crayons are with me",
          "The paints are waiting for me",
          "The puzzles are ready for me",
          "The games are waiting for me",
          "The toys are around me",
          "The bubbles are floating near me",
          "The fish are swimming for me",
          "The ducks are quacking at me",
          "The dogs are barking at me",
          "The cats are purring for me",
          "My friends are with me",
          "The family is around me",
          "The party is for me",
          "The balloons are for me",
          "The presents are for me",
          "The songs are for me",
          "The fireworks are for me",
          "The stars are for me",
          "My dreams are with me",
          "The rainbow is for me",
          "The clouds are shading me",
          "The rain is wetting me",
          "The sun is warming me",
          "The grass is under me",
          "The wind is pushing me",
          "The music is moving me",
          "The waves are splashing me",
          "The river is calling me",
          "The forest is whispering to me",
          "The jungle is full of surprises for me",
          "The snowflakes are falling on me",
          "The leaves are falling around me",
          "The garden is waiting for me",
          "The playground is ready for me",
          "The slide is calling me",
          "The swing is waiting for me",
          "The seesaw is for me",
          "The sandcastle is for me to build",
          "The castle is for me to explore",
          "The adventure is for me",
          "The journey is waiting for me",
          "The ship is ready for me",
          "The airplane is ready for me",
          "The journey is for me",
          "The stars are guiding me",
          "The moon is watching over me",
          "The sun is setting for me",
          "The morning is for me",
          "The night is for me to rest",
          "The stars are shining on me",
          "The dream is waiting for me",
          "The world is for me to explore",
          "The path is for me to follow",
          "The road is for me to travel",
          "The treasure is waiting for me",
          "The goal is for me",
          "The victory is for me",
          "The journey is exciting for me",
          "The adventure is thrilling for me",
          "The magic is with me",
          "The fun is with me",
          "The surprise is for me",
          "The wonder is for me to discover",
          "The love is all around me",
          "The happiness is with me",
        ],
      },
      {
        name: "Yes/No Questions" as const,
        sentence: ["Am I at home?", "Am I in the office?", "Am I on vacation?"],
      },
    ],
    possesive: [
      {
        name: "Negative" as const,
        sentence: [
          "I'm not at home",
          "I'm not in the office",
          "I'm not on vacation",
        ],
      },
      {
        name: "Positive" as const,
        sentence: [
          "My activity is cool",
          "My adventure is thrilling",
          "My art is beautiful",
          "My art is colorful",
          "My bikes are fast",
          "My book is cool",
          "My book is exciting",
          "My book is interesting",
          "My books are colorful",
          "My camp is awesome",
          "My class is cheerful",
          "My class is great",
          "My class is happy",
          "My class is lively",
          "My classroom is neat",
          "My clothes are comfy",
          "My clothes are pretty",
          "My day is bright",
          "My day is fun",
          "My day is special",
          "My drawing is nice",
          "My drawings are bright",
          "My events are fun",
          "My family is awesome",
          "My family is caring",
          "My family is kind",
          "My family is loving",
          "My family is supportive",
          "My field trip is fun",
          "My friends are caring",
          "My friends are funny",
          "My friends are helpful",
          "My friends are kind",
          "My friends are silly",
          "My game is exciting",
          "My game is fun",
          "My games are fair",
          "My games are fun",
          "My garden is green",
          "My garden is pretty",
          "My goals are clear",
          "My holiday is amazing",
          "My holiday is fun",
          "My homework is easy",
          "My house is cozy",
          "My jokes are funny",
          "My lunch is good",
          "My lunch is yummy",
          "My movie is exciting",
          "My movie is fun",
          "My music is cheerful",
          "My music is happy",
          "My music is lively",
          "My neighborhood is safe",
          "My park is beautiful",
          "My park is lively",
          "My park is lovely",
          "My party is awesome",
          "My party is lively",
          "My pet is cute",
          "My pet is playful",
          "My pets are cute",
          "My pets are friendly",
          "My pets are playful",
          "My pets are sweet",
          "My picnic is great",
          "My plans are fun",
          "My playground is big",
          "My playground is fun",
          "My playground is nice",
          "My project is interesting",
          "My room is big",
          "My school is bright",
          "My school is cool",
          "My science is cool",
          "My shoes are comfy",
          "My snack is tasty",
          "My snacks are tasty",
          "My stories are fun",
          "My story is cool",
          "My story is fun",
          "My teacher is funny",
          "My teacher is nice",
          "My teachers are nice",
          "My team is exciting",
          "My team is friendly",
          "My team is happy",
          "My team is helpful",
          "My team is smart",
          "My team is strong",
          "My toys are colorful",
          "My toys are exciting",
          "My toys are fun",
          "My trip is cool",
          "My trip is exciting",
          "My weekend is exciting",
          "My weekend is fun",
        ],
      },
      {
        name: "Yes/No Questions" as const,
        sentence: ["Am I at home?", "Am I in the office?", "Am I on vacation?"],
      },
    ],
  },
];
export const ourselvesData = [
  {
    name: "Ourselves",
    noun: [
      {
        name: "Negative" as const,
        sentence: [
          "We're not kids.",
          "We're not friends.",
          "We're not students.",
          "We're not players.",
          "We're not helpers.",
          "We're not artists.",
          "We're not singers.",
          "We're not swimmers.",
          "We're not runners.",
          "We're not dreamers.",
          "We're not builders.",
          "We're not thinkers.",
          "We're not dancers.",
          "We're not team members.",
          "We're not cooks.",
          "We're not gardeners.",
          "We're not travelers.",
          "We're not storytellers.",
          "We're not animal lovers.",
          "We're not climbers.",
          "We're not painters.",
          "We're not jokers.",
          "We're not scientists.",
          "We're not explorers.",
          "We're not stargazers.",
          "We're not bike riders.",
          "We're not bug catchers.",
          "We're not campers.",
          "We're not snow players.",
          "We're not tree climbers.",
          "We're not fort builders.",
          "We're not puzzle solvers.",
          "We're not cookie bakers.",
          "We're not toy makers.",
          "We're not nature lovers.",
          "We're not game players.",
          "We're not pet owners.",
          "We're not sandcastle builders.",
          "We're not beach combers.",
          "We're not kite flyers.",
          "We're not bubble blowers.",
          "We're not dinosaur fans.",
          "We're not lego builders.",
          "We're not skaters.",
          "We're not flower pickers.",
          "We're not bird watchers.",
          "We're not rock collectors.",
          "We're not soccer players.",
          "We're not balloon poppers.",
          "We're not ice cream eaters.",
          "We're not picture drawers.",
          "We're not joke tellers.",
          "We're not hide-and-seekers.",
          "We're not arm wrestlers.",
          "We're not cloud watchers.",
          "We're not mud puddle jumpers.",
          "We're not train riders.",
          "We're not blanket fort makers.",
          "We're not finger painters.",
        ],
      },
      {
        name: "Positive" as const,
        sentence: [
          "We're kids.",
          "We're friends.",
          "We're students.",
          "We're players.",
          "We're helpers.",
          "We're artists.",
          "We're singers.",
          "We're swimmers.",
          "We're runners.",
          "We're dreamers.",
          "We're builders.",
          "We're thinkers.",
          "We're dancers.",
          "We're team members.",
          "We're cooks.",
          "We're gardeners.",
          "We're travelers.",
          "We're storytellers.",
          "We're animal lovers.",
          "We're climbers.",
          "We're painters.",
          "We're jokers.",
          "We're scientists.",
          "We're explorers.",
          "We're stargazers.",
          "We're bike riders.",
          "We're bug catchers.",
          "We're campers.",
          "We're snow players.",
          "We're tree climbers.",
          "We're fort builders.",
          "We're puzzle solvers.",
          "We're cookie bakers.",
          "We're toy makers.",
          "We're nature lovers.",
          "We're game players.",
          "We're pet owners.",
          "We're sandcastle builders.",
          "We're beach combers.",
          "We're kite flyers.",
          "We're bubble blowers.",
          "We're dinosaur fans.",
          "We're lego builders.",
          "We're skaters.",
          "We're flower pickers.",
          "We're bird watchers.",
          "We're rock collectors.",
          "We're soccer players.",
          "We're balloon poppers.",
          "We're ice cream eaters.",
          "We're picture drawers.",
          "We're joke tellers.",
          "We're hide-and-seekers.",
          "We're arm wrestlers.",
          "We're cloud watchers.",
          "We're mud puddle jumpers.",
          "We're train riders.",
          "We're blanket fort makers.",
          "We're finger painters.",
        ],
      },
      {
        name: "Yes/No Questions" as const,
        sentence: [
          "Are we kids?",
          "Are we friends?",
          "Are we students?",
          "Are we players?",
          "Are we helpers?",
          "Are we artists?",
          "Are we singers?",
          "Are we swimmers?",
          "Are we runners?",
          "Are we dreamers?",
          "Are we builders?",
          "Are we thinkers?",
          "Are we dancers?",
          "Are we team members?",
          "Are we cooks?",
          "Are we gardeners?",
          "Are we travelers?",
          "Are we storytellers?",
          "Are we animal lovers?",
          "Are we climbers?",
          "Are we painters?",
          "Are we jokers?",
          "Are we scientists?",
          "Are we explorers?",
          "Are we stargazers?",
          "Are we bike riders?",
          "Are we bug catchers?",
          "Are we campers?",
          "Are we snow players?",
          "Are we tree climbers?",
          "Are we fort builders?",
          "Are we puzzle solvers?",
          "Are we cookie bakers?",
          "Are we toy makers?",
          "Are we nature lovers?",
          "Are we game players?",
          "Are we pet owners?",
          "Are we sandcastle builders?",
          "Are we beach combers?",
          "Are we kite flyers?",
          "Are we bubble blowers?",
          "Are we dinosaur fans?",
          "Are we lego builders?",
          "Are we skaters?",
          "Are we flower pickers?",
          "Are we bird watchers?",
          "Are we rock collectors?",
          "Are we soccer players?",
          "Are we balloon poppers?",
          "Are we ice cream eaters?",
          "Are we picture drawers?",
          "Are we joke tellers?",
          "Are we hide-and-seekers?",
          "Are we arm wrestlers?",
          "Are we cloud watchers?",
          "Are we mud puddle jumpers?",
          "Are we train riders?",
          "Are we blanket fort makers?",
          "Are we finger painters?",
        ],
      },
    ],
    adjective: [
      {
        name: "Negative" as const,
        sentence: [
          "We're not excited!",
          "We're not hungry.",
          "We're not silly.",
          "We're not smart.",
          "We're not brave.",
          "We're not happy.",
          "We're not curious.",
          "We're not friendly.",
          "We're not helpful.",
          "We're not creative.",
          "We're not energetic.",
          "We're not kind.",
          "We're not funny.",
          "We're not loud.",
          "We're not quiet.",
          "We're not playful.",
          "We're not sleepy.",
          "We're not busy.",
          "We're not calm.",
          "We're not noisy.",
          "We're not careful.",
          "We're not messy.",
          "We're not tidy.",
          "We're not clever.",
          "We're not gentle.",
          "We're not strong.",
          "We're not fast.",
          "We're not slow.",
          "We're not patient.",
          "We're not impatient.",
          "We're not colorful.",
          "We're not giggly.",
          "We're not thoughtful.",
          "We're not adventurous.",
          "We're not polite.",
          "We're not shy.",
          "We're not outgoing.",
          "We're not tall.",
          "We're not short.",
          "We're not active.",
          "We're not relaxed.",
          "We're not musical.",
          "We're not artistic.",
          "We're not sporty.",
          "We're not cheerful.",
          "We're not grumpy.",
          "We're not excited.",
          "We're not bored.",
          "We're not proud.",
          "We're not humble.",
          "We're not fuzzy.",
          "We're not smooth.",
          "We're not bouncy.",
          "We're not wiggly.",
          "We're not jumpy.",
          "We're not sparkly.",
          "We're not shiny.",
          "We're not bubbly.",
          "We're not squiggly.",
          "We're not squishy.",
          "We're not soft.",
          "We're not hard.",
          "We're not fluffy.",
          "We're not slimy.",
          "We're not sticky.",
          "We're not wet.",
          "We're not dry.",
          "We're not hot.",
          "We're not cold.",
          "We're not warm.",
          "We're not cool.",
          "We're not bumpy.",
          "We're not smooth.",
          "We're not rough.",
          "We're not cuddly.",
          "We're not ticklish.",
          "We're not wibbly-wobbly.",
          "We're not zigzaggy.",
          "We're not swirly.",
          "We're not stretchy.",
          "We're not bouncy.",
          "We're not wobbly.",
          "We're not jiggly.",
          "We're not floppy.",
          "We're not snuggly.",
          "We're not cozy.",
          "We're not jolly.",
          "We're not silly-willy.",
          "We're not topsy-turvy.",
          "We're not upside-down.",
          "We're not right-side-up.",
          "We're not inside-out.",
          "We're not outside-in.",
          "We're not front-to-back.",
          "We're not back-to-front.",
          "We're not tippy-toe.",
          "We're not zig-zag.",
          "We're not criss-cross.",
          "We're not super-duper!"
        ]
        ,
      },
      {
        name: "Positive" as const,
        sentence: [
          "We're excited!",
          "We're hungry.",
          "We're silly.",
          "We're smart.",
          "We're brave.",
          "We're happy.",
          "We're curious.",
          "We're friendly.",
          "We're helpful.",
          "We're creative.",
          "We're energetic.",
          "We're kind.",
          "We're funny.",
          "We're loud.",
          "We're quiet.",
          "We're playful.",
          "We're sleepy.",
          "We're busy.",
          "We're calm.",
          "We're noisy.",
          "We're careful.",
          "We're messy.",
          "We're tidy.",
          "We're clever.",
          "We're gentle.",
          "We're strong.",
          "We're fast.",
          "We're slow.",
          "We're patient.",
          "We're impatient.",
          "We're colorful.",
          "We're giggly.",
          "We're thoughtful.",
          "We're adventurous.",
          "We're polite.",
          "We're shy.",
          "We're outgoing.",
          "We're tall.",
          "We're short.",
          "We're active.",
          "We're relaxed.",
          "We're musical.",
          "We're artistic.",
          "We're sporty.",
          "We're cheerful.",
          "We're grumpy.",
          "We're excited.",
          "We're bored.",
          "We're proud.",
          "We're humble.",
          "We're fuzzy.",
          "We're smooth.",
          "We're bouncy.",
          "We're wiggly.",
          "We're jumpy.",
          "We're sparkly.",
          "We're shiny.",
          "We're bubbly.",
          "We're squiggly.",
          "We're squishy.",
          "We're soft.",
          "We're hard.",
          "We're fluffy.",
          "We're slimy.",
          "We're sticky.",
          "We're wet.",
          "We're dry.",
          "We're hot.",
          "We're cold.",
          "We're warm.",
          "We're cool.",
          "We're bumpy.",
          "We're smooth.",
          "We're rough.",
          "We're cuddly.",
          "We're ticklish.",
          "We're wibbly-wobbly.",
          "We're zigzaggy.",
          "We're swirly.",
          "We're stretchy.",
          "We're bouncy.",
          "We're wobbly.",
          "We're jiggly.",
          "We're floppy.",
          "We're snuggly.",
          "We're cozy.",
          "We're jolly.",
          "We're silly-willy.",
          "We're topsy-turvy.",
          "We're upside-down.",
          "We're right-side-up.",
          "We're inside-out.",
          "We're outside-in.",
          "We're front-to-back.",
          "We're back-to-front.",
          "We're tippy-toe.",
          "We're zig-zag.",
          "We're criss-cross.",
          "We're super-duper!",
        ],
      },
      {
        name: "Yes/No Questions" as const,
        sentence: [
          "Are we excited?",
          "Are we hungry?",
          "Are we silly?",
          "Are we smart?",
          "Are we brave?",
          "Are we happy?",
          "Are we curious?",
          "Are we friendly?",
          "Are we helpful?",
          "Are we creative?",
          "Are we energetic?",
          "Are we kind?",
          "Are we funny?",
          "Are we loud?",
          "Are we quiet?",
          "Are we playful?",
          "Are we sleepy?",
          "Are we busy?",
          "Are we calm?",
          "Are we noisy?",
          "Are we careful?",
          "Are we messy?",
          "Are we tidy?",
          "Are we clever?",
          "Are we gentle?",
          "Are we strong?",
          "Are we fast?",
          "Are we slow?",
          "Are we patient?",
          "Are we impatient?",
          "Are we colorful?",
          "Are we giggly?",
          "Are we thoughtful?",
          "Are we adventurous?",
          "Are we polite?",
          "Are we shy?",
          "Are we outgoing?",
          "Are we tall?",
          "Are we short?",
          "Are we active?",
          "Are we relaxed?",
          "Are we musical?",
          "Are we artistic?",
          "Are we sporty?",
          "Are we cheerful?",
          "Are we grumpy?",
          "Are we excited?",
          "Are we bored?",
          "Are we proud?",
          "Are we humble?",
          "Are we fuzzy?",
          "Are we smooth?",
          "Are we bouncy?",
          "Are we wiggly?",
          "Are we jumpy?",
          "Are we sparkly?",
          "Are we shiny?",
          "Are we bubbly?",
          "Are we squiggly?",
          "Are we squishy?",
          "Are we soft?",
          "Are we hard?",
          "Are we fluffy?",
          "Are we slimy?",
          "Are we sticky?",
          "Are we wet?",
          "Are we dry?",
          "Are we hot?",
          "Are we cold?",
          "Are we warm?",
          "Are we cool?",
          "Are we bumpy?",
          "Are we smooth?",
          "Are we rough?",
          "Are we cuddly?",
          "Are we ticklish?",
          "Are we wibbly-wobbly?",
          "Are we zigzaggy?",
          "Are we swirly?",
          "Are we stretchy?",
          "Are we bouncy?",
          "Are we wobbly?",
          "Are we jiggly?",
          "Are we floppy?",
          "Are we snuggly?",
          "Are we cozy?",
          "Are we jolly?",
          "Are we silly-willy?",
          "Are we topsy-turvy?",
          "Are we upside-down?",
          "Are we right-side-up?",
          "Are we inside-out?",
          "Are we outside-in?",
          "Are we front-to-back?",
          "Are we back-to-front?",
          "Are we tippy-toe?",
          "Are we zig-zag?",
          "Are we criss-cross?",
          "Are we super-duper!"
        ],
      },
    ],
    preposition: [
      {
        name: "Negative" as const,
        sentence: ["No Sentences"],

      },
      {
        name: "Positive" as const,
        sentence: ["No Sentences"],
      },
      {
        name: "Yes/No Questions" as const,
        sentence: ["No Sentences"],
      },
    ],
    objective: [
      {
        name: "Negative" as const,
        sentence: [
          "The adventure isn't for us.",
          "The adventure isn't new for us.",
          "The adventure isn't planned for us.",
          "The airplane isn't ready for us.",
          "The amusement park isn't for us.",
          "The balloons aren't for us.",
          "The beach isn't beautiful for us.",
          "The book isn't for us.",
          "The bridge isn't for us to cross.",
          "The bridge isn't strong for us.",
          "The cake isn't delicious for us.",
          "The cake isn't for us.",
          "The cake isn't sweet for us.",
          "The castle isn't for us to explore.",
          "The castle isn't for us.",
          "The chocolate isn't delicious for us.",
          "The chocolate isn't for us.",
          "The clouds aren't fluffy for us.",
          "The clouds aren't over us.",
          "The cookies aren't for us.",
          "The cookies aren't fresh for us.",
          "The cookies aren't warm for us.",
          "The dance isn't for us to enjoy.",
          "The dance isn't fun for us.",
          "The dream isn't big for us.",
          "The fair isn't for us to explore.",
          "The fair isn't fun for us.",
          "The Ferris wheel isn't for us.",
          "The flowers aren't colorful for us.",
          "The flowers aren't for us.",
          "The forest isn't dark for us.",
          "The forest isn't full of fun for us.",
          "The forest isn't fun for us.",
          "The forest isn't mysterious for us.",
          "The fruits aren't healthy for us.",
          "The fruits aren't ready for us.",
          "The fun isn't endless for us.",
          "The fun isn't with us.",
          "The funhouse isn't fun for us.",
          "The funhouse isn't ready for us.",
          "The games aren't ready for us.",
          "The grass isn't green for us.",
          "The grass isn't under us.",
          "The happiness isn't for us.",
          "The happiness isn't with us.",
          "The ice cream isn't cold for us.",
          "The ice cream isn't for us.",
          "The ice cream isn't tasty for us.",
          "The journey isn't ahead of us.",
          "The jungle isn't full of surprises for us.",
          "The magic isn't all around us.",
          "The magic isn't real for us.",
          "The moon isn't watching us.",
          "The mountain isn't high for us.",
          "The mountain isn't ready for us.",
          "The movie isn't ready for us.",
          "The music isn't fun for us.",
          "The music isn't happy for us.",
          "The music isn't joyful for us.",
          "The mystery isn't exciting for us.",
          "The mystery isn't for us to solve.",
          "The night isn't peaceful for us.",
          "The night isn't quiet for us.",
          "The ocean isn't deep for us.",
          "The park isn't for us to play in.",
          "The park isn't fun for us.",
          "The party isn't for us.",
          "The path isn't for us to discover.",
          "The path isn't for us to follow.",
          "The path isn't for us.",
          "The path isn't open for us.",
          "The picnic isn't for us.",
          "The picnic isn't fun for us.",
          "The picnic isn't prepared for us.",
          "The playground isn't for us.",
          "The popcorn isn't for us.",
          "The presents aren't for us.",
          "The puzzle isn't tricky for us.",
          "The puzzles aren't for us.",
          "The rain isn't cool for us.",
          "The rain isn't good for us.",
          "The rain isn't over us.",
          "The rainbow isn't a surprise for us.",
          "The rainbow isn't above us.",
          "The rainbow isn't colorful for us.",
          "The ride isn't fun for us.",
          "The river isn't calm for us.",
          "The road isn't clear for us.",
          "The road isn't open for us.",
          "The seats aren't reserved for us.",
          "The ship isn't ready for us.",
          "The show isn't for us.",
          "The slide isn't for us.",
          "The snack isn't ready for us.",
          "The snow isn't soft for us.",
          "The snowflakes aren't for us.",
          "The song isn't happy for us.",
          "The stars aren't bright for us.",
          "The story isn't about us.",
          "The storybook isn't for us.",
          "The sun isn't hot for us.",
          "The sun isn't warm for us.",
          "The swing isn't for us.",
          "The swing isn't ready for us.",
          "The teacher isn't kind to us.",
          "The toys aren't for us.",
          "The treasure isn't for us to find.",
          "The treasure isn't hidden for us.",
          "The treasure map isn't for us.",
          "The waterfall isn't refreshing for us.",
          "The wind isn't gentle for us.",
          "The wind isn't strong around us.",
          "The world isn't big for us to explore.",
          "The world isn't big for us."
        ]
        
      },
      {
        name: "Positive" as const,
        sentence: [
          "The adventure is for us.",
          "The adventure is new for us.",
          "The adventure is planned for us.",
          "The airplane is ready for us.",
          "The amusement park is for us.",
          "The balloons are for us.",
          "The beach is beautiful for us.",
          "The book is for us.",
          "The bridge is for us to cross.",
          "The bridge is strong for us.",
          "The cake is delicious for us.",
          "The cake is for us.",
          "The cake is sweet for us.",
          "The castle is for us to explore.",
          "The castle is for us.",
          "The chocolate is delicious for us.",
          "The chocolate is for us.",
          "The clouds are fluffy for us.",
          "The clouds are over us.",
          "The cookies are for us.",
          "The cookies are fresh for us.",
          "The cookies are warm for us.",
          "The dance is for us to enjoy.",
          "The dance is fun for us.",
          "The dream is big for us.",
          "The fair is for us to explore.",
          "The fair is fun for us.",
          "The Ferris wheel is for us.",
          "The flowers are colorful for us.",
          "The flowers are for us.",
          "The forest is dark for us.",
          "The forest is full of fun for us.",
          "The forest is fun for us.",
          "The forest is mysterious for us.",
          "The fruits are healthy for us.",
          "The fruits are ready for us.",
          "The fun is endless for us.",
          "The fun is with us.",
          "The funhouse is fun for us.",
          "The funhouse is ready for us.",
          "The games are ready for us.",
          "The grass is green for us.",
          "The grass is under us.",
          "The happiness is for us.",
          "The happiness is with us.",
          "The ice cream is cold for us.",
          "The ice cream is for us.",
          "The ice cream is tasty for us.",
          "The journey is ahead of us.",
          "The jungle is full of surprises for us.",
          "The magic is all around us.",
          "The magic is real for us.",
          "The moon is watching us.",
          "The mountain is high for us.",
          "The mountain is ready for us.",
          "The movie is ready for us.",
          "The music is fun for us.",
          "The music is happy for us.",
          "The music is joyful for us.",
          "The mystery is exciting for us.",
          "The mystery is for us to solve.",
          "The night is peaceful for us.",
          "The night is quiet for us.",
          "The ocean is deep for us.",
          "The park is for us to play in.",
          "The park is fun for us.",
          "The party is for us.",
          "The path is for us to discover.",
          "The path is for us to follow.",
          "The path is for us.",
          "The path is open for us.",
          "The picnic is for us.",
          "The picnic is fun for us.",
          "The picnic is prepared for us.",
          "The playground is for us.",
          "The popcorn is for us.",
          "The presents are for us.",
          "The puzzle is tricky for us.",
          "The puzzles are for us.",
          "The rain is cool for us.",
          "The rain is good for us.",
          "The rain is over us.",
          "The rainbow is a surprise for us.",
          "The rainbow is above us.",
          "The rainbow is colorful for us.",
          "The ride is fun for us.",
          "The river is calm for us.",
          "The road is clear for us.",
          "The road is open for us.",
          "The seats are reserved for us.",
          "The ship is ready for us.",
          "The show is for us.",
          "The slide is for us.",
          "The snack is ready for us.",
          "The snow is soft for us.",
          "The snowflakes are for us.",
          "The song is happy for us.",
          "The stars are bright for us.",
          "The story is about us.",
          "The storybook is for us.",
          "The sun is hot for us.",
          "The sun is warm for us.",
          "The swing is for us.",
          "The swing is ready for us.",
          "The teacher is kind to us.",
          "The toys are for us.",
          "The treasure is for us to find.",
          "The treasure is hidden for us.",
          "The treasure map is for us.",
          "The waterfall is refreshing for us.",
          "The wind is gentle for us.",
          "The wind is strong around us.",
          "The world is big for us to explore.",
          "The world is big for us.",
        ],
      },
      {
        name: "Yes/No Questions" as const,
        sentence: [
          "Is the adventure for us?",
          "Is the adventure new for us?",
          "Is the adventure planned for us?",
          "Is the airplane ready for us?",
          "Is the amusement park for us?",
          "Are the balloons for us?",
          "Is the beach beautiful for us?",
          "Is the book for us?",
          "Is the bridge for us to cross?",
          "Is the bridge strong for us?",
          "Is the cake delicious for us?",
          "Is the cake for us?",
          "Is the cake sweet for us?",
          "Is the castle for us to explore?",
          "Is the castle for us?",
          "Is the chocolate delicious for us?",
          "Is the chocolate for us?",
          "Are the clouds fluffy for us?",
          "Are the clouds over us?",
          "Are the cookies for us?",
          "Are the cookies fresh for us?",
          "Are the cookies warm for us?",
          "Is the dance for us to enjoy?",
          "Is the dance fun for us?",
          "Is the dream big for us?",
          "Is the fair for us to explore?",
          "Is the fair fun for us?",
          "Is the Ferris wheel for us?",
          "Are the flowers colorful for us?",
          "Are the flowers for us?",
          "Is the forest dark for us?",
          "Is the forest full of fun for us?",
          "Is the forest fun for us?",
          "Is the forest mysterious for us?",
          "Are the fruits healthy for us?",
          "Are the fruits ready for us?",
          "Is the fun endless for us?",
          "Is the fun with us?",
          "Is the funhouse fun for us?",
          "Is the funhouse ready for us?",
          "Are the games ready for us?",
          "Is the grass green for us?",
          "Is the grass under us?",
          "Is the happiness for us?",
          "Is the happiness with us?",
          "Is the ice cream cold for us?",
          "Is the ice cream for us?",
          "Is the ice cream tasty for us?",
          "Is the journey ahead of us?",
          "Is the jungle full of surprises for us?",
          "Is the magic all around us?",
          "Is the magic real for us?",
          "Is the moon watching us?",
          "Is the mountain high for us?",
          "Is the mountain ready for us?",
          "Is the movie ready for us?",
          "Is the music fun for us?",
          "Is the music happy for us?",
          "Is the music joyful for us?",
          "Is the mystery exciting for us?",
          "Is the mystery for us to solve?",
          "Is the night peaceful for us?",
          "Is the night quiet for us?",
          "Is the ocean deep for us?",
          "Is the park for us to play in?",
          "Is the park fun for us?",
          "Is the party for us?",
          "Is the path for us to discover?",
          "Is the path for us to follow?",
          "Is the path for us?",
          "Is the path open for us?",
          "Is the picnic for us?",
          "Is the picnic fun for us?",
          "Is the picnic prepared for us?",
          "Is the playground for us?",
          "Is the popcorn for us?",
          "Are the presents for us?",
          "Is the puzzle tricky for us?",
          "Are the puzzles for us?",
          "Is the rain cool for us?",
          "Is the rain good for us?",
          "Is the rain over us?",
          "Is the rainbow a surprise for us?",
          "Is the rainbow above us?",
          "Is the rainbow colorful for us?",
          "Is the ride fun for us?",
          "Is the river calm for us?",
          "Is the road clear for us?",
          "Is the road open for us?",
          "Are the seats reserved for us?",
          "Is the ship ready for us?",
          "Is the show for us?",
          "Is the slide for us?",
          "Is the snack ready for us?",
          "Is the snow soft for us?",
          "Are the snowflakes for us?",
          "Is the song happy for us?",
          "Are the stars bright for us?",
          "Is the story about us?",
          "Is the storybook for us?",
          "Is the sun hot for us?",
          "Is the sun warm for us?",
          "Is the swing for us?",
          "Is the swing ready for us?",
          "Is the teacher kind to us?",
          "Are the toys for us?",
          "Is the treasure for us to find?",
          "Is the treasure hidden for us?",
          "Is the treasure map for us?",
          "Is the waterfall refreshing for us?",
          "Is the wind gentle for us?",
          "Is the wind strong around us?",
          "Is the world big for us to explore?",
          "Is the world big for us?"
        ]
        
      },
    ],
    possesive: [
      {
        name: "Negative" as const,
        sentence: [
          "Our activity isn't cool.",
          "Our adventure isn't thrilling.",
          "Our art isn't beautiful.",
          "Our art isn't colorful.",
          "Our bikes aren't fast.",
          "Our book isn't cool.",
          "Our book isn't exciting.",
          "Our book isn't interesting.",
          "Our books aren't colorful.",
          "Our camp isn't awesome.",
          "Our class isn't cheerful.",
          "Our class isn't great.",
          "Our class isn't happy.",
          "Our class isn't lively.",
          "Our classroom isn't neat.",
          "Our clothes aren't comfy.",
          "Our clothes aren't pretty.",
          "Our day isn't bright.",
          "Our day isn't fun.",
          "Our day isn't special.",
          "Our drawing isn't nice.",
          "Our drawings aren't bright.",
          "Our events aren't fun.",
          "Our family isn't awesome.",
          "Our family isn't caring.",
          "Our family isn't kind.",
          "Our family isn't loving.",
          "Our family isn't supportive.",
          "Our field trip isn't fun.",
          "Our friends aren't caring.",
          "Our friends aren't funny.",
          "Our friends aren't helpful.",
          "Our friends aren't kind.",
          "Our friends aren't silly.",
          "Our game isn't exciting.",
          "Our game isn't fun.",
          "Our games aren't fair.",
          "Our games aren't fun.",
          "Our garden isn't green.",
          "Our garden isn't pretty.",
          "Our goals aren't clear.",
          "Our holiday isn't amazing.",
          "Our holiday isn't fun.",
          "Our homework isn't easy.",
          "Our house isn't cozy.",
          "Our jokes aren't funny.",
          "Our lunch isn't good.",
          "Our lunch isn't yummy.",
          "Our movie isn't exciting.",
          "Our movie isn't fun.",
          "Our music isn't cheerful.",
          "Our music isn't happy.",
          "Our music isn't lively.",
          "Our neighborhood isn't safe.",
          "Our park isn't beautiful.",
          "Our park isn't lively.",
          "Our park isn't lovely.",
          "Our party isn't awesome.",
          "Our party isn't lively.",
          "Our pet isn't cute.",
          "Our pet isn't playful.",
          "Our pets aren't cute.",
          "Our pets aren't friendly.",
          "Our pets aren't playful.",
          "Our pets aren't sweet.",
          "Our picnic isn't great.",
          "Our plans aren't fun.",
          "Our playground isn't big.",
          "Our playground isn't fun.",
          "Our playground isn't nice.",
          "Our project isn't interesting.",
          "Our room isn't big.",
          "Our school isn't bright.",
          "Our school isn't cool.",
          "Our science isn't cool.",
          "Our shoes aren't comfy.",
          "Our snack isn't tasty.",
          "Our snacks aren't tasty.",
          "Our stories aren't fun.",
          "Our story isn't cool.",
          "Our story isn't fun.",
          "Our teacher isn't funny.",
          "Our teacher isn't nice.",
          "Our teachers aren't nice.",
          "Our team isn't exciting.",
          "Our team isn't friendly.",
          "Our team isn't happy.",
          "Our team isn't helpful.",
          "Our team isn't smart.",
          "Our team isn't strong.",
          "Our toys aren't colorful.",
          "Our toys aren't exciting.",
          "Our toys aren't fun.",
          "Our trip isn't cool.",
          "Our trip isn't exciting.",
          "Our weekend isn't exciting.",
          "Our weekend isn't fun."
        ]
        
      },
      {
        name: "Positive" as const,
        sentence: [
          "Our activity is cool.",
          "Our adventure is thrilling.",
          "Our art is beautiful.",
          "Our art is colorful.",
          "Our bikes are fast.",
          "Our book is cool.",
          "Our book is exciting.",
          "Our book is interesting.",
          "Our books are colorful.",
          "Our camp is awesome.",
          "Our class is cheerful.",
          "Our class is great.",
          "Our class is happy.",
          "Our class is lively.",
          "Our classroom is neat.",
          "Our clothes are comfy.",
          "Our clothes are pretty.",
          "Our day is bright.",
          "Our day is fun.",
          "Our day is special.",
          "Our drawing is nice.",
          "Our drawings are bright.",
          "Our events are fun.",
          "Our family is awesome.",
          "Our family is caring.",
          "Our family is kind.",
          "Our family is loving.",
          "Our family is supportive.",
          "Our field trip is fun.",
          "Our friends are caring.",
          "Our friends are funny.",
          "Our friends are helpful.",
          "Our friends are kind.",
          "Our friends are silly.",
          "Our game is exciting.",
          "Our game is fun.",
          "Our games are fair.",
          "Our games are fun.",
          "Our garden is green.",
          "Our garden is pretty.",
          "Our goals are clear.",
          "Our holiday is amazing.",
          "Our holiday is fun.",
          "Our homework is easy.",
          "Our house is cozy.",
          "Our jokes are funny.",
          "Our lunch is good.",
          "Our lunch is yummy.",
          "Our movie is exciting.",
          "Our movie is fun.",
          "Our music is cheerful.",
          "Our music is happy.",
          "Our music is lively.",
          "Our neighborhood is safe.",
          "Our park is beautiful.",
          "Our park is lively.",
          "Our park is lovely.",
          "Our party is awesome.",
          "Our party is lively.",
          "Our pet is cute.",
          "Our pet is playful.",
          "Our pets are cute.",
          "Our pets are friendly.",
          "Our pets are playful.",
          "Our pets are sweet.",
          "Our picnic is great.",
          "Our plans are fun.",
          "Our playground is big.",
          "Our playground is fun.",
          "Our playground is nice.",
          "Our project is interesting.",
          "Our room is big.",
          "Our school is bright.",
          "Our school is cool.",
          "Our science is cool.",
          "Our shoes are comfy.",
          "Our snack is tasty.",
          "Our snacks are tasty.",
          "Our stories are fun.",
          "Our story is cool.",
          "Our story is fun.",
          "Our teacher is funny.",
          "Our teacher is nice.",
          "Our teachers are nice.",
          "Our team is exciting.",
          "Our team is friendly.",
          "Our team is happy.",
          "Our team is helpful.",
          "Our team is smart.",
          "Our team is strong.",
          "Our toys are colorful.",
          "Our toys are exciting.",
          "Our toys are fun.",
          "Our trip is cool.",
          "Our trip is exciting.",
          "Our weekend is exciting.",
          "Our weekend is fun.",
        ],
      },
      {
        name: "Yes/No Questions" as const,
        sentence: [
          "Is our activity cool?",
          "Is our adventure thrilling?",
          "Is our art beautiful?",
          "Is our art colorful?",
          "Are our bikes fast?",
          "Is our book cool?",
          "Is our book exciting?",
          "Is our book interesting?",
          "Are our books colorful?",
          "Is our camp awesome?",
          "Is our class cheerful?",
          "Is our class great?",
          "Is our class happy?",
          "Is our class lively?",
          "Is our classroom neat?",
          "Are our clothes comfy?",
          "Are our clothes pretty?",
          "Is our day bright?",
          "Is our day fun?",
          "Is our day special?",
          "Is our drawing nice?",
          "Are our drawings bright?",
          "Are our events fun?",
          "Is our family awesome?",
          "Is our family caring?",
          "Is our family kind?",
          "Is our family loving?",
          "Is our family supportive?",
          "Is our field trip fun?",
          "Are our friends caring?",
          "Are our friends funny?",
          "Are our friends helpful?",
          "Are our friends kind?",
          "Are our friends silly?",
          "Is our game exciting?",
          "Is our game fun?",
          "Are our games fair?",
          "Are our games fun?",
          "Is our garden green?",
          "Is our garden pretty?",
          "Are our goals clear?",
          "Is our holiday amazing?",
          "Is our holiday fun?",
          "Is our homework easy?",
          "Is our house cozy?",
          "Are our jokes funny?",
          "Is our lunch good?",
          "Is our lunch yummy?",
          "Is our movie exciting?",
          "Is our movie fun?",
          "Is our music cheerful?",
          "Is our music happy?",
          "Is our music lively?",
          "Is our neighborhood safe?",
          "Is our park beautiful?",
          "Is our park lively?",
          "Is our park lovely?",
          "Is our party awesome?",
          "Is our party lively?",
          "Is our pet cute?",
          "Is our pet playful?",
          "Are our pets cute?",
          "Are our pets friendly?",
          "Are our pets playful?",
          "Are our pets sweet?",
          "Is our picnic great?",
          "Are our plans fun?",
          "Is our playground big?",
          "Is our playground fun?",
          "Is our playground nice?",
          "Is our project interesting?",
          "Is our room big?",
          "Is our school bright?",
          "Is our school cool?",
          "Is our science cool?",
          "Are our shoes comfy?",
          "Is our snack tasty?",
          "Are our snacks tasty?",
          "Are our stories fun?",
          "Is our story cool?",
          "Is our story fun?",
          "Is our teacher funny?",
          "Is our teacher nice?",
          "Are our teachers nice?",
          "Is our team exciting?",
          "Is our team friendly?",
          "Is our team happy?",
          "Is our team helpful?",
          "Is our team smart?",
          "Is our team strong?",
          "Are our toys colorful?",
          "Are our toys exciting?",
          "Are our toys fun?",
          "Is our trip cool?",
          "Is our trip exciting?",
          "Is our weekend exciting?",
          "Is our weekend fun?"
        ]
        ,
      },
    ],
  },
];


export const yourselvesData = [
  {
    name: "Yourselves",
    "Singular Noun": [
      {
        name: "Negative" as const,
        sentence: [
          "You're not a dinosaur.",
          "You're not a superhero.",
          "You're not a unicorn.",
          "You're not a teacher.",
          "You're not an astronaut.",
          "You're not a pizza.",
          "You're not a robot.",
          "You're not a princess.",
          "You're not a pirate.",
          "You're not a dragon.",
          "You're not a firefighter.",
          "You're not a scientist.",
          "You're not a mermaid.",
          "You're not a wizard.",
          "You're not a vet.",
          "You're not a chef.",
          "You're not a clown.",
          "You're not a detective.",
          "You're not a knight.",
          "You're not a magician.",
          "You're not a singer.",
          "You're not an athlete.",
          "You're not a farmer.",
          "You're not a doctor.",
          "You're not a pilot.",
          "You're not a dancer.",
          "You're not an artist.",
          "You're not a zookeeper.",
          "You're not a lifeguard.",
          "You're not a ninja.",
          "You're not a painter.",
          "You're not an explorer.",
          "You're not a dentist.",
          "You're not a librarian.",
          "You're not a police officer.",
          "You're not a gardener.",
          "You're not a musician.",
          "You're not a baker.",
          "You're not a surfer.",
          "You're not a photographer.",
          "You're not a bus driver.",
          "You're not a cowboy.",
          "You're not a nurse.",
          "You're not a judge.",
          "You're not a movie star.",
          "You're not a football player.",
          "You're not a builder.",
          "You're not a toy maker.",
          "You're not a hair stylist.",
          "You're not a rocket scientist.",
          "You're not a skateboarder.",
          "You're not a comedian.",
          "You're not a puppeteer.",
          "You're not a fisherman.",
          "You're not a meteorologist.",
          "You're not a carpenter.",
          "You're not a scuba diver.",
          "You're not a fortune teller.",
          "You're not a geologist.",
          "You're not a race car driver.",
          "You're not a tailor.",
          "You're not a news anchor.",
          "You're not a beekeeper.",
          "You're not a gymnast.",
          "You're not a tour guide.",
          "You're not a train conductor.",
          "You're not a park ranger.",
          "You're not a balloon artist.",
          "You're not a tennis player.",
          "You're not a cheerleader.",
          "You're not a pastry chef.",
          "You're not a mountain climber.",
          "You're not a violinist.",
          "You're not a juggler.",
          "You're not a storyteller.",
          "You're not a mechanic.",
          "You're not a botanist.",
          "You're not a figure skater.",
          "You're not a ventriloquist.",
          "You're not a cartoonist.",
          "You're not a submarine captain.",
          "You're not a jeweler.",
          "You're not a paleontologist.",
          "You're not a magician's assistant.",
          "You're not a wildlife photographer.",
          "You're not a tightrope walker.",
          "You're not a computer programmer.",
          "You're not a bee.",
          "You're not a lion tamer.",
          "You're not a sushi chef.",
          "You're not a treasure hunter.",
          "You're not a crossing guard.",
          "You're not a snowboard instructor.",
          "You're not a voice actor.",
          "You're not a toy designer.",
          "You're not a martial arts instructor.",
          "You're not a balloon pilot.",
          "You're not a radio DJ.",
          "You're not a gondolier.",
          "You're not a time traveler."
      ]
      
      },
      {
        name: "Positive" as const,
        sentence: [
          "You're a dinosaur.",
          "You're a superhero.",
          "You're a unicorn.",
          "You're a teacher.",
          "You're an astronaut.",
          "You're a pizza.",
          "You're a robot.",
          "You're a princess.",
          "You're a pirate.",
          "You're a dragon.",
          "You're a firefighter.",
          "You're a scientist.",
          "You're a mermaid.",
          "You're a wizard.",
          "You're a vet.",
          "You're a chef.",
          "You're a clown.",
          "You're a detective.",
          "You're a knight.",
          "You're a magician.",
          "You're a singer.",
          "You're an athlete.",
          "You're a farmer.",
          "You're a doctor.",
          "You're a pilot.",
          "You're a dancer.",
          "You're an artist.",
          "You're a zookeeper.",
          "You're a lifeguard.",
          "You're a ninja.",
          "You're a painter.",
          "You're an explorer.",
          "You're a dentist.",
          "You're a librarian.",
          "You're a police officer.",
          "You're a gardener.",
          "You're a musician.",
          "You're a baker.",
          "You're a surfer.",
          "You're a photographer.",
          "You're a bus driver.",
          "You're a cowboy.",
          "You're a nurse.",
          "You're a judge.",
          "You're a movie star.",
          "You're a football player.",
          "You're a builder.",
          "You're a toy maker.",
          "You're a hair stylist.",
          "You're a rocket scientist.",
          "You're a skateboarder.",
          "You're a comedian.",
          "You're a puppeteer.",
          "You're a fisherman.",
          "You're a meteorologist.",
          "You're a carpenter.",
          "You're a scuba diver.",
          "You're a fortune teller.",
          "You're a geologist.",
          "You're a race car driver.",
          "You're a tailor.",
          "You're a news anchor.",
          "You're a beekeeper.",
          "You're a gymnast.",
          "You're a tour guide.",
          "You're a train conductor.",
          "You're a park ranger.",
          "You're a balloon artist.",
          "You're a tennis player.",
          "You're a cheerleader.",
          "You're a pastry chef.",
          "You're a mountain climber.",
          "You're a violinist.",
          "You're a juggler.",
          "You're a storyteller.",
          "You're a mechanic.",
          "You're a botanist.",
          "You're a figure skater.",
          "You're a ventriloquist.",
          "You're a cartoonist.",
          "You're a submarine captain.",
          "You're a jeweler.",
          "You're a paleontologist.",
          "You're a magician's assistant.",
          "You're a wildlife photographer.",
          "You're a tightrope walker.",
          "You're a computer programmer.",
          "You're a bee.",
          "You're a lion tamer.",
          "You're a sushi chef.",
          "You're a treasure hunter.",
          "You're a crossing guard.",
          "You're a snowboard instructor.",
          "You're a voice actor.",
          "You're a toy designer.",
          "You're a martial arts instructor.",
          "You're a balloon pilot.",
          "You're a radio DJ.",
          "You're a gondolier.",
          "You're a time traveler."
      ]
      
      },
      {
        name: "Yes/No Questions" as const,
        sentence: [
          "Are we kids?",
          "Are we friends?",
          "Are we students?",
          "Are we players?",
          "Are we helpers?",
          "Are we artists?",
          "Are we singers?",
          "Are we swimmers?",
          "Are we runners?",
          "Are we dreamers?",
          "Are we builders?",
          "Are we thinkers?",
          "Are we dancers?",
          "Are we team members?",
          "Are we cooks?",
          "Are we gardeners?",
          "Are we travelers?",
          "Are we storytellers?",
          "Are we animal lovers?",
          "Are we climbers?",
          "Are we painters?",
          "Are we jokers?",
          "Are we scientists?",
          "Are we explorers?",
          "Are we stargazers?",
          "Are we bike riders?",
          "Are we bug catchers?",
          "Are we campers?",
          "Are we snow players?",
          "Are we tree climbers?",
          "Are we fort builders?",
          "Are we puzzle solvers?",
          "Are we cookie bakers?",
          "Are we toy makers?",
          "Are we nature lovers?",
          "Are we game players?",
          "Are we pet owners?",
          "Are we sandcastle builders?",
          "Are we beach combers?",
          "Are we kite flyers?",
          "Are we bubble blowers?",
          "Are we dinosaur fans?",
          "Are we lego builders?",
          "Are we skaters?",
          "Are we flower pickers?",
          "Are we bird watchers?",
          "Are we rock collectors?",
          "Are we soccer players?",
          "Are we balloon poppers?",
          "Are we ice cream eaters?",
          "Are we picture drawers?",
          "Are we joke tellers?",
          "Are we hide-and-seekers?",
          "Are we arm wrestlers?",
          "Are we cloud watchers?",
          "Are we mud puddle jumpers?",
          "Are we train riders?",
          "Are we blanket fort makers?",
          "Are we finger painters?",
        ],
      },
    ],
    "Plural Noun": [
      {
        name: "Negative" as const,
        sentence: [
          "We're not excited!",
          "We're not hungry.",
          "We're not silly.",
          "We're not smart.",
          "We're not brave.",
          "We're not happy.",
          "We're not curious.",
          "We're not friendly.",
          "We're not helpful.",
          "We're not creative.",
          "We're not energetic.",
          "We're not kind.",
          "We're not funny.",
          "We're not loud.",
          "We're not quiet.",
          "We're not playful.",
          "We're not sleepy.",
          "We're not busy.",
          "We're not calm.",
          "We're not noisy.",
          "We're not careful.",
          "We're not messy.",
          "We're not tidy.",
          "We're not clever.",
          "We're not gentle.",
          "We're not strong.",
          "We're not fast.",
          "We're not slow.",
          "We're not patient.",
          "We're not impatient.",
          "We're not colorful.",
          "We're not giggly.",
          "We're not thoughtful.",
          "We're not adventurous.",
          "We're not polite.",
          "We're not shy.",
          "We're not outgoing.",
          "We're not tall.",
          "We're not short.",
          "We're not active.",
          "We're not relaxed.",
          "We're not musical.",
          "We're not artistic.",
          "We're not sporty.",
          "We're not cheerful.",
          "We're not grumpy.",
          "We're not excited.",
          "We're not bored.",
          "We're not proud.",
          "We're not humble.",
          "We're not fuzzy.",
          "We're not smooth.",
          "We're not bouncy.",
          "We're not wiggly.",
          "We're not jumpy.",
          "We're not sparkly.",
          "We're not shiny.",
          "We're not bubbly.",
          "We're not squiggly.",
          "We're not squishy.",
          "We're not soft.",
          "We're not hard.",
          "We're not fluffy.",
          "We're not slimy.",
          "We're not sticky.",
          "We're not wet.",
          "We're not dry.",
          "We're not hot.",
          "We're not cold.",
          "We're not warm.",
          "We're not cool.",
          "We're not bumpy.",
          "We're not smooth.",
          "We're not rough.",
          "We're not cuddly.",
          "We're not ticklish.",
          "We're not wibbly-wobbly.",
          "We're not zigzaggy.",
          "We're not swirly.",
          "We're not stretchy.",
          "We're not bouncy.",
          "We're not wobbly.",
          "We're not jiggly.",
          "We're not floppy.",
          "We're not snuggly.",
          "We're not cozy.",
          "We're not jolly.",
          "We're not silly-willy.",
          "We're not topsy-turvy.",
          "We're not upside-down.",
          "We're not right-side-up.",
          "We're not inside-out.",
          "We're not outside-in.",
          "We're not front-to-back.",
          "We're not back-to-front.",
          "We're not tippy-toe.",
          "We're not zig-zag.",
          "We're not criss-cross.",
          "We're not super-duper!"
        ]
        ,
      },
      {
        name: "Positive" as const,
        sentence: [
          "We're excited!",
          "We're hungry.",
          "We're silly.",
          "We're smart.",
          "We're brave.",
          "We're happy.",
          "We're curious.",
          "We're friendly.",
          "We're helpful.",
          "We're creative.",
          "We're energetic.",
          "We're kind.",
          "We're funny.",
          "We're loud.",
          "We're quiet.",
          "We're playful.",
          "We're sleepy.",
          "We're busy.",
          "We're calm.",
          "We're noisy.",
          "We're careful.",
          "We're messy.",
          "We're tidy.",
          "We're clever.",
          "We're gentle.",
          "We're strong.",
          "We're fast.",
          "We're slow.",
          "We're patient.",
          "We're impatient.",
          "We're colorful.",
          "We're giggly.",
          "We're thoughtful.",
          "We're adventurous.",
          "We're polite.",
          "We're shy.",
          "We're outgoing.",
          "We're tall.",
          "We're short.",
          "We're active.",
          "We're relaxed.",
          "We're musical.",
          "We're artistic.",
          "We're sporty.",
          "We're cheerful.",
          "We're grumpy.",
          "We're excited.",
          "We're bored.",
          "We're proud.",
          "We're humble.",
          "We're fuzzy.",
          "We're smooth.",
          "We're bouncy.",
          "We're wiggly.",
          "We're jumpy.",
          "We're sparkly.",
          "We're shiny.",
          "We're bubbly.",
          "We're squiggly.",
          "We're squishy.",
          "We're soft.",
          "We're hard.",
          "We're fluffy.",
          "We're slimy.",
          "We're sticky.",
          "We're wet.",
          "We're dry.",
          "We're hot.",
          "We're cold.",
          "We're warm.",
          "We're cool.",
          "We're bumpy.",
          "We're smooth.",
          "We're rough.",
          "We're cuddly.",
          "We're ticklish.",
          "We're wibbly-wobbly.",
          "We're zigzaggy.",
          "We're swirly.",
          "We're stretchy.",
          "We're bouncy.",
          "We're wobbly.",
          "We're jiggly.",
          "We're floppy.",
          "We're snuggly.",
          "We're cozy.",
          "We're jolly.",
          "We're silly-willy.",
          "We're topsy-turvy.",
          "We're upside-down.",
          "We're right-side-up.",
          "We're inside-out.",
          "We're outside-in.",
          "We're front-to-back.",
          "We're back-to-front.",
          "We're tippy-toe.",
          "We're zig-zag.",
          "We're criss-cross.",
          "We're super-duper!",
        ],
      },
      {
        name: "Yes/No Questions" as const,
        sentence: [
          "Are we excited?",
          "Are we hungry?",
          "Are we silly?",
          "Are we smart?",
          "Are we brave?",
          "Are we happy?",
          "Are we curious?",
          "Are we friendly?",
          "Are we helpful?",
          "Are we creative?",
          "Are we energetic?",
          "Are we kind?",
          "Are we funny?",
          "Are we loud?",
          "Are we quiet?",
          "Are we playful?",
          "Are we sleepy?",
          "Are we busy?",
          "Are we calm?",
          "Are we noisy?",
          "Are we careful?",
          "Are we messy?",
          "Are we tidy?",
          "Are we clever?",
          "Are we gentle?",
          "Are we strong?",
          "Are we fast?",
          "Are we slow?",
          "Are we patient?",
          "Are we impatient?",
          "Are we colorful?",
          "Are we giggly?",
          "Are we thoughtful?",
          "Are we adventurous?",
          "Are we polite?",
          "Are we shy?",
          "Are we outgoing?",
          "Are we tall?",
          "Are we short?",
          "Are we active?",
          "Are we relaxed?",
          "Are we musical?",
          "Are we artistic?",
          "Are we sporty?",
          "Are we cheerful?",
          "Are we grumpy?",
          "Are we excited?",
          "Are we bored?",
          "Are we proud?",
          "Are we humble?",
          "Are we fuzzy?",
          "Are we smooth?",
          "Are we bouncy?",
          "Are we wiggly?",
          "Are we jumpy?",
          "Are we sparkly?",
          "Are we shiny?",
          "Are we bubbly?",
          "Are we squiggly?",
          "Are we squishy?",
          "Are we soft?",
          "Are we hard?",
          "Are we fluffy?",
          "Are we slimy?",
          "Are we sticky?",
          "Are we wet?",
          "Are we dry?",
          "Are we hot?",
          "Are we cold?",
          "Are we warm?",
          "Are we cool?",
          "Are we bumpy?",
          "Are we smooth?",
          "Are we rough?",
          "Are we cuddly?",
          "Are we ticklish?",
          "Are we wibbly-wobbly?",
          "Are we zigzaggy?",
          "Are we swirly?",
          "Are we stretchy?",
          "Are we bouncy?",
          "Are we wobbly?",
          "Are we jiggly?",
          "Are we floppy?",
          "Are we snuggly?",
          "Are we cozy?",
          "Are we jolly?",
          "Are we silly-willy?",
          "Are we topsy-turvy?",
          "Are we upside-down?",
          "Are we right-side-up?",
          "Are we inside-out?",
          "Are we outside-in?",
          "Are we front-to-back?",
          "Are we back-to-front?",
          "Are we tippy-toe?",
          "Are we zig-zag?",
          "Are we criss-cross?",
          "Are we super-duper!"
        ],
      },
    ],
    "Adjectives": [
      {
        name: "Negative" as const,
        sentence: ["No Sentences"],

      },
      {
        name: "Positive" as const,
        sentence: ["No Sentences"],
      },
      {
        name: "Yes/No Questions" as const,
        sentence: ["No Sentences"],
      },
    ],
  },
];