// data.ts
const data = [
  {
    name: "MySelf",
    "data set 1": [
      {
        name: "Positive" as const,
        sentence: [
          "I don't play the piano very well.",
          "Anna doesn't play the piano very well.",
          "They don't know my phone number.",
          "We don't work very hard.",
          "He doesn't have a bath every day.",
          "You don't do the same thing every day.",
          "I don't like spicy food.",
          "She doesn't go to the gym.",
          "They don't visit us often.",
          "We don't watch TV every night.",
          "He doesn't read books.",
          "You don't call me anymore.",
          "I don't drink coffee in the evening.",
          "She doesn't wear glasses.",
          "They don't play football.",
          "We don't eat out often.",
          "He doesn't drive to work.",
          "You don't listen to music.",
          "I don't go to bed late.",
          "She doesn't cook dinner.",
          "They don't travel abroad.",
          "We don't have pets.",
          "He doesn't speak French.",
          "You don't like chocolate.",
          "I don't swim in the ocean.",
          "She doesn't write letters.",
          "They don't attend meetings.",
          "We don't celebrate holidays.",
          "He doesn't wear a tie.",
          "You don't clean the house.",
          "I don't play video games.",
          "She doesn't drink tea.",
          "They don't go hiking.",
          "We don't visit museums.",
          "He doesn't use social media.",
          "You don't eat breakfast.",
          "I don't wear a watch.",
          "She doesn't like cats.",
          "They don't go to the beach.",
          "We don't read newspapers.",
          "He doesn't play the guitar.",
          "You don't take photos.",
          "I don't ride a bike.",
          "She doesn't like rain.",
          "They don't go fishing.",
          "We don't watch movies.",
          "He doesn't eat meat.",
          "You don't drink soda.",
          "I don't wear hats.",
          "She doesn't like winter.",
          "They don't go camping.",
          "We don't play chess.",
          "He doesn't use a laptop.",
          "You don't like ice cream.",
          "I don't wear makeup.",
          "She doesn't like summer.",
          "They don't go skiing.",
          "We don't play cards.",
          "He doesn't use a smartphone.",
          "You don't like pizza.",
          "I don't wear jewelry.",
          "She doesn't like autumn.",
          "They don't go running.",
          "We don't play tennis.",
          "He doesn't use a tablet.",
          "You don't like burgers.",
          "I don't wear perfume.",
          "She doesn't like spring.",
          "They don't go cycling.",
          "We don't play basketball.",
          "He doesn't use a camera.",
          "You don't like pasta.",
          "I don't wear sunglasses.",
          "She doesn't like flowers.",
          "They don't go swimming.",
          "We don't play soccer.",
          "He doesn't use a printer.",
          "You don't like sandwiches.",
          "I don't wear scarves.",
          "She doesn't like books.",
          "They don't go jogging.",
          "We don't play volleyball.",
          "He doesn't use a microwave.",
          "You don't like salads.",
          "I don't wear boots.",
          "She doesn't like movies.",
          "They don't go to concerts.",
          "We don't play golf.",
          "He doesn't use a dishwasher.",
          "You don't like soup.",
          "I don't wear gloves.",
          "She doesn't like music.",
          "They don't go to parties.",
          "We don't play badminton.",
          "He doesn't use a blender.",
          "You don't like cereal.",
          "I don't wear belts.",
          "She doesn't like dancing.",
          "They don't go to festivals.",
          "We don't play cricket.",
          "He doesn't use a vacuum cleaner.",
          "You don't like yogurt.",
          "I don't wear rings.",
          "She doesn't like painting.",
          "They don't go to the theater.",
          "We don't play rugby."
        ]
        },
    ],
    "data set 2": [
      {
        name: "Positive" as const,
        sentence: [
          "Ben and Sophie like classic music.",
          "Kate doesn't like classic music.",
          "I don't like classic music.",
          "Ben and Sophie don't like boxing.",
          "Kate likes boxing.",
          "I don't like boxing.",
          "Ben and Sophie like horror movies.",
          "Kate doesn't like horror movies.",
          "I don't like horror movies.",
          "Ben and Sophie like jazz music.",
          "Kate doesn't like jazz music.",
          "I don't like jazz music.",
          "Ben and Sophie don't like soccer.",
          "Kate likes soccer.",
          "I don't like soccer.",
          "Ben and Sophie like comedy movies.",
          "Kate doesn't like comedy movies.",
          "I don't like comedy movies.",
          "Ben and Sophie like Italian food.",
          "Kate doesn't like Italian food.",
          "I don't like Italian food.",
          "Ben and Sophie don't like swimming.",
          "Kate likes swimming.",
          "I don't like swimming.",
          "Ben and Sophie like science fiction books.",
          "Kate doesn't like science fiction books.",
          "I don't like science fiction books.",
          "Ben and Sophie don't like hiking.",
          "Kate likes hiking.",
          "I don't like hiking.",
          "Ben and Sophie like painting.",
          "Kate doesn't like painting.",
          "I don't like painting.",
          "Ben and Sophie don't like running.",
          "Kate likes running.",
          "I don't like running.",
          "Ben and Sophie like sushi.",
          "Kate doesn't like sushi.",
          "I don't like sushi.",
          "Ben and Sophie don't like dancing.",
          "Kate likes dancing.",
          "I don't like dancing.",
          "Ben and Sophie like mystery novels.",
          "Kate doesn't like mystery novels.",
          "I don't like mystery novels.",
          "Ben and Sophie don't like skiing.",
          "Kate likes skiing.",
          "I don't like skiing.",
          "Ben and Sophie like gardening.",
          "Kate doesn't like gardening.",
          "I don't like gardening.",
          "Ben and Sophie don't like fishing.",
          "Kate likes fishing.",
          "I don't like fishing.",
          "Ben and Sophie like rock music.",
          "Kate doesn't like rock music.",
          "I don't like rock music.",
          "Ben and Sophie don't like basketball.",
          "Kate likes basketball.",
          "I don't like basketball.",
          "Ben and Sophie like romantic movies.",
          "Kate doesn't like romantic movies.",
          "I don't like romantic movies.",
          "Ben and Sophie don't like cycling.",
          "Kate likes cycling.",
          "I don't like cycling.",
          "Ben and Sophie like spicy food.",
          "Kate doesn't like spicy food.",
          "I don't like spicy food.",
          "Ben and Sophie don't like reading.",
          "Kate likes reading.",
          "I don't like reading.",
          "Ben and Sophie like action movies.",
          "Kate doesn't like action movies.",
          "I don't like action movies.",
          "Ben and Sophie don't like cooking.",
          "Kate likes cooking.",
          "I don't like cooking.",
          "Ben and Sophie like classical literature.",
          "Kate doesn't like classical literature.",
          "I don't like classical literature.",
          "Ben and Sophie don't like traveling.",
          "Kate likes traveling.",
          "I don't like traveling.",
          "Ben and Sophie like pop music.",
          "Kate doesn't like pop music.",
          "I don't like pop music.",
          "Ben and Sophie don't like yoga.",
          "Kate likes yoga.",
          "I don't like yoga.",
          "Ben and Sophie like historical documentaries.",
          "Kate doesn't like historical documentaries.",
          "I don't like historical documentaries.",
          "Ben and Sophie don't like playing chess.",
          "Kate likes playing chess.",
          "I don't like playing chess.",
          "Ben and Sophie like seafood.",
          "Kate doesn't like seafood.",
          "I don't like seafood.",
          "Ben and Sophie don't like jogging.",
          "Kate likes jogging.",
          "I don't like jogging.",
          "Ben and Sophie like fantasy novels.",
          "Kate doesn't like fantasy novels.",
          "I don't like fantasy novels.",
          "Ben and Sophie don't like playing tennis.",
          "Kate likes playing tennis.",
          "I don't like playing tennis.",
          "Ben and Sophie like adventure movies."
        ]
         },
    ],
    "data set 3": [
      {
        name: "Positive" as const,
        sentence: [
          "I often watch TV.",
          "I don't go to the theatre very often.",
          "I never ride a bike.",
          "I often eat in restaurants.",
          "I don't travel by train very often.",
          "I often read books.",
          "I don't go to the gym very often.",
          "I never play video games.",
          "I often cook at home.",
          "I don't visit museums very often.",
          "I often listen to music.",
          "I don't go hiking very often.",
          "I never play golf.",
          "I often go for walks.",
          "I don't go to concerts very often.",
          "I often drink coffee.",
          "I don't go swimming very often.",
          "I never play tennis.",
          "I often write in my journal.",
          "I don't go to the beach very often.",
          "I often watch movies.",
          "I don't go fishing very often.",
          "I never play basketball.",
          "I often visit friends.",
          "I don't go camping very often.",
          "I often go shopping.",
          "I don't go skiing very often.",
          "I never play soccer.",
          "I often read the news.",
          "I don't go to the park very often.",
          "I often drink tea.",
          "I don't go to the library very often.",
          "I never play chess.",
          "I often go to cafes.",
          "I don't go to the zoo very often.",
          "I often write emails.",
          "I don't go to the countryside very often.",
          "I never play baseball.",
          "I often go to the gym.",
          "I don't go to the mountains very often.",
          "I often read magazines.",
          "I don't go to the aquarium very often.",
          "I never play volleyball.",
          "I often go to the market.",
          "I don't go to the spa very often.",
          "I often drink water.",
          "I don't go to the amusement park very often.",
          "I never play rugby.",
          "I often go to the bookstore.",
          "I don't go to the botanical garden very often.",
          "I often read blogs.",
          "I don't go to the flea market very often.",
          "I never play hockey.",
          "I often go to the bakery.",
          "I don't go to the theater very often.",
          "I often drink juice.",
          "I don't go to the gym very often.",
          "I never play cricket.",
          "I often go to the cinema.",
          "I don't go to the art gallery very often.",
          "I often read novels.",
          "I don't go to the farmer's market very often.",
          "I never play badminton.",
          "I often go to the library.",
          "I don't go to the lake very often.",
          "I often drink milk.",
          "I don't go to the river very often.",
          "I never play table tennis.",
          "I often go to the park.",
          "I don't go to the forest very often.",
          "I often read newspapers.",
          "I don't go to the desert very often.",
          "I never play handball.",
          "I often go to the beach.",
          "I don't go to the mountains very often.",
          "I often drink soda.",
          "I don't go to the city center very often.",
          "I never play squash.",
          "I often go to the countryside.",
          "I don't go to the suburbs very often.",
          "I often read poetry.",
          "I don't go to the island very often.",
          "I never play lacrosse.",
          "I often go to the mountains.",
          "I don't go to the village very often.",
          "I often drink herbal tea.",
          "I don't go to the riverbank very often.",
          "I never play water polo.",
          "I often go to the forest.",
          "I don't go to the meadow very often.",
          "I often read short stories.",
          "I don't go to the orchard very often.",
          "I never play field hockey.",
          "I often go to the desert.",
          "I don't go to the vineyard very often.",
          "I often drink hot chocolate.",
          "I don't go to the waterfall very often.",
          "I never play ice hockey.",
          "I often go to the island.",
          "I don't go to the canyon very often.",
          "I often read essays.",
          "I don't go to the plateau very often.",
          "I never play polo.",
          "I often go to the village.",
          "I don't go to the peninsula very often."
        ]
        },
    ],
    "data set 4": [
      {
        name: "Positive" as const,
        sentence: [
          "The weather here is usually nice. It doesn't rain much.",
          "Paul has a car, but he doesn't use it very often.",
          "Paul and his friends like films, but they don't go to the cinema very often.",
          "Amanda is married but she doesn't wear a ring.",
          "I don't know much about politics. I'm not interested in it.",
          "The Regent Hotel isn't expensive. It doesn't cost much to stay there.",
          "Ed lives very near us, but we don't see him very often.",
          "The weather here is usually warm. It doesn't snow much.",
          "Sarah has a bike, but she doesn't ride it very often.",
          "John and his friends like sports, but they don't play football very often.",
          "Lisa is engaged but she doesn't wear her engagement ring.",
          "I don't know much about art. I'm not interested in it.",
          "The local café isn't expensive. It doesn't cost much to eat there.",
          "Tom lives very near us, but we don't visit him very often.",
          "The weather here is usually dry. It doesn't rain much.",
          "Mike has a guitar, but he doesn't play it very often.",
          "Jane and her friends like music, but they don't go to concerts very often.",
          "David is married but he doesn't wear a wedding ring.",
          "I don't know much about history. I'm not interested in it.",
          "The new restaurant isn't expensive. It doesn't cost much to dine there.",
          "Emma lives very near us, but we don't see her very often.",
          "The weather here is usually mild. It doesn't get very hot.",
          "Anna has a piano, but she doesn't play it very often.",
          "Mark and his friends like hiking, but they don't go hiking very often.",
          "Rachel is married but she doesn't wear her wedding ring.",
          "I don't know much about science. I'm not interested in it.",
          "The local gym isn't expensive. It doesn't cost much to join.",
          "Steve lives very near us, but we don't meet him very often.",
          "The weather here is usually cool. It doesn't get very warm.",
          "Laura has a camera, but she doesn't use it very often.",
          "Chris and his friends like traveling, but they don't travel very often.",
          "Jessica is married but she doesn't wear her wedding ring.",
          "I don't know much about technology. I'm not interested in it.",
          "The new bookstore isn't expensive. It doesn't cost much to buy books there.",
          "Alex lives very near us, but we don't visit him very often.",
          "The weather here is usually sunny. It doesn't get very cloudy.",
          "Peter has a boat, but he doesn't sail it very often.",
          "Mary and her friends like reading, but they don't read very often.",
          "Tom is married but he doesn't wear his wedding ring.",
          "I don't know much about geography. I'm not interested in it.",
          "The local theater isn't expensive. It doesn't cost much to watch plays there.",
          "Linda lives very near us, but we don't see her very often.",
          "The weather here is usually pleasant. It doesn't get very cold.",
          "Sam has a skateboard, but he doesn't use it very often.",
          "Kate and her friends like dancing, but they don't dance very often.",
          "John is married but he doesn't wear his wedding ring.",
          "I don't know much about literature. I'm not interested in it.",
          "The new café isn't expensive. It doesn't cost much to have coffee there.",
          "Paul lives very near us, but we don't meet him very often.",
          "The weather here is usually calm. It doesn't get very windy.",
          "Alice has a violin, but she doesn't play it very often.",
          "Mike and his friends like fishing, but they don't fish very often.",
          "Sarah is married but she doesn't wear her wedding ring.",
          "I don't know much about economics. I'm not interested in it.",
          "The local park isn't crowded. It doesn't get very busy.",
          "Jane lives very near us, but we don't visit her very often.",
          "The weather here is usually clear. It doesn't get very foggy.",
          "David has a drone, but he doesn't fly it very often.",
          "Emma and her friends like cooking, but they don't cook very often.",
          "Mark is married but he doesn't wear his wedding ring.",
          "I don't know much about philosophy. I'm not interested in it.",
          "The new gym isn't crowded. It doesn't get very busy.",
          "Rachel lives very near us, but we don't see her very often.",
          "The weather here is usually stable. It doesn't change much.",
          "Chris has a telescope, but he doesn't use it very often.",
          "Laura and her friends like gardening, but they don't garden very often.",
          "Alex is married but he doesn't wear his wedding ring.",
          "I don't know much about astronomy. I'm not interested in it.",
          "The local library isn't crowded. It doesn't get very busy.",
          "Tom lives very near us, but we don't meet him very often.",
          "The weather here is usually moderate. It doesn't get very extreme.",
          "Peter has a motorcycle, but he doesn't ride it very often.",
          "Linda and her friends like knitting, but they don't knit very often.",
          "Steve is married but he doesn't wear his wedding ring.",
          "I don't know much about biology. I'm not interested in it.",
          "The new restaurant isn't crowded. It doesn't get very busy.",
          "Jessica lives very near us, but we don't visit her very often.",
          "The weather here is usually dry. It doesn't get very humid.",
          "Anna has a sewing machine, but she doesn't use it very often.",
          "John and his friends like painting, but they don't paint very often.",
          "Paul is married but he doesn't wear his wedding ring.",
          "I don't know much about chemistry. I'm not interested in it.",
          "The local café isn't crowded. It doesn't get very busy.",
          "Sarah lives very near us, but we don't see her very often.",
          "The weather here is usually warm. It doesn't get very cold.",
          "Mike has a surfboard, but he doesn't use it very often.",
          "Kate and her friends like baking, but they don't bake very often.",
          "David is married but he doesn't wear his wedding ring.",
          "I don't know much about physics. I'm not interested in it.",
          "The new bookstore isn't crowded. It doesn't get very busy.",
          "Alice lives very near us, but we don't meet her very often.",
          "The weather here is usually cool. It doesn't get very hot.",
          "Sam has a kayak, but he doesn't use it very often.",
          "Emma and her friends like sewing, but they don't sew very often.",
          "Mark is married but he doesn't wear his wedding ring.",
          "I don't know much about sociology. I'm not interested in it.",
          "The local theater isn't crowded. It doesn't get very busy.",
          "Chris lives very near us, but we don't visit him very often.",
          "The weather here is usually mild. It doesn't get very extreme.",
          "Peter has a snowboard, but he doesn't use it very often.",
          "Laura and her friends like crafting, but they don't craft very often.",
          "John is married but he doesn't wear his wedding ring.",
          "I don't know much about anthropology. I'm not interested in it.",
          "The new café isn't crowded. It doesn't get very busy.",
          "Linda lives very near us, but we don't see her very often.",
          "The weather here is usually pleasant. It doesn't get very harsh.",
          "David has a camera, but he doesn't use it very often."
        ]        
      },
    ],
    "data set 5": [
      {
        name: "Positive" as const,
        sentence: [
          "Margaret speaks four languages - English, French, German, and Spanish.",
          "I don't like my job. It's very boring.",
          "‘Where's Steve?' ‘I'm sorry. I don't know.'",
          "Sue is a very quiet person. She doesn't talk very much.",
          "Andy drinks a lot of tea. It's his favourite drink.",
          "It's not true! I don't believe it!",
          "That's a very beautiful picture. I like it very much.",
          "Mark is a vegetarian. He doesn't eat meat.",
          "Sarah speaks three languages - English, Italian, and Japanese.",
          "I don't enjoy my job. It's very stressful.",
          "‘Where's Anna?' ‘I'm sorry. I don't know.'",
          "John is a very shy person. He doesn't talk much.",
          "Emily drinks a lot of coffee. It's her favourite drink.",
          "It's not true! I don't believe it!",
          "That's a very interesting book. I like it very much.",
          "Lisa is a vegan. She doesn't eat dairy.",
          "Michael speaks five languages - English, Spanish, Chinese, Arabic, and Russian.",
          "I don't like my apartment. It's very small.",
          "‘Where's Tom?' ‘I'm sorry. I don't know.'",
          "Mary is a very reserved person. She doesn't talk much.",
          "James drinks a lot of water. It's his favourite drink.",
          "It's not true! I don't believe it!",
          "That's a very nice song. I like it very much.",
          "David is a pescatarian. He doesn't eat meat.",
          "Jessica speaks two languages - English and French.",
          "I don't like my car. It's very old.",
          "‘Where's Emma?' ‘I'm sorry. I don't know.'",
          "Robert is a very quiet person. He doesn't talk much.",
          "Laura drinks a lot of juice. It's her favourite drink.",
          "It's not true! I don't believe it!",
          "That's a very funny movie. I like it very much.",
          "Chris is a vegetarian. He doesn't eat fish.",
          "Olivia speaks four languages - English, German, Spanish, and Italian.",
          "I don't like my house. It's very noisy.",
          "‘Where's Jack?' ‘I'm sorry. I don't know.'",
          "Alice is a very introverted person. She doesn't talk much.",
          "Daniel drinks a lot of milk. It's his favourite drink.",
          "It's not true! I don't believe it!",
          "That's a very beautiful painting. I like it very much.",
          "Sophie is a vegan. She doesn't eat eggs.",
          "Henry speaks three languages - English, Portuguese, and Mandarin.",
          "I don't like my neighborhood. It's very crowded.",
          "‘Where's Lucy?' ‘I'm sorry. I don't know.'",
          "Kevin is a very reserved person. He doesn't talk much.",
          "Rachel drinks a lot of smoothies. It's her favourite drink.",
          "It's not true! I don't believe it!",
          "That's a very exciting game. I like it very much.",
          "Megan is a pescatarian. She doesn't eat chicken.",
          "William speaks five languages - English, French, German, Russian, and Japanese.",
          "I don't like my job. It's very demanding.",
          "‘Where's Sam?' ‘I'm sorry. I don't know.'",
          "Chloe is a very quiet person. She doesn't talk much.",
          "Ethan drinks a lot of herbal tea. It's his favourite drink.",
          "It's not true! I don't believe it!",
          "That's a very inspiring story. I like it very much.",
          "Grace is a vegetarian. She doesn't eat seafood.",
          "Lucas speaks two languages - English and Spanish.",
          "I don't like my office. It's very cold.",
          "‘Where's Mia?' ‘I'm sorry. I don't know.'",
          "Nathan is a very introverted person. He doesn't talk much.",
          "Lily drinks a lot of lemonade. It's her favourite drink.",
          "It's not true! I don't believe it!",
          "That's a very interesting documentary. I like it very much.",
          "Oliver is a vegan. He doesn't eat honey.",
          "Emma speaks four languages - English, Italian, French, and German.",
          "I don't like my commute. It's very long.",
          "‘Where's Ben?' ‘I'm sorry. I don't know.'",
          "Ava is a very reserved person. She doesn't talk much.",
          "Ryan drinks a lot of iced tea. It's his favourite drink.",
          "It's not true! I don't believe it!",
          "That's a very entertaining show. I like it very much.",
          "Ella is a pescatarian. She doesn't eat pork.",
          "Noah speaks three languages - English, Spanish, and French.",
          "I don't like my schedule. It's very hectic.",
          "‘Where's Zoe?' ‘I'm sorry. I don't know.'",
          "Leo is a very quiet person. He doesn't talk much.",
          "Mia drinks a lot of coconut water. It's her favourite drink.",
          "It's not true! I don't believe it!",
          "That's a very informative article. I like it very much.",
          "Jack is a vegetarian. He doesn't eat poultry.",
          "Lily speaks five languages - English, German, Spanish, Italian, and Portuguese.",
          "I don't like my routine. It's very monotonous.",
          "‘Where's Max?' ‘I'm sorry. I don't know.'",
          "Ava is a very introverted person. She doesn't talk much.",
          "Lucas drinks a lot of green tea. It's his favourite drink.",
          "It's not true! I don't believe it!",
          "That's a very thrilling book. I like it very much.",
          "Grace is a vegan. She doesn't eat cheese.",
          "Ethan speaks two languages - English and Japanese.",
          "I don't like my apartment. It's very dark.",
          "‘Where's Aiza?' ‘I'm sorry. I don't know.'",
          "Husnain is a very reserved person. She doesn't talk much.",
          "Taha drinks a lot of hot chocolate. It's his favourite drink.",
          "It's not true! I don't believe it!",
          "That's a very captivating story. I like it very much.",
          "Aima is a pescatarian. She doesn't eat beef.",
          "Amin speaks four languages - English, French, Spanish, and Russian.",
          "I don't like my neighborhood. It's very noisy.",
          "‘Where's Eman?' ‘I'm sorry. I don't know.'",
          "Husnain is a very quiet person. He doesn't talk much.",
          "Shahnila drinks a lot of chamomile tea. It's her favourite drink.",
          "It's not true! I don't believe it!",
          "That's a very fascinating documentary. I like it very much.",
          "Taha is a vegetarian. He doesn't eat lamb.",
          "Sarah speaks three languages - English, German, and Italian.",
          "I don't like my job. It's very repetitive.",
          "‘Where's Aima?' ‘I'm sorry. I don't know.'",
          "Laura is a very introverted person. She doesn't talk much."
        ]
        
      },
    ],
    "data set 6": [
      {
        name: "Positive" as const,
        sentence: [
          "He doesn't take exercise regularly.",
          "She doesn't always speak the truth.",
          "They don't do their own work.",
          "You don't go for a walk in the evening.",
          "I don't wish to meet him.",
          "We don't like boxing.",
          "The goat does not eat meat.",
          "He doesn't hate anyone.",
          "The girl doesn't call her mother.",
          "Horses don't run in the desert.",
          "We don't boast of our ability.",
          "We don't run this factory.",
          "Your brother doesn't look after the cow.",
          "Good boys don't abuse anyone.",
          "Good friends don't cheat.",
          "He doesn't repent for his sins.",
          "You don't admit your mistakes.",
          "Uninteresting books don't sell quickly.",
          "Stars don't appear during the day.",
          "He doesn't listen to me.",
          "I don't recognize this stranger.",
          "We don't know you.",
          "Not all boys are mischievous.",
          "A wise man doesn't make such mistakes.",
          "The sun doesn't revolve around the earth.",
          "The moon doesn't appear in the evening these days.",
          "Wood doesn't sink in water.",
          "A piece of iron doesn't float on water.",
          "Akbar doesn't save anything.",
          "We don't tease anyone without reason."
        ]
      },
    ],
  },
];

export default data;
