// data.ts
const data = [
  {
    name: "MySelf",
    "data set 1": [
      {
        name: "Positive" as const,
        sentence: [
          "Do you like chocolate?",
          "Do you play tennis?",
          "Does Lucy live near here?",
          "Do Tom’s friends play tennis?",
          "Does your brother speak English?",
          "Do you do yoga every morning?",
          "Does Paul go away a lot?",
          "Do you want to be famous?",
          "Does Anna work hard?",
          "Do you enjoy reading books?",
          "Does your sister play the piano?",
          "Do you watch movies often?",
          "Does John work at the bank?",
          "Do you like to travel?",
          "Does your friend speak French?",
          "Do you cook dinner every night?",
          "Does Sarah go to the gym?",
          "Do you have a pet?",
          "Does your father drive to work?",
          "Do you listen to music while studying?",
          "Does your neighbor have a garden?",
          "Do you drink coffee in the morning?",
          "Does your teacher give a lot of homework?",
          "Do you visit your grandparents often?",
          "Does your brother play video games?",
          "Do you like spicy food?",
          "Does your cousin live in the city?",
          "Do you go for a walk every evening?",
          "Does your boss travel for work?",
          "Do you enjoy painting?",
          "Does your friend like to dance?",
          "Do you play any musical instruments?",
          "Does your mother bake cakes?",
          "Do you go to the beach in summer?",
          "Does your uncle work in an office?",
          "Do you like to sing?",
          "Does your aunt teach at a school?",
          "Do you read the newspaper daily?",
          "Does your friend play soccer?",
          "Do you enjoy hiking?",
          "Does your sister like to swim?",
          "Do you write in a journal?",
          "Does your brother watch sports?",
          "Do you like to garden?",
          "Does your friend have a dog?",
          "Do you study late at night?",
          "Does your father like to fish?",
          "Do you play chess?",
          "Does your mother enjoy cooking?",
          "Do you go to the library often?",
          "Does your friend like to draw?",
          "Do you watch TV shows?",
          "Does your cousin play basketball?",
          "Do you like to sew?",
          "Does your neighbor have a cat?",
          "Do you go to concerts?",
          "Does your sister like to read?",
          "Do you enjoy photography?",
          "Does your brother play the guitar?",
          "Do you like to write stories?",
          "Does your friend enjoy camping?",
          "Do you play board games?",
          "Does your father like to travel?",
          "Do you go to the park?",
          "Does your mother enjoy gardening?",
          "Do you like to knit?",
          "Does your friend have a bicycle?",
          "Do you enjoy cooking?",
          "Does your sister play volleyball?",
          "Do you like to watch documentaries?",
          "Does your brother like to run?",
          "Do you go to the gym?",
          "Does your friend enjoy reading?",
          "Do you like to play cards?",
          "Does your father watch movies?",
          "Do you enjoy swimming?",
          "Does your mother like to walk?",
          "Do you play the piano?",
          "Does your friend like to cook?",
          "Do you like to travel by train?",
          "Does your sister enjoy hiking?",
          "Do you watch the news?",
          "Does your brother like to bike?",
          "Do you enjoy fishing?",
          "Does your friend have a pet?",
          "Do you like to play tennis?",
          "Does your father enjoy painting?",
          "Do you go to the theater?",
          "Does your mother like to sew?",
          "Do you enjoy playing sports?",
          "Does your sister like to dance?",
          "Do you like to read novels?",
          "Does your brother enjoy cooking?",
          "Do you play video games?",
          "Does your friend like to swim?",
          "Do you enjoy watching movies?",
          "Does your father like to garden?",
          "Do you go hiking?",
          "Does your mother enjoy knitting?",
          "Do you like to play soccer?",
          "Does your sister enjoy painting?",
          "Do you watch reality shows?",
          "Does your brother like to fish?",
          "Do you enjoy playing chess?",
          "Does your friend like to bike?",
          "Do you like to go camping?",
          "Does your father enjoy reading?",
          "Do you go to art galleries?",
          "Does your mother like to travel?"
        ]        
        },
    ],
    "data set 2": [
      {
        name: "Positive" as const,
        sentence: [
          "Where do your parents live?",
          "Do you always get up early?",
          "How often do you watch TV?",
          "What do you want for dinner?",
          "Do you like football?",
          "Does your brother like football?",
          "What do you do in your free time?",
          "Where does your sister work?",
          "Do you always have breakfast?",
          "What does this word mean?",
          "Does it snow here in winter?",
          "What time do you usually go to bed?",
          "How much does it cost to phone New York?",
          "What do you usually have for breakfast?",
          "Where do you work?",
          "Do you enjoy reading books?",
          "How often do you exercise?",
          "What do you like to do on weekends?",
          "Do you play any sports?",
          "Does your friend live nearby?",
          "What do you study at university?",
          "Where do you go for vacations?",
          "Do you drink coffee every morning?",
          "What does your name mean?",
          "Does it rain a lot in your city?",
          "What time do you start work?",
          "How much does a ticket to the concert cost?",
          "What do you usually eat for lunch?",
          "Where do you buy groceries?",
          "Do you like to cook?",
          "How often do you visit your family?",
          "What do you do for fun?",
          "Does your sister play any instruments?",
          "Where do you go for a walk?",
          "Do you enjoy watching movies?",
          "How often do you travel?",
          "What do you do on holidays?",
          "Does your brother work in an office?",
          "Where do you go to school?",
          "Do you like to swim?",
          "How often do you read the news?",
          "What do you do on your days off?",
          "Does your friend speak another language?",
          "Where do you go shopping?",
          "Do you enjoy hiking?",
          "How often do you clean your house?",
          "What do you do in the evenings?",
          "Does your father like to fish?",
          "Where do you spend your weekends?",
          "Do you like to paint?",
          "How often do you go to the gym?",
          "What do you do in the summer?",
          "Does your mother enjoy gardening?",
          "Where do you go for dinner?",
          "Do you enjoy playing games?",
          "How often do you call your friends?",
          "What do you do in the winter?",
          "Does your sister like to travel?",
          "Where do you go for entertainment?",
          "Do you like to dance?",
          "How often do you visit the library?",
          "What do you do on rainy days?",
          "Does your brother enjoy sports?",
          "Where do you go for exercise?",
          "Do you enjoy listening to music?",
          "How often do you go out with friends?",
          "What do you do on your birthday?",
          "Does your friend like to read?",
          "Where do you go for relaxation?",
          "Do you like to write?",
          "How often do you go to the beach?",
          "What do you do in your spare time?",
          "Does your father enjoy cooking?",
          "Where do you go for fun?",
          "Do you enjoy photography?",
          "How often do you visit museums?",
          "What do you do on weekends?",
          "Does your mother like to sew?",
          "Where do you go for a run?",
          "Do you like to knit?",
          "How often do you go to the park?",
          "What do you do in the morning?",
          "Does your sister enjoy painting?",
          "Where do you go for coffee?",
          "Do you enjoy baking?",
          "How often do you visit art galleries?",
          "What do you do in the afternoon?",
          "Does your brother like to bike?",
          "Where do you go for lunch?",
          "Do you like to draw?",
          "How often do you go to the theater?",
          "What do you do in the evening?",
          "Does your friend enjoy hiking?",
          "Where do you go for breakfast?",
          "Do you enjoy sewing?",
          "How often do you visit parks?",
          "What do you do on holidays?",
          "Does your father like to travel?",
          "Where do you go for walks?",
          "Do you like to play chess?",
          "How often do you go to concerts?",
          "What do you do in your free time?",
          "Does your mother enjoy knitting?",
          "Where do you go for shopping?",
          "Do you enjoy fishing?",
          "How often do you visit zoos?",
          "What do you do on weekends?",
          "Does your sister like to swim?",
          "Where do you go for vacations?",
          "Do you like to play cards?",
          "How often do you go to the movies?",
          "What do you do in your leisure time?",
          "Does your brother enjoy reading?",
          "Where do you go for picnics?"
        ]
        
         },
    ],
    "data set 3": [
      {
        name: "Positive" as const,
        sentence: [
          "What do you do? I work in a bookshop.",
          "Do you enjoy it? It’s OK.",
          "What time do you start in the morning? At 9 o’clock.",
          "Do you work on Saturdays? Sometimes.",
          "How do you go to work? Usually by bus.",
          "And your husband. What does he do? He’s a teacher.",
          "What does he teach? Science.",
          "Does he like his job? Yes, he loves it.",
          "What do you do? I work in a library.",
          "Do you enjoy it? It’s interesting.",
          "What time do you start in the morning? At 8 o’clock.",
          "Do you work on Sundays? Rarely.",
          "How do you commute to work? By train.",
          "And your wife. What does she do? She’s a nurse.",
          "What does she specialize in? Pediatrics.",
          "Does she like her job? Yes, she finds it rewarding.",
          "What do you do? I work in a cafe.",
          "Do you enjoy it? It’s fun.",
          "What time do you start in the morning? At 7 o’clock.",
          "Do you work on weekends? Occasionally.",
          "How do you get to work? By bike.",
          "And your partner. What does he do? He’s a chef.",
          "What does he cook? Italian cuisine.",
          "Does he like his job? Yes, he loves it.",
          "What do you do? I work in a hospital.",
          "Do you enjoy it? It’s challenging.",
          "What time do you start in the morning? At 6 o’clock.",
          "Do you work on holidays? Sometimes.",
          "How do you travel to work? By car.",
          "And your friend. What does she do? She’s a lawyer.",
          "What does she practice? Corporate law.",
          "Does she like her job? Yes, she enjoys it.",
          "What do you do? I work in a school.",
          "Do you enjoy it? It’s fulfilling.",
          "What time do you start in the morning? At 8:30.",
          "Do you work on public holidays? No.",
          "How do you get to work? By bus.",
          "And your sibling. What does he do? He’s an engineer.",
          "What does he design? Bridges.",
          "Does he like his job? Yes, he finds it exciting.",
          "What do you do? I work in a factory.",
          "Do you enjoy it? It’s okay.",
          "What time do you start in the morning? At 7:30.",
          "Do you work on Saturdays? Occasionally.",
          "How do you go to work? By motorcycle.",
          "And your cousin. What does she do? She’s a journalist.",
          "What does she cover? Politics.",
          "Does she like her job? Yes, she loves it.",
          "What do you do? I work in a bank.",
          "Do you enjoy it? It’s good.",
          "What time do you start in the morning? At 9:30.",
          "Do you work on weekends? No.",
          "How do you commute to work? By subway.",
          "And your neighbor. What does he do? He’s a firefighter.",
          "What does he do? He saves lives.",
          "Does he like his job? Yes, he finds it rewarding.",
          "What do you do? I work in a restaurant.",
          "Do you enjoy it? It’s busy.",
          "What time do you start in the morning? At 10 o’clock.",
          "Do you work on holidays? Yes.",
          "How do you get to work? By foot.",
          "And your friend. What does she do? She’s a photographer.",
          "What does she photograph? Weddings.",
          "Does she like her job? Yes, she enjoys it.",
          "What do you do? I work in a hotel.",
          "Do you enjoy it? It’s nice.",
          "What time do you start in the morning? At 6:30.",
          "Do you work on weekends? Yes.",
          "How do you travel to work? By taxi.",
          "And your partner. What does he do? He’s a musician.",
          "What does he play? The guitar.",
          "Does he like his job? Yes, he loves it.",
          "What do you do? I work in a supermarket.",
          "Do you enjoy it? It’s fine.",
          "What time do you start in the morning? At 7 o’clock.",
          "Do you work on public holidays? Sometimes.",
          "How do you get to work? By bus.",
          "And your friend. What does he do? He’s a doctor.",
          "What does he specialize in? Cardiology.",
          "Does he like his job? Yes, he finds it fulfilling.",
          "What do you do? I work in a pharmacy.",
          "Do you enjoy it? It’s okay.",
          "What time do you start in the morning? At 8:30.",
          "Do you work on weekends? Occasionally.",
          "How do you commute to work? By car.",
          "And your sibling. What does she do? She’s a scientist.",
          "What does she research? Genetics.",
          "Does she like her job? Yes, she loves it.",
          "What do you do? I work in a museum.",
          "Do you enjoy it? It’s interesting.",
          "What time do you start in the morning? At 9 o’clock.",
          "Do you work on holidays? Rarely.",
          "How do you get to work? By bike.",
          "And your cousin. What does he do? He’s an artist.",
          "What does he create? Paintings.",
          "Does he like his job? Yes, he enjoys it.",
          "What do you do? I work in a theater.",
          "Do you enjoy it? It’s fun.",
          "What time do you start in the morning? At 10 o’clock.",
          "Do you work on weekends? Yes.",
          "How do you travel to work? By train.",
          "And your neighbor. What does she do? She’s a writer.",
          "What does she write? Novels.",
          "Does she like her job? Yes, she loves it.",
          "What do you do? I work in a gym.",
          "Do you enjoy it? It’s great.",
          "What time do you start in the morning? At 5 o’clock.",
          "Do you work on public holidays? Sometimes.",
          "How do you get to work? By car.",
          "And your friend. What does he do? He’s a pilot.",
          "What does he fly? Airplanes.",
          "Does he like his job? Yes, he finds it exciting."
        ]        
        },
    ],
    "data set 4": [
      {
        name: "Positive" as const,
        sentence: [
          "Do you watch TV a lot? No, I don’t.",
          "Do you live in a big city? Yes, I do.",
          "Do you often ride a bike? No, I don’t.",
          "Does it rain a lot where you live? Yes, it does.",
          "Do you play the piano? No, I don’t.",
          "Do you like coffee? Yes, I do.",
          "Do you read books often? No, I don’t.",
          "Does your friend play soccer? Yes, he does.",
          "Do you enjoy cooking? Yes, I do.",
          "Does your sister sing? No, she doesn’t.",
          "Do you travel frequently? No, I don’t.",
          "Does your brother work out? Yes, he does.",
          "Do you like spicy food? Yes, I do.",
          "Does it snow in winter? Yes, it does.",
          "Do you go to the gym? No, I don’t.",
          "Does your father drive? Yes, he does.",
          "Do you like to swim? No, I don’t.",
          "Does your mother bake? Yes, she does.",
          "Do you play chess? No, I don’t.",
          "Does your friend like hiking? Yes, she does.",
          "Do you watch movies? Yes, I do.",
          "Does your cousin live nearby? No, he doesn’t.",
          "Do you enjoy painting? No, I don’t.",
          "Does your neighbor have a dog? Yes, he does.",
          "Do you like to dance? Yes, I do.",
          "Does your teacher give homework? Yes, she does.",
          "Do you play video games? No, I don’t.",
          "Does your friend speak Spanish? Yes, he does.",
          "Do you like to read? Yes, I do.",
          "Does your sister play the guitar? No, she doesn’t.",
          "Do you go for walks? Yes, I do.",
          "Does your brother like fishing? Yes, he does.",
          "Do you enjoy gardening? No, I don’t.",
          "Does your friend visit often? Yes, she does.",
          "Do you like to travel? Yes, I do.",
          "Does your father watch sports? Yes, he does.",
          "Do you play basketball? No, I don’t.",
          "Does your mother like knitting? Yes, she does.",
          "Do you enjoy writing? Yes, I do.",
          "Does your friend have a cat? No, he doesn’t.",
          "Do you like to sew? No, I don’t.",
          "Does your sister enjoy yoga? Yes, she does.",
          "Do you go to the beach? Yes, I do.",
          "Does your brother play tennis? No, he doesn’t.",
          "Do you like to draw? Yes, I do.",
          "Does your friend like to cook? Yes, she does.",
          "Do you enjoy fishing? No, I don’t.",
          "Does your father read the newspaper? Yes, he does.",
          "Do you play any instruments? No, I don’t.",
          "Does your mother enjoy walking? Yes, she does.",
          "Do you like to knit? No, I don’t.",
          "Does your friend go to the gym? Yes, he does.",
          "Do you enjoy photography? Yes, I do.",
          "Does your sister like to swim? Yes, she does.",
          "Do you go to concerts? No, I don’t.",
          "Does your brother enjoy running? Yes, he does.",
          "Do you like to bake? Yes, I do.",
          "Does your friend play the piano? No, she doesn’t.",
          "Do you enjoy hiking? Yes, I do.",
          "Does your father like gardening? Yes, he does.",
          "Do you play soccer? No, I don’t.",
          "Does your mother enjoy painting? Yes, she does.",
          "Do you like to write? Yes, I do.",
          "Does your friend like to read? Yes, he does.",
          "Do you enjoy camping? No, I don’t.",
          "Does your sister play volleyball? Yes, she does.",
          "Do you go to the library? Yes, I do.",
          "Does your brother like to bike? Yes, he does.",
          "Do you like to cook? Yes, I do.",
          "Does your friend enjoy dancing? Yes, she does.",
          "Do you play golf? No, I don’t.",
          "Does your father like fishing? Yes, he does.",
          "Do you enjoy reading? Yes, I do.",
          "Does your mother like to travel? Yes, she does.",
          "Do you like to swim? Yes, I do.",
          "Does your friend play chess? No, he doesn’t.",
          "Do you enjoy playing sports? Yes, I do.",
          "Does your sister like to draw? Yes, she does.",
          "Do you go hiking? Yes, I do.",
          "Does your brother enjoy cooking? Yes, he does.",
          "Do you like to garden? No, I don’t.",
          "Does your friend enjoy painting? Yes, she does.",
          "Do you play the violin? No, I don’t.",
          "Does your father like to read? Yes, he does.",
          "Do you enjoy sewing? No, I don’t.",
          "Does your mother like to knit? Yes, she does.",
          "Do you like to travel? Yes, I do.",
          "Does your friend play basketball? No, he doesn’t.",
          "Do you enjoy watching TV? Yes, I do.",
          "Does your sister like to sing? Yes, she does.",
          "Do you go to the park? Yes, I do.",
          "Does your brother enjoy hiking? Yes, he does.",
          "Do you like to play cards? No, I don’t.",
          "Does your friend enjoy swimming? Yes, she does.",
          "Do you play the drums? No, I don’t.",
          "Does your father like to cook? Yes, he does.",
          "Do you enjoy knitting? No, I don’t.",
          "Does your mother like to sew? Yes, she does.",
          "Do you like to read books? Yes, I do.",
          "Does your friend play golf? No, he doesn’t.",
          "Do you enjoy playing chess? Yes, I do.",
          "Does your sister like to bike? Yes, she does.",
          "Do you go to the gym? Yes, I do.",
          "Does your brother enjoy fishing? Yes, he does.",
          "Do you like to paint? Yes, I do."
        ]
        
      },
    ],
    "data set 5": [
      {
        name: "Positive" as const,
        sentence: [
          "Sue always gets to work early.",
          "We don’t watch TV very often.",
          "How often do you wash your hair?",
          "I want to go to the cinema, but Sam doesn’t want to go.",
          "Do you want to go out tonight?",
          "Does Helen live near here?",
          "Sarah knows a lot of people.",
          "I enjoy travelling, but I don’t travel very much.",
          "What time do you usually get up in the morning?",
          "My parents are usually at home in the evening. They don’t go out very often.",
          "Tom always finishes work at five o’clock.",
          "What does Jessica do? She works in a hotel.",
          "John always arrives at the office early.",
          "We don’t eat out very often.",
          "How often do you visit your grandparents?",
          "I want to read a book, but Mary doesn’t want to read.",
          "Do you like to play chess?",
          "Does Mike live in this neighborhood?",
          "Emily knows many languages.",
          "I enjoy cooking, but I don’t cook very often.",
          "What time do you usually go to bed?",
          "My friends are usually busy on weekends. They don’t relax very often.",
          "Anna always finishes her homework on time.",
          "What does Mark do? He works in a bank.",
          "Jane always brings lunch from home.",
          "We don’t go to the movies very often.",
          "How often do you exercise?",
          "I want to go hiking, but Tom doesn’t want to go.",
          "Do you enjoy reading novels?",
          "Does Lisa work at the hospital?",
          "David knows a lot about history.",
          "I enjoy painting, but I don’t paint very much.",
          "What time do you usually leave for work?",
          "My neighbors are usually quiet in the evening. They don’t make noise very often.",
          "Paul always completes his projects early.",
          "What does Sarah do? She works in a school.",
          "Mike always takes the bus to work.",
          "We don’t travel abroad very often.",
          "How often do you call your parents?",
          "I want to learn Spanish, but John doesn’t want to learn.",
          "Do you like to swim?",
          "Does Anna live with her parents?",
          "Kevin knows a lot about computers.",
          "I enjoy writing, but I don’t write very often.",
          "What time do you usually have dinner?",
          "My colleagues are usually helpful. They don’t complain very often.",
          "Lisa always finishes her tasks before the deadline.",
          "What does Peter do? He works in a factory.",
          "Susan always drinks coffee in the morning.",
          "We don’t visit the park very often.",
          "How often do you go shopping?",
          "I want to play tennis, but Sarah doesn’t want to play.",
          "Do you enjoy watching documentaries?",
          "Does Tom work in an office?",
          "Rachel knows a lot about art.",
          "I enjoy jogging, but I don’t jog very much.",
          "What time do you usually start your day?",
          "My family is usually together on holidays. They don’t travel very often.",
          "Steve always finishes his chores quickly.",
          "What does Laura do? She works in a restaurant.",
          "James always reads the newspaper in the morning.",
          "We don’t go to the beach very often.",
          "How often do you visit museums?",
          "I want to go cycling, but Mike doesn’t want to go.",
          "Do you like to play the guitar?",
          "Does Emma live in the city?",
          "Chris knows a lot about science.",
          "I enjoy baking, but I don’t bake very often.",
          "What time do you usually go to the gym?",
          "My friends are usually busy during the week. They don’t hang out very often.",
          "Karen always finishes her work early.",
          "What does David do? He works in a library.",
          "Alice always takes a walk in the evening.",
          "We don’t eat fast food very often.",
          "How often do you read books?",
          "I want to go fishing, but John doesn’t want to go.",
          "Do you enjoy playing board games?",
          "Does Lisa work at the university?",
          "Michael knows a lot about music.",
          "I enjoy knitting, but I don’t knit very much.",
          "What time do you usually have breakfast?",
          "My neighbors are usually friendly. They don’t argue very often.",
          "Tom always finishes his reports on time.",
          "What does Emily do? She works in a clinic.",
          "Robert always listens to the radio in the morning.",
          "We don’t go hiking very often.",
          "How often do you visit the zoo?",
          "I want to go dancing, but Sarah doesn’t want to go.",
          "Do you like to play basketball?",
          "Does Anna live alone?",
          "Kevin knows a lot about technology.",
          "I enjoy sewing, but I don’t sew very often.",
          "What time do you usually leave the house?",
          "My colleagues are usually punctual. They don’t arrive late very often.",
          "Lisa always finishes her assignments early.",
          "What does Mark do? He works in a pharmacy.",
          "Susan always drinks tea in the afternoon.",
          "We don’t go to the theater very often.",
          "How often do you go to the gym?",
          "I want to go running, but Tom doesn’t want to go.",
          "Do you enjoy listening to music?",
          "Does Mike work at the store?",
          "Rachel knows a lot about literature.",
          "I enjoy drawing, but I don’t draw very much.",
          "What time do you usually go to sleep?",
          "My family is usually home on weekends. They don’t go out very often.",
          "Steve always finishes his meals quickly.",
          "What does Laura do? She works in a bakery.",
          "James always reads a book before bed.",
          "We don’t go skiing very often.",
          "How often do you visit the countryside?",
          "I want to go kayaking, but Sarah doesn’t want to go."
        ]        
      },
    ],
    "data set 6": [
      {
        name: "Positive" as const,
        sentence: [
          "What’s your name? Ben.",
          "Are you married? Yes, I am.",
          "Where do you live? In Barton Road.",
          "Do you have any children? Yes, a daughter.",
          "How old is she? She’s three.",
          "How old are you? I’m 29.",
          "What is your job? I work in a supermarket.",
          "Do you like your job? No, I hate it.",
          "Do you have a car? Yes, I have.",
          "Do you go to work by car? No, I usually go by bus.",
          "Who is this man? That’s my brother.",
          "What is his name? Michael.",
          "What does he do? He’s a travel agent.",
          "Does he live here? No, in Manchester.",
          "What’s your name? Sarah.",
          "Are you single? Yes, I am.",
          "Where do you work? In a bank.",
          "Do you have any pets? Yes, a dog.",
          "How old is he? He’s five.",
          "How old are you? I’m 32.",
          "What is your profession? I’m a teacher.",
          "Do you enjoy your job? Yes, I love it.",
          "Do you own a house? No, I rent.",
          "Do you drive to work? No, I walk.",
          "Who is this woman? That’s my sister.",
          "What is her name? Emily.",
          "What does she do? She’s a nurse.",
          "Does she live nearby? Yes, she does.",
          "What’s your name? John.",
          "Are you employed? Yes, I am.",
          "Where do you study? At university.",
          "Do you have siblings? Yes, a brother.",
          "How old is he? He’s ten.",
          "How old are you? I’m 25.",
          "What is your occupation? I’m an engineer.",
          "Do you like your work? Yes, it’s interesting.",
          "Do you have a bicycle? Yes, I do.",
          "Do you cycle to work? No, I take the bus.",
          "Who is this child? That’s my son.",
          "What is his name? Alex.",
          "What does he like? He likes cars.",
          "Does he go to school? Yes, he does.",
          "What’s your name? Lisa.",
          "Are you a student? Yes, I am.",
          "Where do you shop? At the mall.",
          "Do you have a hobby? Yes, painting.",
          "How old is your cat? She’s two.",
          "How old are you? I’m 28.",
          "What is your job? I’m a designer.",
          "Do you enjoy designing? Yes, very much.",
          "Do you have a garden? Yes, I do.",
          "Do you work from home? Yes, I do.",
          "Who is this person? That’s my friend.",
          "What is her name? Rachel.",
          "What does she study? She studies law.",
          "Does she live alone? No, with her parents.",
          "What’s your name? Mark.",
          "Are you retired? Yes, I am.",
          "Where do you travel? Around the world.",
          "Do you have grandchildren? Yes, three.",
          "How old are they? They’re six, eight, and ten.",
          "How old are you? I’m 65.",
          "What was your profession? I was a doctor.",
          "Did you like your job? Yes, I did.",
          "Do you have a hobby? Yes, gardening.",
          "Do you travel often? Yes, I do.",
          "Who is this lady? That’s my wife.",
          "What is her name? Linda.",
          "What does she enjoy? She enjoys reading.",
          "Does she travel with you? Yes, she does.",
          "What’s your name? Emma.",
          "Are you a teacher? Yes, I am.",
          "Where do you teach? At a high school.",
          "Do you have a car? Yes, I do.",
          "How old is your car? It’s three years old.",
          "How old are you? I’m 40.",
          "What is your subject? I teach math.",
          "Do you like teaching? Yes, I do.",
          "Do you have a pet? Yes, a parrot.",
          "Do you drive to school? Yes, I do.",
          "Who is this girl? That’s my daughter.",
          "What is her name? Sophie.",
          "What does she play? She plays the piano.",
          "Does she like music? Yes, she does.",
          "What’s your name? David.",
          "Are you a manager? Yes, I am.",
          "Where do you work? In an office.",
          "Do you have a family? Yes, a wife and two kids.",
          "How old are your kids? They’re four and seven.",
          "How old are you? I’m 38.",
          "What is your role? I manage a team.",
          "Do you enjoy managing? Yes, it’s rewarding.",
          "Do you have a hobby? Yes, fishing.",
          "Do you work long hours? Yes, I do.",
          "Who is this boy? That’s my nephew.",
          "What is his name? Jack.",
          "What does he like? He likes sports.",
          "Does he play soccer? Yes, he does.",
          "What’s your name? Olivia.",
          "Are you a nurse? Yes, I am.",
          "Where do you work? In a hospital.",
          "Do you have a partner? Yes, I do.",
          "How old is he? He’s 35.",
          "How old are you? I’m 30.",
          "What is your specialty? I work in pediatrics.",
          "Do you like your job? Yes, I love it.",
          "Do you have a pet? Yes, a rabbit.",
          "Do you work night shifts? Sometimes, yes.",
          "Who is this man? That’s my father.",
          "What is his name? Robert.",
          "What does he do? He’s retired.",
          "Does he live with you? No, he lives nearby.",
          "What’s your name? James.",
          "Are you a chef? Yes, I am.",
          "Where do you cook? In a restaurant.",
          "Do you have children? Yes, a son.",
          "How old is he? He’s eight.",
          "How old are you? I’m 35.",
          "What is your specialty? I cook Italian food.",
          "Do you enjoy cooking? Yes, very much.",
          "Do you have a hobby? Yes, playing guitar.",
          "Do you work late hours? Yes, I do.",
          "Who is this woman? That’s my mother.",
          "What is her name? Grace.",
          "What does she like? She likes gardening.",
          "Does she live with you? No, she lives in another city."
        ]
        
      },
    ],
    "data set 7": [
      {
        name: "Positive" as const,
        sentence: [
          "Where do children play hide and seek?",
          "When does the postman come to this street?",
          "Why do you object to his stay here?",
          "Does the cloud thunder loudly?",
          "Does it hail in the summer?",
          "Why does he spend more than his income?",
          "Does he feel ashamed of what he did?",
          "Does Bashir wander till late night?",
          "How long does Naseema stay at her uncle’s place?",
          "Where does the army encamp?",
          "Do you prefer fruits over sweets?",
          "Do people consider time important?",
          "Why do these students waste time?",
          "When does the rooster crow?",
          "Does your daughter respect elders?",
          "Does he demand a reasonable price for the fox?",
          "Why does the cloth merchant give short measure?",
          "Do all students collect postage stamps?",
          "Does a rich man spend lavishly?",
          "Why do you insist on buying a bicycle?",
          "Does this girl sleep late at night?",
          "When do birds chirp?",
          "Why do people sing and dance at the Urs?",
          "Do they not care for anyone?",
          "Do you dream of any kind?",
          "Why don’t you show me your translation exercises?",
          "Does he admit his mistake?",
          "Does this class take interest in their work?",
          "Does it only rain in summer in Pakistan?",
          "In which season does it snow on the mountains?"
        ]
        
      },
    ],
  },
];

export default data;
